/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Map;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class AgrupadorDTO {

    @SerializedName("resultado")
    private Map<String, ResultadoPesquisaPaginadaDTOSerializable> resultado = null;
    @SerializedName("pageSize")
    private Integer pageSize = null;

    /**
     * Registros relacionados com a consulta. A chave é a modalidade, o value é um ResultadoPesquisaPaginadaDTO
     **/
    @ApiModelProperty(value = "Registros relacionados com a consulta. A chave é a modalidade, o value é um ResultadoPesquisaPaginadaDTO")
    public Map<String, ResultadoPesquisaPaginadaDTOSerializable> getResultado() {
        return resultado;
    }

    public void setResultado(Map<String, ResultadoPesquisaPaginadaDTOSerializable> resultado) {
        this.resultado = resultado;
    }

    /**
     * Quantidade de páginas para apresentação do resultado da consulta
     **/
    @ApiModelProperty(value = "Quantidade de páginas para apresentação do resultado da consulta")
    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgrupadorDTO agrupadorDTO = (AgrupadorDTO) o;
        return (this.resultado == null ? agrupadorDTO.resultado == null : this.resultado.equals(agrupadorDTO.resultado)) &&
                (this.pageSize == null ? agrupadorDTO.pageSize == null : this.pageSize.equals(agrupadorDTO.pageSize));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.resultado == null ? 0 : this.resultado.hashCode());
        result = 31 * result + (this.pageSize == null ? 0 : this.pageSize.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class AgrupadorDTO {\n" +
                "  resultado: " + resultado + "\n" +
                "  pageSize: " + pageSize + "\n" +
                "}\n";
        return sb;
    }
}
