/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ApostadorAlteracaoDTO {

    @SerializedName("cep")
    private String cep = null;
    @SerializedName("municipioId")
    private MunicipioIdDTO municipioId = null;
    @SerializedName("lotericaId")
    private Long lotericaId = null;
    public enum SexoEnum {
        F,  M,
    };
    @SerializedName("sexo")
    private SexoEnum sexo = null;
    @SerializedName("alterandoLoterica")
    private Boolean alterandoLoterica = null;
    @SerializedName("limiteDiario")
    private BigDecimal limiteDiario = null;
    @SerializedName("aceitaReceberNoticias")
    private Boolean aceitaReceberNoticias = null;

    /**
     * CEP relacionado com o endereço do apostador
     **/
    @ApiModelProperty(required = true, value = "CEP relacionado com o endereço do apostador")
    public String getCep() {
        return cep;
    }
    public void setCep(String cep) {
        this.cep = cep;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public MunicipioIdDTO getMunicipioId() {
        return municipioId;
    }
    public void setMunicipioId(MunicipioIdDTO municipioId) {
        this.municipioId = municipioId;
    }

    /**
     * Identificação da Unidade Lotérica de Vinculação do Apostador
     **/
    @ApiModelProperty(required = true, value = "Identificação da Unidade Lotérica de Vinculação do Apostador")
    public Long getLotericaId() {
        return lotericaId;
    }
    public void setLotericaId(Long lotericaId) {
        this.lotericaId = lotericaId;
    }

    /**
     * Sexo do apostador
     **/
    @ApiModelProperty(required = true, value = "Sexo do apostador")
    public SexoEnum getSexo() {
        return sexo;
    }
    public void setSexo(SexoEnum sexo) {
        this.sexo = sexo;
    }

    /**
     * Se a lotérica do apostador está sendo alterada
     **/
    @ApiModelProperty(value = "Se a lotérica do apostador está sendo alterada")
    public Boolean getAlterandoLoterica() {
        return alterandoLoterica;
    }
    public void setAlterandoLoterica(Boolean alterandoLoterica) {
        this.alterandoLoterica = alterandoLoterica;
    }

    /**
     * Alterar recebimento ou não de notícias
     */
    public void setAceitaReceberNoticias(Boolean aceitaReceberNoticias){
        this.aceitaReceberNoticias = aceitaReceberNoticias;
    }

    /**
     * Limite Diário de apostas
     **/
    @ApiModelProperty(value = "Limite Diário de apostas")
    public BigDecimal getLimiteDiario() {
        return limiteDiario;
    }
    public void setLimiteDiario(BigDecimal limiteDiario) {
        this.limiteDiario = limiteDiario;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApostadorAlteracaoDTO apostadorAlteracaoDTO = (ApostadorAlteracaoDTO) o;
        return (this.cep == null ? apostadorAlteracaoDTO.cep == null : this.cep.equals(apostadorAlteracaoDTO.cep)) &&
                (this.municipioId == null ? apostadorAlteracaoDTO.municipioId == null : this.municipioId.equals(apostadorAlteracaoDTO.municipioId)) &&
                (this.lotericaId == null ? apostadorAlteracaoDTO.lotericaId == null : this.lotericaId.equals(apostadorAlteracaoDTO.lotericaId)) &&
                (this.sexo == null ? apostadorAlteracaoDTO.sexo == null : this.sexo.equals(apostadorAlteracaoDTO.sexo)) &&
                (this.alterandoLoterica == null ? apostadorAlteracaoDTO.alterandoLoterica == null : this.alterandoLoterica.equals(apostadorAlteracaoDTO.alterandoLoterica)) &&
                (this.limiteDiario == null ? apostadorAlteracaoDTO.limiteDiario == null : this.limiteDiario.equals(apostadorAlteracaoDTO.limiteDiario));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.cep == null ? 0: this.cep.hashCode());
        result = 31 * result + (this.municipioId == null ? 0: this.municipioId.hashCode());
        result = 31 * result + (this.lotericaId == null ? 0: this.lotericaId.hashCode());
        result = 31 * result + (this.sexo == null ? 0: this.sexo.hashCode());
        result = 31 * result + (this.alterandoLoterica == null ? 0: this.alterandoLoterica.hashCode());
        result = 31 * result + (this.limiteDiario == null ? 0: this.limiteDiario.hashCode());
        return result;
    }

    @Override
    public String toString()  {

        String sb = "class ApostadorAlteracaoDTO {\n" +
                "  cep: " + cep + "\n" +
                "  municipioId: " + municipioId + "\n" +
                "  lotericaId: " + lotericaId + "\n" +
                "  sexo: " + sexo + "\n" +
                "  alterandoLoterica: " + alterandoLoterica + "\n" +
                "  limiteDiario: " + limiteDiario + "\n" +
                "}\n";
        return sb;
    }
}