/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

@ApiModel(description = "")
public class ApostadorDTO {

    @SerializedName("cpf")
    private String cpf = null;
    @SerializedName("email")
    private String email = null;
    @SerializedName("nome")
    private String nome = null;
    @SerializedName("dataNascimento")
    private String dataNascimento = null;
    @SerializedName("telefone")
    private TelefoneDTO telefone = null;
    @SerializedName("cep")
    private String cep = null;
    @SerializedName("aceitaTermosUso")
    private Boolean aceitaTermosUso = null;
    @SerializedName("aceitaReceberNoticias")
    private Boolean aceitaReceberNoticias = null;
    @SerializedName("municipioId")
    private MunicipioIdDTO municipioId = null;
    @SerializedName("lotericaId")
    private Long lotericaId = null;
    public enum SexoEnum {
        M,  F,
    };
    @SerializedName("sexo")
    private SexoEnum sexo = null;
    @SerializedName("mercadoPagoCustomerId")
    private String mercadoPagoCustomerId = null;
    @SerializedName("apostas")
    private List<ApostaDTO> apostas = null;
    @SerializedName("limiteMinimoDiario")
    private BigDecimal limiteMinimoDiario = null;
    @SerializedName("limiteDiario")
    private BigDecimal limiteDiario = null;
    @SerializedName("limiteDiarioAutorizado")
    private BigDecimal limiteDiarioAutorizado = null;

    /**
     * CPF relacionado com o apostador
     **/
    @ApiModelProperty(value = "CPF relacionado com o apostador")
    public String getCpf() {
        return cpf;
    }
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * Email para acesso ao site, relacionado com o apostador
     **/
    @ApiModelProperty(value = "Email para acesso ao site, relacionado com o apostador")
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Nome do Apostador, conforme nome cadastrado no SICPF
     **/
    @ApiModelProperty(value = "Nome do Apostador, conforme nome cadastrado no SICPF")
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * Data de Nascimento do apostador, que deve obrigatoriamente ser maior de 18 anos
     **/
    @ApiModelProperty(value = "Data de Nascimento do apostador, que deve obrigatoriamente ser maior de 18 anos")
    public String getDataNascimento() {
        return dataNascimento;
    }
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    /** **/
    @ApiModelProperty(required = true, value = "")
    public TelefoneDTO getTelefone() {
        return telefone;
    }
    public void setTelefone(TelefoneDTO telefone) {
        this.telefone = telefone;
    }

    /**
     * CEP do endereço do apostador
     **/
    @ApiModelProperty(value = "CEP do endereço do apostador")
    public String getCep() {
        return cep;
    }
    public void setCep(String cep) {
        this.cep = cep;
    }

    /**
     * Identifica se o apostador aceitou o termo de uso vigente
     **/
    @ApiModelProperty(required = true, value = "Identifica se o apostador aceitou o termo de uso vigente")
    public Boolean getAceitaTermosUso() {
        return aceitaTermosUso;
    }
    public void setAceitaTermosUso(Boolean aceitaTermosUso) {
        this.aceitaTermosUso = aceitaTermosUso;
    }

    /**
     * Identifica se o aposta selecionou a opção para receber noticias
     **/
    @ApiModelProperty(required = true, value = "Identifica se o aposta selecionou a opção para receber noticias")
    public Boolean getAceitaReceberNoticias() {
        return aceitaReceberNoticias;
    }
    public void setAceitaReceberNoticias(Boolean aceitaReceberNoticias) {
        this.aceitaReceberNoticias = aceitaReceberNoticias;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public MunicipioIdDTO getMunicipioId() {
        return municipioId;
    }
    public void setMunicipioId(MunicipioIdDTO municipioId) {
        this.municipioId = municipioId;
    }

    /**
     * Código da Lotérica de Vinculação do Apostador, selecionada no seu cadastro
     **/
    @ApiModelProperty(value = "Código da Lotérica de Vinculação do Apostador, selecionada no seu cadastro")
    public Long getLotericaId() {
        return lotericaId;
    }
    public void setLotericaId(Long lotericaId) {
        this.lotericaId = lotericaId;
    }

    /**
     * Sexo do Apostador
     **/
    @ApiModelProperty(required = true, value = "Sexo do Apostador")
    public SexoEnum getSexo() {
        return sexo;
    }
    public void setSexo(SexoEnum sexo) {
        this.sexo = sexo;
    }

    /**
     * Identificação do Apostador no Mercado Pago
     **/
    @ApiModelProperty(value = "Identificação do Apostador no Mercado Pago")
    public String getMercadoPagoCustomerId() {
        return mercadoPagoCustomerId;
    }
    public void setMercadoPagoCustomerId(String mercadoPagoCustomerId) {
        this.mercadoPagoCustomerId = mercadoPagoCustomerId;
    }

    /**
     * Apostas que estão na sessão
     **/
    @ApiModelProperty(value = "Apostas que estão na sessão")
    public List<ApostaDTO> getApostas() {
        return apostas;
    }
    public void setApostas(List<ApostaDTO> apostas) {
        this.apostas = apostas;
    }

    /**
     * Valor do limite mínimo diário de apostas, é o valor mínimo que o limiteDiario pode ser reduzido pelo Apostador
     **/
    @ApiModelProperty(value = "Valor do limite mínimo diário de apostas, é o valor mínimo que o limiteDiario pode ser reduzido pelo Apostador")
    public BigDecimal getLimiteMinimoDiario() {
        return limiteMinimoDiario;
    }
    public void setLimiteMinimoDiario(BigDecimal limiteMinimoDiario) {
        this.limiteMinimoDiario = limiteMinimoDiario;
    }

    /**
     * Valor do limite diário de apostas para este apostador
     **/
    @ApiModelProperty(value = "Valor do limite diário de apostas para este apostador")
    public BigDecimal getLimiteDiario() {
        return limiteDiario;
    }
    public void setLimiteDiario(BigDecimal limiteDiario) {
        this.limiteDiario = limiteDiario;
    }

    /**
     * Valor do limite diário autorizado, é o valor máximo que o limiteDiario pode ser aumentado pelo Apostador.
     **/
    @ApiModelProperty(value = "Valor do limite diário autorizado, é o valor máximo que o limiteDiario pode ser aumentado pelo Apostador.")
    public BigDecimal getLimiteDiarioAutorizado() {
        return limiteDiarioAutorizado;
    }
    public void setLimiteDiarioAutorizado(BigDecimal limiteDiarioAutorizado) {
        this.limiteDiarioAutorizado = limiteDiarioAutorizado;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApostadorDTO apostadorDTO = (ApostadorDTO) o;
        return (this.cpf == null ? apostadorDTO.cpf == null : this.cpf.equals(apostadorDTO.cpf)) &&
                (this.email == null ? apostadorDTO.email == null : this.email.equals(apostadorDTO.email)) &&
                (this.nome == null ? apostadorDTO.nome == null : this.nome.equals(apostadorDTO.nome)) &&
                (this.dataNascimento == null ? apostadorDTO.dataNascimento == null : this.dataNascimento.equals(apostadorDTO.dataNascimento)) &&
                (this.telefone == null ? apostadorDTO.telefone == null : this.telefone.equals(apostadorDTO.telefone)) &&
                (this.cep == null ? apostadorDTO.cep == null : this.cep.equals(apostadorDTO.cep)) &&
                (this.aceitaTermosUso == null ? apostadorDTO.aceitaTermosUso == null : this.aceitaTermosUso.equals(apostadorDTO.aceitaTermosUso)) &&
                (this.aceitaReceberNoticias == null ? apostadorDTO.aceitaReceberNoticias == null : this.aceitaReceberNoticias.equals(apostadorDTO.aceitaReceberNoticias)) &&
                (this.municipioId == null ? apostadorDTO.municipioId == null : this.municipioId.equals(apostadorDTO.municipioId)) &&
                (this.lotericaId == null ? apostadorDTO.lotericaId == null : this.lotericaId.equals(apostadorDTO.lotericaId)) &&
                (this.sexo == null ? apostadorDTO.sexo == null : this.sexo.equals(apostadorDTO.sexo)) &&
                (this.mercadoPagoCustomerId == null ? apostadorDTO.mercadoPagoCustomerId == null : this.mercadoPagoCustomerId.equals(apostadorDTO.mercadoPagoCustomerId)) &&
                (this.apostas == null ? apostadorDTO.apostas == null : this.apostas.equals(apostadorDTO.apostas)) &&
                (this.limiteMinimoDiario == null ? apostadorDTO.limiteMinimoDiario == null : this.limiteMinimoDiario.equals(apostadorDTO.limiteMinimoDiario)) &&
                (this.limiteDiario == null ? apostadorDTO.limiteDiario == null : this.limiteDiario.equals(apostadorDTO.limiteDiario)) &&
                (this.limiteDiarioAutorizado == null ? apostadorDTO.limiteDiarioAutorizado == null : this.limiteDiarioAutorizado.equals(apostadorDTO.limiteDiarioAutorizado));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.cpf == null ? 0: this.cpf.hashCode());
        result = 31 * result + (this.email == null ? 0: this.email.hashCode());
        result = 31 * result + (this.nome == null ? 0: this.nome.hashCode());
        result = 31 * result + (this.dataNascimento == null ? 0: this.dataNascimento.hashCode());
        result = 31 * result + (this.telefone == null ? 0: this.telefone.hashCode());
        result = 31 * result + (this.cep == null ? 0: this.cep.hashCode());
        result = 31 * result + (this.aceitaTermosUso == null ? 0: this.aceitaTermosUso.hashCode());
        result = 31 * result + (this.aceitaReceberNoticias == null ? 0: this.aceitaReceberNoticias.hashCode());
        result = 31 * result + (this.municipioId == null ? 0: this.municipioId.hashCode());
        result = 31 * result + (this.lotericaId == null ? 0: this.lotericaId.hashCode());
        result = 31 * result + (this.sexo == null ? 0: this.sexo.hashCode());
        result = 31 * result + (this.mercadoPagoCustomerId == null ? 0: this.mercadoPagoCustomerId.hashCode());
        result = 31 * result + (this.apostas == null ? 0: this.apostas.hashCode());
        result = 31 * result + (this.limiteMinimoDiario == null ? 0: this.limiteMinimoDiario.hashCode());
        result = 31 * result + (this.limiteDiario == null ? 0: this.limiteDiario.hashCode());
        result = 31 * result + (this.limiteDiarioAutorizado == null ? 0: this.limiteDiarioAutorizado.hashCode());
        return result;
    }

    @Override
    public String toString()  {

        String sb = "class ApostadorDTO {\n" +
                "  cpf: " + cpf + "\n" +
                "  email: " + email + "\n" +
                "  nome: " + nome + "\n" +
                "  dataNascimento: " + dataNascimento + "\n" +
                "  telefone: " + telefone + "\n" +
                "  cep: " + cep + "\n" +
                "  aceitaTermosUso: " + aceitaTermosUso + "\n" +
                "  aceitaReceberNoticias: " + aceitaReceberNoticias + "\n" +
                "  municipioId: " + municipioId + "\n" +
                "  lotericaId: " + lotericaId + "\n" +
                "  sexo: " + sexo + "\n" +
                "  mercadoPagoCustomerId: " + mercadoPagoCustomerId + "\n" +
                "  apostas: " + apostas + "\n" +
                "  limiteMinimoDiario: " + limiteMinimoDiario + "\n" +
                "  limiteDiario: " + limiteDiario + "\n" +
                "  limiteDiarioAutorizado: " + limiteDiarioAutorizado + "\n" +
                "}\n";
        return sb;
    }
}
