/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ApostadorVO {

    @SerializedName("id")
    private Long id = null;
    @SerializedName("cpf")
    private CPF cpf = null;
    @SerializedName("email")
    private Email email = null;
    @SerializedName("novoEmail")
    private Email novoEmail = null;
    @SerializedName("confirmacaoEmail")
    private Email confirmacaoEmail = null;
    @SerializedName("nome")
    private String nome = null;
    @SerializedName("nomeMae")
    private String nomeMae = null;
    @SerializedName("dataNascimento")
    private Data dataNascimento = null;
    @SerializedName("dataUltimoAcesso")
    private Data dataUltimoAcesso = null;
    @SerializedName("dataAtualizacaoContadorTentativasAcesso")
    private Data dataAtualizacaoContadorTentativasAcesso = null;
    @SerializedName("dataFimBloqueioVinculacao")
    private Data dataFimBloqueioVinculacao = null;
    @SerializedName("contadorTentativasAcesso")
    private Integer contadorTentativasAcesso = null;
    @SerializedName("telefoneDdd")
    private Integer telefoneDdd = null;
    @SerializedName("telefoneNumero")
    private Integer telefoneNumero = null;
    @SerializedName("cep")
    private CEP cep = null;
    @SerializedName("senha")
    private String senha = null;
    @SerializedName("novaSenha")
    private String novaSenha = null;
    @SerializedName("confirmacaoSenha")
    private String confirmacaoSenha = null;
    @SerializedName("aceitaTermosUso")
    private Boolean aceitaTermosUso = null;
    @SerializedName("aceitaReceberNoticias")
    private Boolean aceitaReceberNoticias = null;
    @SerializedName("municipioCodigoUf")
    private Long municipioCodigoUf = null;
    @SerializedName("municipioNumero")
    private Long municipioNumero = null;
    @SerializedName("municipioDigitoVerificador")
    private Long municipioDigitoVerificador = null;
    @SerializedName("situacaoId")
    private Long situacaoId = null;
    @SerializedName("dataCadastro")
    private Data dataCadastro = null;
    @SerializedName("lotericaId")
    private Long lotericaId = null;
    @SerializedName("sexo")
    private String sexo = null;
    @SerializedName("municipioPK")
    private MunicipioPK municipioPK = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public CPF getCpf() {
        return cpf;
    }

    public void setCpf(CPF cpf) {
        this.cpf = cpf;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Email getEmail() {
        return email;
    }

    public void setEmail(Email email) {
        this.email = email;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Email getNovoEmail() {
        return novoEmail;
    }

    public void setNovoEmail(Email novoEmail) {
        this.novoEmail = novoEmail;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Email getConfirmacaoEmail() {
        return confirmacaoEmail;
    }

    public void setConfirmacaoEmail(Email confirmacaoEmail) {
        this.confirmacaoEmail = confirmacaoEmail;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNomeMae() {
        return nomeMae;
    }

    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(Data dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataUltimoAcesso() {
        return dataUltimoAcesso;
    }

    public void setDataUltimoAcesso(Data dataUltimoAcesso) {
        this.dataUltimoAcesso = dataUltimoAcesso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataAtualizacaoContadorTentativasAcesso() {
        return dataAtualizacaoContadorTentativasAcesso;
    }

    public void setDataAtualizacaoContadorTentativasAcesso(Data dataAtualizacaoContadorTentativasAcesso) {
        this.dataAtualizacaoContadorTentativasAcesso = dataAtualizacaoContadorTentativasAcesso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataFimBloqueioVinculacao() {
        return dataFimBloqueioVinculacao;
    }

    public void setDataFimBloqueioVinculacao(Data dataFimBloqueioVinculacao) {
        this.dataFimBloqueioVinculacao = dataFimBloqueioVinculacao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getContadorTentativasAcesso() {
        return contadorTentativasAcesso;
    }

    public void setContadorTentativasAcesso(Integer contadorTentativasAcesso) {
        this.contadorTentativasAcesso = contadorTentativasAcesso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getTelefoneDdd() {
        return telefoneDdd;
    }

    public void setTelefoneDdd(Integer telefoneDdd) {
        this.telefoneDdd = telefoneDdd;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getTelefoneNumero() {
        return telefoneNumero;
    }

    public void setTelefoneNumero(Integer telefoneNumero) {
        this.telefoneNumero = telefoneNumero;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public CEP getCep() {
        return cep;
    }

    public void setCep(CEP cep) {
        this.cep = cep;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNovaSenha() {
        return novaSenha;
    }

    public void setNovaSenha(String novaSenha) {
        this.novaSenha = novaSenha;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getConfirmacaoSenha() {
        return confirmacaoSenha;
    }

    public void setConfirmacaoSenha(String confirmacaoSenha) {
        this.confirmacaoSenha = confirmacaoSenha;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getAceitaTermosUso() {
        return aceitaTermosUso;
    }

    public void setAceitaTermosUso(Boolean aceitaTermosUso) {
        this.aceitaTermosUso = aceitaTermosUso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getAceitaReceberNoticias() {
        return aceitaReceberNoticias;
    }

    public void setAceitaReceberNoticias(Boolean aceitaReceberNoticias) {
        this.aceitaReceberNoticias = aceitaReceberNoticias;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getMunicipioCodigoUf() {
        return municipioCodigoUf;
    }

    public void setMunicipioCodigoUf(Long municipioCodigoUf) {
        this.municipioCodigoUf = municipioCodigoUf;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getMunicipioNumero() {
        return municipioNumero;
    }

    public void setMunicipioNumero(Long municipioNumero) {
        this.municipioNumero = municipioNumero;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getMunicipioDigitoVerificador() {
        return municipioDigitoVerificador;
    }

    public void setMunicipioDigitoVerificador(Long municipioDigitoVerificador) {
        this.municipioDigitoVerificador = municipioDigitoVerificador;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getSituacaoId() {
        return situacaoId;
    }

    public void setSituacaoId(Long situacaoId) {
        this.situacaoId = situacaoId;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataCadastro() {
        return dataCadastro;
    }

    public void setDataCadastro(Data dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getLotericaId() {
        return lotericaId;
    }

    public void setLotericaId(Long lotericaId) {
        this.lotericaId = lotericaId;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public MunicipioPK getMunicipioPK() {
        return municipioPK;
    }

    public void setMunicipioPK(MunicipioPK municipioPK) {
        this.municipioPK = municipioPK;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApostadorVO apostadorVO = (ApostadorVO) o;
        return (this.id == null ? apostadorVO.id == null : this.id.equals(apostadorVO.id)) &&
                (this.cpf == null ? apostadorVO.cpf == null : this.cpf.equals(apostadorVO.cpf)) &&
                (this.email == null ? apostadorVO.email == null : this.email.equals(apostadorVO.email)) &&
                (this.novoEmail == null ? apostadorVO.novoEmail == null : this.novoEmail.equals(apostadorVO.novoEmail)) &&
                (this.confirmacaoEmail == null ? apostadorVO.confirmacaoEmail == null : this.confirmacaoEmail.equals(apostadorVO.confirmacaoEmail)) &&
                (this.nome == null ? apostadorVO.nome == null : this.nome.equals(apostadorVO.nome)) &&
                (this.nomeMae == null ? apostadorVO.nomeMae == null : this.nomeMae.equals(apostadorVO.nomeMae)) &&
                (this.dataNascimento == null ? apostadorVO.dataNascimento == null : this.dataNascimento.equals(apostadorVO.dataNascimento)) &&
                (this.dataUltimoAcesso == null ? apostadorVO.dataUltimoAcesso == null : this.dataUltimoAcesso.equals(apostadorVO.dataUltimoAcesso)) &&
                (this.dataAtualizacaoContadorTentativasAcesso == null ? apostadorVO.dataAtualizacaoContadorTentativasAcesso == null : this.dataAtualizacaoContadorTentativasAcesso.equals(apostadorVO.dataAtualizacaoContadorTentativasAcesso)) &&
                (this.dataFimBloqueioVinculacao == null ? apostadorVO.dataFimBloqueioVinculacao == null : this.dataFimBloqueioVinculacao.equals(apostadorVO.dataFimBloqueioVinculacao)) &&
                (this.contadorTentativasAcesso == null ? apostadorVO.contadorTentativasAcesso == null : this.contadorTentativasAcesso.equals(apostadorVO.contadorTentativasAcesso)) &&
                (this.telefoneDdd == null ? apostadorVO.telefoneDdd == null : this.telefoneDdd.equals(apostadorVO.telefoneDdd)) &&
                (this.telefoneNumero == null ? apostadorVO.telefoneNumero == null : this.telefoneNumero.equals(apostadorVO.telefoneNumero)) &&
                (this.cep == null ? apostadorVO.cep == null : this.cep.equals(apostadorVO.cep)) &&
                (this.senha == null ? apostadorVO.senha == null : this.senha.equals(apostadorVO.senha)) &&
                (this.novaSenha == null ? apostadorVO.novaSenha == null : this.novaSenha.equals(apostadorVO.novaSenha)) &&
                (this.confirmacaoSenha == null ? apostadorVO.confirmacaoSenha == null : this.confirmacaoSenha.equals(apostadorVO.confirmacaoSenha)) &&
                (this.aceitaTermosUso == null ? apostadorVO.aceitaTermosUso == null : this.aceitaTermosUso.equals(apostadorVO.aceitaTermosUso)) &&
                (this.aceitaReceberNoticias == null ? apostadorVO.aceitaReceberNoticias == null : this.aceitaReceberNoticias.equals(apostadorVO.aceitaReceberNoticias)) &&
                (this.municipioCodigoUf == null ? apostadorVO.municipioCodigoUf == null : this.municipioCodigoUf.equals(apostadorVO.municipioCodigoUf)) &&
                (this.municipioNumero == null ? apostadorVO.municipioNumero == null : this.municipioNumero.equals(apostadorVO.municipioNumero)) &&
                (this.municipioDigitoVerificador == null ? apostadorVO.municipioDigitoVerificador == null : this.municipioDigitoVerificador.equals(apostadorVO.municipioDigitoVerificador)) &&
                (this.situacaoId == null ? apostadorVO.situacaoId == null : this.situacaoId.equals(apostadorVO.situacaoId)) &&
                (this.dataCadastro == null ? apostadorVO.dataCadastro == null : this.dataCadastro.equals(apostadorVO.dataCadastro)) &&
                (this.lotericaId == null ? apostadorVO.lotericaId == null : this.lotericaId.equals(apostadorVO.lotericaId)) &&
                (this.sexo == null ? apostadorVO.sexo == null : this.sexo.equals(apostadorVO.sexo)) &&
                (this.municipioPK == null ? apostadorVO.municipioPK == null : this.municipioPK.equals(apostadorVO.municipioPK));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.cpf == null ? 0 : this.cpf.hashCode());
        result = 31 * result + (this.email == null ? 0 : this.email.hashCode());
        result = 31 * result + (this.novoEmail == null ? 0 : this.novoEmail.hashCode());
        result = 31 * result + (this.confirmacaoEmail == null ? 0 : this.confirmacaoEmail.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        result = 31 * result + (this.nomeMae == null ? 0 : this.nomeMae.hashCode());
        result = 31 * result + (this.dataNascimento == null ? 0 : this.dataNascimento.hashCode());
        result = 31 * result + (this.dataUltimoAcesso == null ? 0 : this.dataUltimoAcesso.hashCode());
        result = 31 * result + (this.dataAtualizacaoContadorTentativasAcesso == null ? 0 : this.dataAtualizacaoContadorTentativasAcesso.hashCode());
        result = 31 * result + (this.dataFimBloqueioVinculacao == null ? 0 : this.dataFimBloqueioVinculacao.hashCode());
        result = 31 * result + (this.contadorTentativasAcesso == null ? 0 : this.contadorTentativasAcesso.hashCode());
        result = 31 * result + (this.telefoneDdd == null ? 0 : this.telefoneDdd.hashCode());
        result = 31 * result + (this.telefoneNumero == null ? 0 : this.telefoneNumero.hashCode());
        result = 31 * result + (this.cep == null ? 0 : this.cep.hashCode());
        result = 31 * result + (this.senha == null ? 0 : this.senha.hashCode());
        result = 31 * result + (this.novaSenha == null ? 0 : this.novaSenha.hashCode());
        result = 31 * result + (this.confirmacaoSenha == null ? 0 : this.confirmacaoSenha.hashCode());
        result = 31 * result + (this.aceitaTermosUso == null ? 0 : this.aceitaTermosUso.hashCode());
        result = 31 * result + (this.aceitaReceberNoticias == null ? 0 : this.aceitaReceberNoticias.hashCode());
        result = 31 * result + (this.municipioCodigoUf == null ? 0 : this.municipioCodigoUf.hashCode());
        result = 31 * result + (this.municipioNumero == null ? 0 : this.municipioNumero.hashCode());
        result = 31 * result + (this.municipioDigitoVerificador == null ? 0 : this.municipioDigitoVerificador.hashCode());
        result = 31 * result + (this.situacaoId == null ? 0 : this.situacaoId.hashCode());
        result = 31 * result + (this.dataCadastro == null ? 0 : this.dataCadastro.hashCode());
        result = 31 * result + (this.lotericaId == null ? 0 : this.lotericaId.hashCode());
        result = 31 * result + (this.sexo == null ? 0 : this.sexo.hashCode());
        result = 31 * result + (this.municipioPK == null ? 0 : this.municipioPK.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ApostadorVO {\n" +
                "  id: " + id + "\n" +
                "  cpf: " + cpf + "\n" +
                "  email: " + email + "\n" +
                "  novoEmail: " + novoEmail + "\n" +
                "  confirmacaoEmail: " + confirmacaoEmail + "\n" +
                "  nome: " + nome + "\n" +
                "  nomeMae: " + nomeMae + "\n" +
                "  dataNascimento: " + dataNascimento + "\n" +
                "  dataUltimoAcesso: " + dataUltimoAcesso + "\n" +
                "  dataAtualizacaoContadorTentativasAcesso: " + dataAtualizacaoContadorTentativasAcesso + "\n" +
                "  dataFimBloqueioVinculacao: " + dataFimBloqueioVinculacao + "\n" +
                "  contadorTentativasAcesso: " + contadorTentativasAcesso + "\n" +
                "  telefoneDdd: " + telefoneDdd + "\n" +
                "  telefoneNumero: " + telefoneNumero + "\n" +
                "  cep: " + cep + "\n" +
                "  senha: " + senha + "\n" +
                "  novaSenha: " + novaSenha + "\n" +
                "  confirmacaoSenha: " + confirmacaoSenha + "\n" +
                "  aceitaTermosUso: " + aceitaTermosUso + "\n" +
                "  aceitaReceberNoticias: " + aceitaReceberNoticias + "\n" +
                "  municipioCodigoUf: " + municipioCodigoUf + "\n" +
                "  municipioNumero: " + municipioNumero + "\n" +
                "  municipioDigitoVerificador: " + municipioDigitoVerificador + "\n" +
                "  situacaoId: " + situacaoId + "\n" +
                "  dataCadastro: " + dataCadastro + "\n" +
                "  lotericaId: " + lotericaId + "\n" +
                "  sexo: " + sexo + "\n" +
                "  municipioPK: " + municipioPK + "\n" +
                "}\n";
        return sb;
    }
}
