/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class Apostador {
    @SerializedName("id")
    private Long id = null;
    @SerializedName("cpf")
    private CPF cpf = null;
    @SerializedName("email")
    private Email email = null;
    @SerializedName("novoEmail")
    private Email novoEmail = null;
    @SerializedName("confirmacaoEmail")
    private Email confirmacaoEmail = null;
    @SerializedName("nome")
    private String nome = null;
    @SerializedName("primeiroNome")
    private String primeiroNome = null;
    @SerializedName("nomeMae")
    private String nomeMae = null;
    @SerializedName("dataNascimento")
    private Data dataNascimento = null;
    @SerializedName("dataUltimoAcesso")
    private Data dataUltimoAcesso = null;
    @SerializedName("dataAtualizacaoContadorTentativasAcesso")
    private Data dataAtualizacaoContadorTentativasAcesso = null;
    @SerializedName("dataFimBloqueioVinculacao")
    private Data dataFimBloqueioVinculacao = null;
    @SerializedName("contadorTentativasAcesso")
    private Integer contadorTentativasAcesso = null;
    @SerializedName("telefone")
    private Telefone telefone = null;
    @SerializedName("cep")
    private CEP cep = null;
    @SerializedName("senha")
    private String senha = null;
    @SerializedName("novaSenha")
    private String novaSenha = null;
    @SerializedName("confirmacaoSenha")
    private String confirmacaoSenha = null;
    @SerializedName("aceitaTermosUso")
    private Boolean aceitaTermosUso = null;
    @SerializedName("aceitaReceberNoticias")
    private Boolean aceitaReceberNoticias = null;
    @SerializedName("municipio")
    private MunicipioToDelete municipio = null;
    @SerializedName("situacao")
    private SituacaoApostador situacao = null;
    @SerializedName("dataCadastro")
    private Data dataCadastro = null;
    @SerializedName("loterica")
    private Loterica loterica = null;
    @SerializedName("sexo")
    private SexoEnum sexo = null;
    @SerializedName("ultimoTermoDeUsoAceito")
    private TermoDeUso ultimoTermoDeUsoAceito = null;
    @SerializedName("dataUltimoAceiteTermoDeUso")
    private Data dataUltimoAceiteTermoDeUso = null;
    @SerializedName("mercadoPagoCustomerId")
    private String mercadoPagoCustomerId = null;
    @SerializedName("vo")
    private ApostadorVO vo = null;
    @SerializedName("alterouEmail")
    private Boolean alterouEmail = null;
    @SerializedName("sobrenome")
    private String sobrenome = null;
    @SerializedName("carteiraVinculada")
    private Boolean carteiraVinculada = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public CPF getCpf() {
        return cpf;
    }

    public void setCpf(CPF cpf) {
        this.cpf = cpf;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Email getEmail() {
        return email;
    }

    public void setEmail(Email email) {
        this.email = email;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Email getNovoEmail() {
        return novoEmail;
    }

    public void setNovoEmail(Email novoEmail) {
        this.novoEmail = novoEmail;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Email getConfirmacaoEmail() {
        return confirmacaoEmail;
    }

    public void setConfirmacaoEmail(Email confirmacaoEmail) {
        this.confirmacaoEmail = confirmacaoEmail;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getPrimeiroNome() {
        return primeiroNome;
    }

    public void setPrimeiroNome(String primeiroNome) {
        this.primeiroNome = primeiroNome;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNomeMae() {
        return nomeMae;
    }

    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(Data dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataUltimoAcesso() {
        return dataUltimoAcesso;
    }

    public void setDataUltimoAcesso(Data dataUltimoAcesso) {
        this.dataUltimoAcesso = dataUltimoAcesso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataAtualizacaoContadorTentativasAcesso() {
        return dataAtualizacaoContadorTentativasAcesso;
    }

    public void setDataAtualizacaoContadorTentativasAcesso(Data dataAtualizacaoContadorTentativasAcesso) {
        this.dataAtualizacaoContadorTentativasAcesso = dataAtualizacaoContadorTentativasAcesso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataFimBloqueioVinculacao() {
        return dataFimBloqueioVinculacao;
    }

    public void setDataFimBloqueioVinculacao(Data dataFimBloqueioVinculacao) {
        this.dataFimBloqueioVinculacao = dataFimBloqueioVinculacao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getContadorTentativasAcesso() {
        return contadorTentativasAcesso;
    }

    public void setContadorTentativasAcesso(Integer contadorTentativasAcesso) {
        this.contadorTentativasAcesso = contadorTentativasAcesso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Telefone getTelefone() {
        return telefone;
    }

    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public CEP getCep() {
        return cep;
    }

    public void setCep(CEP cep) {
        this.cep = cep;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNovaSenha() {
        return novaSenha;
    }

    public void setNovaSenha(String novaSenha) {
        this.novaSenha = novaSenha;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getConfirmacaoSenha() {
        return confirmacaoSenha;
    }

    public void setConfirmacaoSenha(String confirmacaoSenha) {
        this.confirmacaoSenha = confirmacaoSenha;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getAceitaTermosUso() {
        return aceitaTermosUso;
    }

    public void setAceitaTermosUso(Boolean aceitaTermosUso) {
        this.aceitaTermosUso = aceitaTermosUso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getAceitaReceberNoticias() {
        return aceitaReceberNoticias;
    }

    public void setAceitaReceberNoticias(Boolean aceitaReceberNoticias) {
        this.aceitaReceberNoticias = aceitaReceberNoticias;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public MunicipioToDelete getMunicipio() {
        return municipio;
    }

    public void setMunicipio(MunicipioToDelete municipio) {
        this.municipio = municipio;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public SituacaoApostador getSituacao() {
        return situacao;
    }

    public void setSituacao(SituacaoApostador situacao) {
        this.situacao = situacao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataCadastro() {
        return dataCadastro;
    }

    public void setDataCadastro(Data dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Loterica getLoterica() {
        return loterica;
    }

    public void setLoterica(Loterica loterica) {
        this.loterica = loterica;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public SexoEnum getSexo() {
        return sexo;
    }

    public void setSexo(SexoEnum sexo) {
        this.sexo = sexo;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public TermoDeUso getUltimoTermoDeUsoAceito() {
        return ultimoTermoDeUsoAceito;
    }

    public void setUltimoTermoDeUsoAceito(TermoDeUso ultimoTermoDeUsoAceito) {
        this.ultimoTermoDeUsoAceito = ultimoTermoDeUsoAceito;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataUltimoAceiteTermoDeUso() {
        return dataUltimoAceiteTermoDeUso;
    }

    public void setDataUltimoAceiteTermoDeUso(Data dataUltimoAceiteTermoDeUso) {
        this.dataUltimoAceiteTermoDeUso = dataUltimoAceiteTermoDeUso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getMercadoPagoCustomerId() {
        return mercadoPagoCustomerId;
    }

    public void setMercadoPagoCustomerId(String mercadoPagoCustomerId) {
        this.mercadoPagoCustomerId = mercadoPagoCustomerId;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ApostadorVO getVo() {
        return vo;
    }

    public void setVo(ApostadorVO vo) {
        this.vo = vo;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getAlterouEmail() {
        return alterouEmail;
    }

    public void setAlterouEmail(Boolean alterouEmail) {
        this.alterouEmail = alterouEmail;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getSobrenome() {
        return sobrenome;
    }

    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getCarteiraVinculada() {
        return carteiraVinculada;
    }

    public void setCarteiraVinculada(Boolean carteiraVinculada) {
        this.carteiraVinculada = carteiraVinculada;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Apostador apostador = (Apostador) o;
        return (this.id == null ? apostador.id == null : this.id.equals(apostador.id)) &&
                (this.cpf == null ? apostador.cpf == null : this.cpf.equals(apostador.cpf)) &&
                (this.email == null ? apostador.email == null : this.email.equals(apostador.email)) &&
                (this.novoEmail == null ? apostador.novoEmail == null : this.novoEmail.equals(apostador.novoEmail)) &&
                (this.confirmacaoEmail == null ? apostador.confirmacaoEmail == null : this.confirmacaoEmail.equals(apostador.confirmacaoEmail)) &&
                (this.nome == null ? apostador.nome == null : this.nome.equals(apostador.nome)) &&
                (this.primeiroNome == null ? apostador.primeiroNome == null : this.primeiroNome.equals(apostador.primeiroNome)) &&
                (this.nomeMae == null ? apostador.nomeMae == null : this.nomeMae.equals(apostador.nomeMae)) &&
                (this.dataNascimento == null ? apostador.dataNascimento == null : this.dataNascimento.equals(apostador.dataNascimento)) &&
                (this.dataUltimoAcesso == null ? apostador.dataUltimoAcesso == null : this.dataUltimoAcesso.equals(apostador.dataUltimoAcesso)) &&
                (this.dataAtualizacaoContadorTentativasAcesso == null ? apostador.dataAtualizacaoContadorTentativasAcesso == null : this.dataAtualizacaoContadorTentativasAcesso.equals(apostador.dataAtualizacaoContadorTentativasAcesso)) &&
                (this.dataFimBloqueioVinculacao == null ? apostador.dataFimBloqueioVinculacao == null : this.dataFimBloqueioVinculacao.equals(apostador.dataFimBloqueioVinculacao)) &&
                (this.contadorTentativasAcesso == null ? apostador.contadorTentativasAcesso == null : this.contadorTentativasAcesso.equals(apostador.contadorTentativasAcesso)) &&
                (this.telefone == null ? apostador.telefone == null : this.telefone.equals(apostador.telefone)) &&
                (this.cep == null ? apostador.cep == null : this.cep.equals(apostador.cep)) &&
                (this.senha == null ? apostador.senha == null : this.senha.equals(apostador.senha)) &&
                (this.novaSenha == null ? apostador.novaSenha == null : this.novaSenha.equals(apostador.novaSenha)) &&
                (this.confirmacaoSenha == null ? apostador.confirmacaoSenha == null : this.confirmacaoSenha.equals(apostador.confirmacaoSenha)) &&
                (this.aceitaTermosUso == null ? apostador.aceitaTermosUso == null : this.aceitaTermosUso.equals(apostador.aceitaTermosUso)) &&
                (this.aceitaReceberNoticias == null ? apostador.aceitaReceberNoticias == null : this.aceitaReceberNoticias.equals(apostador.aceitaReceberNoticias)) &&
                (this.municipio == null ? apostador.municipio == null : this.municipio.equals(apostador.municipio)) &&
                (this.situacao == null ? apostador.situacao == null : this.situacao.equals(apostador.situacao)) &&
                (this.dataCadastro == null ? apostador.dataCadastro == null : this.dataCadastro.equals(apostador.dataCadastro)) &&
                (this.loterica == null ? apostador.loterica == null : this.loterica.equals(apostador.loterica)) &&
                (this.sexo == null ? apostador.sexo == null : this.sexo.equals(apostador.sexo)) &&
                (this.ultimoTermoDeUsoAceito == null ? apostador.ultimoTermoDeUsoAceito == null : this.ultimoTermoDeUsoAceito.equals(apostador.ultimoTermoDeUsoAceito)) &&
                (this.dataUltimoAceiteTermoDeUso == null ? apostador.dataUltimoAceiteTermoDeUso == null : this.dataUltimoAceiteTermoDeUso.equals(apostador.dataUltimoAceiteTermoDeUso)) &&
                (this.mercadoPagoCustomerId == null ? apostador.mercadoPagoCustomerId == null : this.mercadoPagoCustomerId.equals(apostador.mercadoPagoCustomerId)) &&
                (this.vo == null ? apostador.vo == null : this.vo.equals(apostador.vo)) &&
                (this.alterouEmail == null ? apostador.alterouEmail == null : this.alterouEmail.equals(apostador.alterouEmail)) &&
                (this.sobrenome == null ? apostador.sobrenome == null : this.sobrenome.equals(apostador.sobrenome)) &&
                (this.carteiraVinculada == null ? apostador.carteiraVinculada == null : this.carteiraVinculada.equals(apostador.carteiraVinculada));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.cpf == null ? 0 : this.cpf.hashCode());
        result = 31 * result + (this.email == null ? 0 : this.email.hashCode());
        result = 31 * result + (this.novoEmail == null ? 0 : this.novoEmail.hashCode());
        result = 31 * result + (this.confirmacaoEmail == null ? 0 : this.confirmacaoEmail.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        result = 31 * result + (this.primeiroNome == null ? 0 : this.primeiroNome.hashCode());
        result = 31 * result + (this.nomeMae == null ? 0 : this.nomeMae.hashCode());
        result = 31 * result + (this.dataNascimento == null ? 0 : this.dataNascimento.hashCode());
        result = 31 * result + (this.dataUltimoAcesso == null ? 0 : this.dataUltimoAcesso.hashCode());
        result = 31 * result + (this.dataAtualizacaoContadorTentativasAcesso == null ? 0 : this.dataAtualizacaoContadorTentativasAcesso.hashCode());
        result = 31 * result + (this.dataFimBloqueioVinculacao == null ? 0 : this.dataFimBloqueioVinculacao.hashCode());
        result = 31 * result + (this.contadorTentativasAcesso == null ? 0 : this.contadorTentativasAcesso.hashCode());
        result = 31 * result + (this.telefone == null ? 0 : this.telefone.hashCode());
        result = 31 * result + (this.cep == null ? 0 : this.cep.hashCode());
        result = 31 * result + (this.senha == null ? 0 : this.senha.hashCode());
        result = 31 * result + (this.novaSenha == null ? 0 : this.novaSenha.hashCode());
        result = 31 * result + (this.confirmacaoSenha == null ? 0 : this.confirmacaoSenha.hashCode());
        result = 31 * result + (this.aceitaTermosUso == null ? 0 : this.aceitaTermosUso.hashCode());
        result = 31 * result + (this.aceitaReceberNoticias == null ? 0 : this.aceitaReceberNoticias.hashCode());
        result = 31 * result + (this.municipio == null ? 0 : this.municipio.hashCode());
        result = 31 * result + (this.situacao == null ? 0 : this.situacao.hashCode());
        result = 31 * result + (this.dataCadastro == null ? 0 : this.dataCadastro.hashCode());
        result = 31 * result + (this.loterica == null ? 0 : this.loterica.hashCode());
        result = 31 * result + (this.sexo == null ? 0 : this.sexo.hashCode());
        result = 31 * result + (this.ultimoTermoDeUsoAceito == null ? 0 : this.ultimoTermoDeUsoAceito.hashCode());
        result = 31 * result + (this.dataUltimoAceiteTermoDeUso == null ? 0 : this.dataUltimoAceiteTermoDeUso.hashCode());
        result = 31 * result + (this.mercadoPagoCustomerId == null ? 0 : this.mercadoPagoCustomerId.hashCode());
        result = 31 * result + (this.vo == null ? 0 : this.vo.hashCode());
        result = 31 * result + (this.alterouEmail == null ? 0 : this.alterouEmail.hashCode());
        result = 31 * result + (this.sobrenome == null ? 0 : this.sobrenome.hashCode());
        result = 31 * result + (this.carteiraVinculada == null ? 0 : this.carteiraVinculada.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class Apostador {\n" +
                "  id: " + id + "\n" +
                "  cpf: " + cpf + "\n" +
                "  email: " + email + "\n" +
                "  novoEmail: " + novoEmail + "\n" +
                "  confirmacaoEmail: " + confirmacaoEmail + "\n" +
                "  nome: " + nome + "\n" +
                "  primeiroNome: " + primeiroNome + "\n" +
                "  nomeMae: " + nomeMae + "\n" +
                "  dataNascimento: " + dataNascimento + "\n" +
                "  dataUltimoAcesso: " + dataUltimoAcesso + "\n" +
                "  dataAtualizacaoContadorTentativasAcesso: " + dataAtualizacaoContadorTentativasAcesso + "\n" +
                "  dataFimBloqueioVinculacao: " + dataFimBloqueioVinculacao + "\n" +
                "  contadorTentativasAcesso: " + contadorTentativasAcesso + "\n" +
                "  telefone: " + telefone + "\n" +
                "  cep: " + cep + "\n" +
                "  senha: " + senha + "\n" +
                "  novaSenha: " + novaSenha + "\n" +
                "  confirmacaoSenha: " + confirmacaoSenha + "\n" +
                "  aceitaTermosUso: " + aceitaTermosUso + "\n" +
                "  aceitaReceberNoticias: " + aceitaReceberNoticias + "\n" +
                "  municipio: " + municipio + "\n" +
                "  situacao: " + situacao + "\n" +
                "  dataCadastro: " + dataCadastro + "\n" +
                "  loterica: " + loterica + "\n" +
                "  sexo: " + sexo + "\n" +
                "  ultimoTermoDeUsoAceito: " + ultimoTermoDeUsoAceito + "\n" +
                "  dataUltimoAceiteTermoDeUso: " + dataUltimoAceiteTermoDeUso + "\n" +
                "  mercadoPagoCustomerId: " + mercadoPagoCustomerId + "\n" +
                "  vo: " + vo + "\n" +
                "  alterouEmail: " + alterouEmail + "\n" +
                "  sobrenome: " + sobrenome + "\n" +
                "  carteiraVinculada: " + carteiraVinculada + "\n" +
                "}\n";
        return sb;
    }
}
