/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class AtivarUsuarioDTO {

    @SerializedName("cpf")
    private String cpf = null;
    @SerializedName("email")
    private String email = null;
    @SerializedName("codigoValidacao")
    private String codigoValidacao = null;
    @SerializedName("senha")
    private String senha = null;

    /**
     * CPF do apostador
     **/
    @ApiModelProperty(value = "CPF do apostador")
    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * Email do apostador
     **/
    @ApiModelProperty(value = "Email do apostador")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Código de Validação do apostador
     **/
    @ApiModelProperty(value = "Código de Validação do apostador")
    public String getCodigoValidacao() {
        return codigoValidacao;
    }

    public void setCodigoValidacao(String codigoValidacao) {
        this.codigoValidacao = codigoValidacao;
    }

    /**
     * Senha do apostador
     **/
    @ApiModelProperty(value = "Senha do apostador")
    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AtivarUsuarioDTO ativarUsuarioDTO = (AtivarUsuarioDTO) o;
        return (this.cpf == null ? ativarUsuarioDTO.cpf == null : this.cpf.equals(ativarUsuarioDTO.cpf)) &&
                (this.email == null ? ativarUsuarioDTO.email == null : this.email.equals(ativarUsuarioDTO.email)) &&
                (this.codigoValidacao == null ? ativarUsuarioDTO.codigoValidacao == null : this.codigoValidacao.equals(ativarUsuarioDTO.codigoValidacao)) &&
                (this.senha == null ? ativarUsuarioDTO.senha == null : this.senha.equals(ativarUsuarioDTO.senha));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.cpf == null ? 0 : this.cpf.hashCode());
        result = 31 * result + (this.email == null ? 0 : this.email.hashCode());
        result = 31 * result + (this.codigoValidacao == null ? 0 : this.codigoValidacao.hashCode());
        result = 31 * result + (this.senha == null ? 0 : this.senha.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class AtivarUsuarioDTO {\n" +
                "  cpf: " + cpf + "\n" +
                "  email: " + email + "\n" +
                "  codigoValidacao: " + codigoValidacao + "\n" +
                "  senha: " + senha + "\n" +
                "}\n";
        return sb;
    }
}
