/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class BairroDTO {

    @SerializedName("id")
    private Long id = null;
    @SerializedName("nome")
    private String nome = null;
    @SerializedName("municipio")
    private MunicipioDTO municipio = null;

    /**
     * Identificação do Bairro
     **/
    @ApiModelProperty(required = true, value = "Identificação do Bairro")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Descrição do bairro
     **/
    @ApiModelProperty(value = "Descrição do bairro")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public MunicipioDTO getMunicipio() {
        return municipio;
    }

    public void setMunicipio(MunicipioDTO municipio) {
        this.municipio = municipio;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BairroDTO bairroDTO = (BairroDTO) o;
        return (this.id == null ? bairroDTO.id == null : this.id.equals(bairroDTO.id)) &&
                (this.nome == null ? bairroDTO.nome == null : this.nome.equals(bairroDTO.nome)) &&
                (this.municipio == null ? bairroDTO.municipio == null : this.municipio.equals(bairroDTO.municipio));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        result = 31 * result + (this.municipio == null ? 0 : this.municipio.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class BairroDTO {\n" +
                "  id: " + id + "\n" +
                "  nome: " + nome + "\n" +
                "  municipio: " + municipio + "\n" +
                "}\n";
        return sb;
    }
}
