/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CadastrarApostadorDTO {
  
  @SerializedName("cep")
  private String cep = null;
  @SerializedName("aceitaTermosUso")
  private Boolean aceitaTermosUso = null;
  @SerializedName("aceitaReceberNoticias")
  private Boolean aceitaReceberNoticias = null;
  @SerializedName("municipioId")
  private MunicipioIdDTO municipioId = null;
  public enum SexoEnum {
     M,  F, 
  };
  @SerializedName("sexo")
  private SexoEnum sexo = null;
  @SerializedName("apostas")
  private List<ApostaDTO> apostas = null;

  /**
   * CEP do endereço do apostador
   **/
  @ApiModelProperty(value = "CEP do endereço do apostador")
  public String getCep() {
    return cep;
  }
  public void setCep(String cep) {
    this.cep = cep;
  }

  /**
   * Identifica se o apostador aceitou o termo de uso vigente
   **/
  @ApiModelProperty(required = true, value = "Identifica se o apostador aceitou o termo de uso vigente")
  public Boolean getAceitaTermosUso() {
    return aceitaTermosUso;
  }
  public void setAceitaTermosUso(Boolean aceitaTermosUso) {
    this.aceitaTermosUso = aceitaTermosUso;
  }

  /**
   * Identifica se o aposta selecionou a opção para receber noticias
   **/
  @ApiModelProperty(required = true, value = "Identifica se o aposta selecionou a opção para receber noticias")
  public Boolean getAceitaReceberNoticias() {
    return aceitaReceberNoticias;
  }
  public void setAceitaReceberNoticias(Boolean aceitaReceberNoticias) {
    this.aceitaReceberNoticias = aceitaReceberNoticias;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public MunicipioIdDTO getMunicipioId() {
    return municipioId;
  }
  public void setMunicipioId(MunicipioIdDTO municipioId) {
    this.municipioId = municipioId;
  }

  /**
   * Sexo do Apostador
   **/
  @ApiModelProperty(required = true, value = "Sexo do Apostador")
  public SexoEnum getSexo() {
    return sexo;
  }
  public void setSexo(SexoEnum sexo) {
    this.sexo = sexo;
  }

  /**
   * Apostas que estão na sessão
   **/
  @ApiModelProperty(value = "Apostas que estão na sessão")
  public List<ApostaDTO> getApostas() {
    return apostas;
  }
  public void setApostas(List<ApostaDTO> apostas) {
    this.apostas = apostas;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CadastrarApostadorDTO cadastrarApostadorDTO = (CadastrarApostadorDTO) o;
    return (this.cep == null ? cadastrarApostadorDTO.cep == null : this.cep.equals(cadastrarApostadorDTO.cep)) &&
        (this.aceitaTermosUso == null ? cadastrarApostadorDTO.aceitaTermosUso == null : this.aceitaTermosUso.equals(cadastrarApostadorDTO.aceitaTermosUso)) &&
        (this.aceitaReceberNoticias == null ? cadastrarApostadorDTO.aceitaReceberNoticias == null : this.aceitaReceberNoticias.equals(cadastrarApostadorDTO.aceitaReceberNoticias)) &&
        (this.municipioId == null ? cadastrarApostadorDTO.municipioId == null : this.municipioId.equals(cadastrarApostadorDTO.municipioId)) &&
        (this.sexo == null ? cadastrarApostadorDTO.sexo == null : this.sexo.equals(cadastrarApostadorDTO.sexo)) &&
        (this.apostas == null ? cadastrarApostadorDTO.apostas == null : this.apostas.equals(cadastrarApostadorDTO.apostas));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cep == null ? 0: this.cep.hashCode());
    result = 31 * result + (this.aceitaTermosUso == null ? 0: this.aceitaTermosUso.hashCode());
    result = 31 * result + (this.aceitaReceberNoticias == null ? 0: this.aceitaReceberNoticias.hashCode());
    result = 31 * result + (this.municipioId == null ? 0: this.municipioId.hashCode());
    result = 31 * result + (this.sexo == null ? 0: this.sexo.hashCode());
    result = 31 * result + (this.apostas == null ? 0: this.apostas.hashCode());
    return result;
  }

  @Override
  public String toString()  {

    String sb = "class CadastrarApostadorDTO {\n" +
            "  cep: " + cep + "\n" +
            "  aceitaTermosUso: " + aceitaTermosUso + "\n" +
            "  aceitaReceberNoticias: " + aceitaReceberNoticias + "\n" +
            "  municipioId: " + municipioId + "\n" +
            "  sexo: " + sexo + "\n" +
            "  apostas: " + apostas + "\n" +
            "}\n";
    return sb;
  }
}
