/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CarrinhoFavoritoDTOResponse
 */
@ApiModel(description = "")
public class CarrinhoFavoritoDTOResponse {
  @SerializedName("codigo")
  private String codigo = null;

  @SerializedName("mensagem")
  private String mensagem = null;

  @SerializedName("redirect")
  private RedirectEnum redirect = null;

  @SerializedName("errosValidacao")
  private List<ErroValidacao> errosValidacao = null;

  @SerializedName("versao")
  private String versao = null;

  @SerializedName("payload")
  private CarrinhoFavoritoDTO payload = null;

  @SerializedName("tipo")
  private TipoEnum tipo = null;

  /**
   * Tipo da mensagem. 1&#x3D;Mensagem de usuário, 2&#x3D;Mensagem de sistema, 3&#x3D; Erro de validação
   */
  @JsonAdapter(TipoEnum.Adapter.class)
  public enum TipoEnum {
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    TipoEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TipoEnum fromValue(String text) {
      for (TipoEnum b : TipoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TipoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TipoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TipoEnum read(final JsonReader jsonReader) throws IOException {
        Integer value = jsonReader.nextInt();
        return TipoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public CarrinhoFavoritoDTOResponse codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Código do erro
   * @return codigo
  **/
  @ApiModelProperty(value = "Código do erro")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public CarrinhoFavoritoDTOResponse mensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário
   * @return mensagem
  **/
  @ApiModelProperty(value = "Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário")
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  public CarrinhoFavoritoDTOResponse tipo(TipoEnum tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Tipo da mensagem. 1&#x3D;Mensagem de usuário, 2&#x3D;Mensagem de sistema, 3&#x3D; Erro de validação
   * @return tipo
  **/
  @ApiModelProperty(value = "Tipo da mensagem. 1=Mensagem de usuário, 2=Mensagem de sistema, 3= Erro de validação")
  public TipoEnum getTipo() {
    return tipo;
  }

  public void setTipo(TipoEnum tipo) {
    this.tipo = tipo;
  }

  public CarrinhoFavoritoDTOResponse redirect(RedirectEnum redirect) {
    this.redirect = redirect;
    return this;
  }

   /**
   * ID da tela que o usuário deve ser redirecionado
   * @return redirect
  **/
  @ApiModelProperty(value = "ID da tela que o usuário deve ser redirecionado")
  public RedirectEnum getRedirect() {
    return redirect;
  }

  public void setRedirect(RedirectEnum redirect) {
    this.redirect = redirect;
  }

  public CarrinhoFavoritoDTOResponse errosValidacao(List<ErroValidacao> errosValidacao) {
    this.errosValidacao = errosValidacao;
    return this;
  }

  public CarrinhoFavoritoDTOResponse addErrosValidacaoItem(ErroValidacao errosValidacaoItem) {
    if (this.errosValidacao == null) {
      this.errosValidacao = new ArrayList<ErroValidacao>();
    }
    this.errosValidacao.add(errosValidacaoItem);
    return this;
  }

   /**
   * Lista com os erros de validação
   * @return errosValidacao
  **/
  @ApiModelProperty(value = "Lista com os erros de validação")
  public List<ErroValidacao> getErrosValidacao() {
    return errosValidacao;
  }

  public void setErrosValidacao(List<ErroValidacao> errosValidacao) {
    this.errosValidacao = errosValidacao;
  }

  public CarrinhoFavoritoDTOResponse versao(String versao) {
    this.versao = versao;
    return this;
  }

   /**
   * Versão do serviço
   * @return versao
  **/
  @ApiModelProperty(value = "Versão do serviço")
  public String getVersao() {
    return versao;
  }

  public void setVersao(String versao) {
    this.versao = versao;
  }

  public CarrinhoFavoritoDTOResponse payload(CarrinhoFavoritoDTO payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @ApiModelProperty(value = "")
  public CarrinhoFavoritoDTO getPayload() {
    return payload;
  }

  public void setPayload(CarrinhoFavoritoDTO payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarrinhoFavoritoDTOResponse carrinhoFavoritoDTOResponse = (CarrinhoFavoritoDTOResponse) o;
    return Objects.equals(this.codigo, carrinhoFavoritoDTOResponse.codigo) &&
        Objects.equals(this.mensagem, carrinhoFavoritoDTOResponse.mensagem) &&
        Objects.equals(this.tipo, carrinhoFavoritoDTOResponse.tipo) &&
        Objects.equals(this.redirect, carrinhoFavoritoDTOResponse.redirect) &&
        Objects.equals(this.errosValidacao, carrinhoFavoritoDTOResponse.errosValidacao) &&
        Objects.equals(this.versao, carrinhoFavoritoDTOResponse.versao) &&
        Objects.equals(this.payload, carrinhoFavoritoDTOResponse.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, mensagem, tipo, redirect, errosValidacao, versao, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarrinhoFavoritoDTOResponse {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    errosValidacao: ").append(toIndentedString(errosValidacao)).append("\n");
    sb.append("    versao: ").append(toIndentedString(versao)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

