/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class CEP {

    @SerializedName("cepSemMascara")
    private String cepSemMascara = null;
    @SerializedName("complemento")
    private String complemento = null;
    @SerializedName("cepComMascara")
    private String cepComMascara = null;
    @SerializedName("numero")
    private String numero = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public String getCepSemMascara() {
        return cepSemMascara;
    }

    public void setCepSemMascara(String cepSemMascara) {
        this.cepSemMascara = cepSemMascara;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getComplemento() {
        return complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getCepComMascara() {
        return cepComMascara;
    }

    public void setCepComMascara(String cepComMascara) {
        this.cepComMascara = cepComMascara;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CEP CEP = (CEP) o;
        return (this.cepSemMascara == null ? CEP.cepSemMascara == null : this.cepSemMascara.equals(CEP.cepSemMascara)) &&
                (this.complemento == null ? CEP.complemento == null : this.complemento.equals(CEP.complemento)) &&
                (this.cepComMascara == null ? CEP.cepComMascara == null : this.cepComMascara.equals(CEP.cepComMascara)) &&
                (this.numero == null ? CEP.numero == null : this.numero.equals(CEP.numero));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.cepSemMascara == null ? 0 : this.cepSemMascara.hashCode());
        result = 31 * result + (this.complemento == null ? 0 : this.complemento.hashCode());
        result = 31 * result + (this.cepComMascara == null ? 0 : this.cepComMascara.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class CEP {\n" +
                "  cepSemMascara: " + cepSemMascara + "\n" +
                "  complemento: " + complemento + "\n" +
                "  cepComMascara: " + cepComMascara + "\n" +
                "  numero: " + numero + "\n" +
                "}\n";
        return sb;
    }
}
