/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class CodigoResgateDTO implements Serializable {

    @SerializedName("nsb")
    protected String nsb = null;
    @SerializedName("codigo")
    protected String codigo = null;
    @SerializedName("validade")
    protected Integer validade;
    @SerializedName("qrCode")
    protected String qrCode;

    /**
     * NSBi da aposta para geração do QR Code
     **/
    @ApiModelProperty(value = "NSBi da aposta para geração do QR Code")
    public String getNsb() {
        return nsb;
    }

    public void setNsb(String nsb) {
        this.nsb = nsb;
    }

    /**
     * Código de Resgate da aposta para geração do QR Code
     **/
    @ApiModelProperty(value = "Código de Resgate da aposta para geração do QR Code")
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Integer getValidade() {
        return validade;
    }

    public void setValidade(Integer validade) {
        this.validade = validade;
    }

    public String getQrCode() {
        return qrCode;
    }

    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CodigoResgateDTO codigoResgateDTO = (CodigoResgateDTO) o;
        return (this.nsb == null ? codigoResgateDTO.nsb == null : this.nsb.equals(codigoResgateDTO.nsb)) &&
                (this.codigo == null ? codigoResgateDTO.codigo == null : this.codigo.equals(codigoResgateDTO.codigo));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.nsb == null ? 0 : this.nsb.hashCode());
        result = 31 * result + (this.codigo == null ? 0 : this.codigo.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class CodigoResgateDTO {\n" +
                "  nsb: " + nsb + "\n" +
                "  codigo: " + codigo + "\n" +
                "}\n";
        return sb;
    }
}
