/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * CombosDTO
 */
public class CombosDTO {
  @SerializedName("tipoCombo")
  private TipoComboDTO tipoCombo = null;

  @SerializedName("modalidadesCombo")
  private List<ModalidadeComboDTO> modalidadesCombo = null;

  @SerializedName("valor")
  private BigDecimal valor = null;

  public CombosDTO tipoCombo(TipoComboDTO tipoCombo) {
    this.tipoCombo = tipoCombo;
    return this;
  }

  public enum TipoComboEnum {
    ESPECIAL(1),
    SUPER_MILIONARIO(2),
    MILIONARIO(3),
    MUITO_DINHEIRO(4),
    SORTE_FACIL(5),
    CHANCE_TODO_DIA(6),
    SORTE_ACUMULADA(7),
    SORTE_HOJE(8),
    FEZINHA_DO_MES(9),
    VIP(10),
    CAIXA_PRA_ELAS(11);

    private final Integer value;

    TipoComboEnum(Integer value) {
      this.value = value;
    }

    // Método para recuperar o valor do enum
    public Integer getValue() {
      return value;
    }

    // Método para recuperar o tipo do combo pelo valor
    public static TipoComboEnum fromValue(Integer value) {
      for (TipoComboEnum tipo : TipoComboEnum.values()) {
        if (tipo.value.equals(value)) {
          return tipo;
        }
      }
      throw new IllegalArgumentException("Valor inválido para TipoComboEnum: " + value);
    }

    // Método para recuperar o valor pelo tipo de combo
    public static Integer fromEnum(TipoComboEnum tipoCombo) {
      if (tipoCombo == null) {
        throw new IllegalArgumentException("TipoComboEnum não pode ser nulo");
      }
      return tipoCombo.getValue();
    }
  }

   /**
   * Get tipoCombo
   * @return tipoCombo
  **/
  @ApiModelProperty(value = "")
  public TipoComboDTO getTipoCombo() {
    return tipoCombo;
  }

  public void setTipoCombo(TipoComboDTO tipoCombo) {
    this.tipoCombo = tipoCombo;
  }

  public CombosDTO modalidadesCombo(List<ModalidadeComboDTO> modalidadesCombo) {
    this.modalidadesCombo = modalidadesCombo;
    return this;
  }

  public CombosDTO addModalidadesComboItem(ModalidadeComboDTO modalidadesComboItem) {
    if (this.modalidadesCombo == null) {
      this.modalidadesCombo = new ArrayList<ModalidadeComboDTO>();
    }
    this.modalidadesCombo.add(modalidadesComboItem);
    return this;
  }

   /**
   * Get modalidadesCombo
   * @return modalidadesCombo
  **/
  @ApiModelProperty(value = "")
  public List<ModalidadeComboDTO> getModalidadesCombo() {
    return modalidadesCombo;
  }

  public void setModalidadesCombo(List<ModalidadeComboDTO> modalidadesCombo) {
    this.modalidadesCombo = modalidadesCombo;
  }

  public CombosDTO valor(BigDecimal valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getValor() {
    return valor;
  }

  public void setValor(BigDecimal valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CombosDTO combosDTO = (CombosDTO) o;
    return Objects.equals(this.tipoCombo, combosDTO.tipoCombo) &&
        Objects.equals(this.modalidadesCombo, combosDTO.modalidadesCombo) &&
        Objects.equals(this.valor, combosDTO.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoCombo, modalidadesCombo, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CombosDTO {\n");
    
    sb.append("    tipoCombo: ").append(toIndentedString(tipoCombo)).append("\n");
    sb.append("    modalidadesCombo: ").append(toIndentedString(modalidadesCombo)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

