/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ComprovanteApostaDTO implements Serializable {

    @SerializedName("nsbi")
    protected String nsbi = null;
    @SerializedName("aposta")
    protected IdentificaoDeUmaApostaDas8Modalidades aposta = null;
    @SerializedName("loterica")
    protected LotericaDTO loterica = null;
    @SerializedName("dataSorteio")
    protected String dataSorteio = null;

    /**
     * NSBi da aposta
     **/
    @ApiModelProperty(value = "NSBi da aposta")
    public String getNsbi() {
        return nsbi;
    }

    public void setNsbi(String nsbi) {
        this.nsbi = nsbi;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public IdentificaoDeUmaApostaDas8Modalidades getAposta() {
        return aposta;
    }

    public void setAposta(IdentificaoDeUmaApostaDas8Modalidades aposta) {
        this.aposta = aposta;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public LotericaDTO getLoterica() {
        return loterica;
    }

    public void setLoterica(LotericaDTO loterica) {
        this.loterica = loterica;
    }

    /**
     * Data do sorteio do concurso relacionado a aposta
     **/
    @ApiModelProperty(value = "Data do sorteio do concurso relacionado a aposta")
    public String getDataSorteio() {
        return dataSorteio;
    }

    public void setDataSorteio(String dataSorteio) {
        this.dataSorteio = dataSorteio;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ComprovanteApostaDTO comprovanteApostaDTO = (ComprovanteApostaDTO) o;
        return (this.nsbi == null ? comprovanteApostaDTO.nsbi == null : this.nsbi.equals(comprovanteApostaDTO.nsbi)) &&
                (this.aposta == null ? comprovanteApostaDTO.aposta == null : this.aposta.equals(comprovanteApostaDTO.aposta)) &&
                (this.loterica == null ? comprovanteApostaDTO.loterica == null : this.loterica.equals(comprovanteApostaDTO.loterica)) &&
                (this.dataSorteio == null ? comprovanteApostaDTO.dataSorteio == null : this.dataSorteio.equals(comprovanteApostaDTO.dataSorteio));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.nsbi == null ? 0 : this.nsbi.hashCode());
        result = 31 * result + (this.aposta == null ? 0 : this.aposta.hashCode());
        result = 31 * result + (this.loterica == null ? 0 : this.loterica.hashCode());
        result = 31 * result + (this.dataSorteio == null ? 0 : this.dataSorteio.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ComprovanteApostaDTO {\n" +
                "  nsbi: " + nsbi + "\n" +
                "  aposta: " + aposta + "\n" +
                "  loterica: " + loterica + "\n" +
                "  dataSorteio: " + dataSorteio + "\n" +
                "}\n";
        return sb;
    }
}
