/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.Duration;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

import java.math.BigDecimal;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class CompraDTO {

    @SerializedName("id")
    private Long id = null;
    @SerializedName("situacao")
    private DTOEnumLong situacao = null;
    @SerializedName("loterica")
    private LotericaDTO loterica = null;
    @SerializedName("dataInicioCompra")
    private String dataInicioCompra = null;
    @SerializedName("dataEfetivacaoDebito")
    private String dataEfetivacaoDebito = null;
    @SerializedName("horaInicioCompra")
    private String horaInicioCompra = null;
    @SerializedName("dataFinalizacaoCompra")
    private String dataFinalizacaoCompra = null;
    @SerializedName("horaFinalizacaoCompra")
    private String horaFinalizacaoCompra = null;
    @SerializedName("valorTotal")
    private BigDecimal valorTotal = null;
    @SerializedName("timestampUltimaAlteracao")
    private String timestampUltimaAlteracao = null;
    @SerializedName("meioPagamento")
    private DTOEnumLong meioPagamento = null;
    @SerializedName("codigoMensageErro")
    private String codigoMensageErro = null;
    @SerializedName("e2eId")
    private String e2eId = null;
    @SerializedName("dataHoraExpiracaoPagamento")
    private String dataHoraExpiracaoPagamento = null;
    @SerializedName("qrcodeString")
    private String qrcodeString = null;
    @SerializedName("qrcodeArrByte")
    private String qrcodeArrByte = null;
    @SerializedName("pixCopiaECola")
    private String pixCopiaECola = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public DTOEnumLong getSituacao() {
        return situacao;
    }

    public void setSituacao(DTOEnumLong situacao) {
        this.situacao = situacao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public LotericaDTO getLoterica() {
        return loterica;
    }

    public void setLoterica(LotericaDTO loterica) {
        this.loterica = loterica;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getDataInicioCompra() {
        return dataInicioCompra;
    }

    public void setDataInicioCompra(String dataInicioCompra) {
        this.dataInicioCompra = dataInicioCompra;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getDataEfetivacaoDebito() {
        return dataEfetivacaoDebito;
    }

    public void setDataEfetivacaoDebito(String dataEfetivacaoDebito) {
        this.dataEfetivacaoDebito = dataEfetivacaoDebito;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getHoraInicioCompra() {
        return horaInicioCompra;
    }

    public void setHoraInicioCompra(String horaInicioCompra) {
        this.horaInicioCompra = horaInicioCompra;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getDataFinalizacaoCompra() {
        return dataFinalizacaoCompra;
    }

    public void setDataFinalizacaoCompra(String dataFinalizacaoCompra) {
        this.dataFinalizacaoCompra = dataFinalizacaoCompra;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getHoraFinalizacaoCompra() {
        return horaFinalizacaoCompra;
    }

    public void setHoraFinalizacaoCompra(String horaFinalizacaoCompra) {
        this.horaFinalizacaoCompra = horaFinalizacaoCompra;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getTimestampUltimaAlteracao() {
        return timestampUltimaAlteracao;
    }

    public void setTimestampUltimaAlteracao(String timestampUltimaAlteracao) {
        this.timestampUltimaAlteracao = timestampUltimaAlteracao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public DTOEnumLong getMeioPagamento() {
        return meioPagamento;
    }

    public void setMeioPagamento(DTOEnumLong meioPagamento) {
        this.meioPagamento = meioPagamento;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getCodigoMensageErro() {
        return codigoMensageErro;
    }

    public void setCodigoMensageErro(String codigoMensageErro) {
        this.codigoMensageErro = codigoMensageErro;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getE2eId() {
        return e2eId;
    }

    public void setE2eId(String e2eId) {
        this.e2eId = e2eId;
    }

    @ApiModelProperty(value = "")
    public String getDataHoraExpiracaoPagamento() {
        return dataHoraExpiracaoPagamento;
    }

    public void setDataHoraExpiracaoPagamento(String dataHoraExpiracaoPagamento) {
        this.dataHoraExpiracaoPagamento = dataHoraExpiracaoPagamento;
    }

    @ApiModelProperty(value = "")
    public String getQrcodeString() {
        return qrcodeString;
    }

    public void setQrcodeString(String qrcodeString) {
        this.qrcodeString = qrcodeString;
    }

    @ApiModelProperty(value = "")
    public String getQrcodeArrByte() {
        return qrcodeArrByte;
    }

    public void setQrcodeArrByte(String qrcodeArrByte) {
        this.qrcodeArrByte = qrcodeArrByte;
    }

    @ApiModelProperty(value = "")
    public String getPixCopiaECola() {
        return pixCopiaECola;
    }

    public void setPixCopiaECola(String pixCopiaECola) {
        this.pixCopiaECola = pixCopiaECola;
    }

    public int getTimerSeconds(String dataHoraServidor) {
        DateTimeZone timeZone = DateTimeZone.forID("America/Sao_Paulo");
        DateTime inicio;
        DateTimeFormatter formatter = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS").withZone(timeZone);

        try {
            inicio = formatter.parseDateTime(dataHoraServidor);
        } catch (Exception e){
            inicio = DateTime.now(timeZone);
        }
        DateTime expiracao = formatter.parseDateTime(getDataHoraExpiracaoPagamento());

        Duration duration = new Duration(inicio, expiracao);
        long diffInSeconds = duration.getStandardSeconds();

        return (int) diffInSeconds;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompraDTO compraDTO = (CompraDTO) o;
        return (this.id == null ? compraDTO.id == null : this.id.equals(compraDTO.id)) &&
                (this.situacao == null ? compraDTO.situacao == null : this.situacao.equals(compraDTO.situacao)) &&
                (this.loterica == null ? compraDTO.loterica == null : this.loterica.equals(compraDTO.loterica)) &&
                (this.dataInicioCompra == null ? compraDTO.dataInicioCompra == null : this.dataInicioCompra.equals(compraDTO.dataInicioCompra)) &&
                (this.dataEfetivacaoDebito == null ? compraDTO.dataEfetivacaoDebito == null : this.dataEfetivacaoDebito.equals(compraDTO.dataEfetivacaoDebito)) &&
                (this.horaInicioCompra == null ? compraDTO.horaInicioCompra == null : this.horaInicioCompra.equals(compraDTO.horaInicioCompra)) &&
                (this.dataFinalizacaoCompra == null ? compraDTO.dataFinalizacaoCompra == null : this.dataFinalizacaoCompra.equals(compraDTO.dataFinalizacaoCompra)) &&
                (this.horaFinalizacaoCompra == null ? compraDTO.horaFinalizacaoCompra == null : this.horaFinalizacaoCompra.equals(compraDTO.horaFinalizacaoCompra)) &&
                (this.valorTotal == null ? compraDTO.valorTotal == null : this.valorTotal.equals(compraDTO.valorTotal)) &&
                (this.timestampUltimaAlteracao == null ? compraDTO.timestampUltimaAlteracao == null : this.timestampUltimaAlteracao.equals(compraDTO.timestampUltimaAlteracao)) &&
                (this.meioPagamento == null ? compraDTO.meioPagamento == null : this.meioPagamento.equals(compraDTO.meioPagamento)) &&
                (this.codigoMensageErro == null ? compraDTO.codigoMensageErro == null : this.codigoMensageErro.equals(compraDTO.codigoMensageErro)) &&
                (this.e2eId == null ? compraDTO.e2eId == null : this.e2eId.equals(compraDTO.e2eId)) &&
                (this.dataHoraExpiracaoPagamento == null ? compraDTO.dataHoraExpiracaoPagamento == null : this.dataHoraExpiracaoPagamento.equals(compraDTO.dataHoraExpiracaoPagamento)) &&
                (this.qrcodeString == null ? compraDTO.qrcodeString == null : this.qrcodeString.equals(compraDTO.qrcodeString)) &&
                (this.qrcodeArrByte == null ? compraDTO.qrcodeArrByte == null : this.qrcodeArrByte.equals(compraDTO.qrcodeArrByte)) &&
                (this.pixCopiaECola == null ? compraDTO.pixCopiaECola == null : this.pixCopiaECola.equals(compraDTO.pixCopiaECola));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.situacao == null ? 0 : this.situacao.hashCode());
        result = 31 * result + (this.loterica == null ? 0 : this.loterica.hashCode());
        result = 31 * result + (this.dataInicioCompra == null ? 0 : this.dataInicioCompra.hashCode());
        result = 31 * result + (this.dataEfetivacaoDebito == null ? 0 : this.dataEfetivacaoDebito.hashCode());
        result = 31 * result + (this.horaInicioCompra == null ? 0 : this.horaInicioCompra.hashCode());
        result = 31 * result + (this.dataFinalizacaoCompra == null ? 0 : this.dataFinalizacaoCompra.hashCode());
        result = 31 * result + (this.horaFinalizacaoCompra == null ? 0 : this.horaFinalizacaoCompra.hashCode());
        result = 31 * result + (this.valorTotal == null ? 0 : this.valorTotal.hashCode());
        result = 31 * result + (this.timestampUltimaAlteracao == null ? 0 : this.timestampUltimaAlteracao.hashCode());
        result = 31 * result + (this.meioPagamento == null ? 0 : this.meioPagamento.hashCode());
        result = 31 * result + (this.codigoMensageErro == null ? 0 : this.codigoMensageErro.hashCode());
        result = 31 * result + (this.e2eId == null ? 0 : this.e2eId.hashCode());
        result = 31 * result + (this.dataHoraExpiracaoPagamento == null ? 0 : this.dataHoraExpiracaoPagamento.hashCode());
        result = 31 * result + (this.qrcodeString == null ? 0 : this.qrcodeString.hashCode());
        result = 31 * result + (this.qrcodeArrByte == null ? 0 : this.qrcodeArrByte.hashCode());
        result = 31 * result + (this.pixCopiaECola == null ? 0 : this.pixCopiaECola.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class CompraDTO {\n" +
                "  id: " + id + "\n" +
                "  situacao: " + situacao + "\n" +
                "  loterica: " + loterica + "\n" +
                "  dataInicioCompra: " + dataInicioCompra + "\n" +
                "  dataEfetivacaoDebito: " + dataEfetivacaoDebito + "\n" +
                "  horaInicioCompra: " + horaInicioCompra + "\n" +
                "  dataFinalizacaoCompra: " + dataFinalizacaoCompra + "\n" +
                "  horaFinalizacaoCompra: " + horaFinalizacaoCompra + "\n" +
                "  valorTotal: " + valorTotal + "\n" +
                "  timestampUltimaAlteracao: " + timestampUltimaAlteracao + "\n" +
                "  meioPagamento: " + meioPagamento + "\n" +
                "  codigoMensageErro: " + codigoMensageErro + "\n" +
                "  e2eId: " + e2eId + "\n" +
                "  dataHoraExpiracaoPagamento: " + dataHoraExpiracaoPagamento + "\n" +
                "  qrcodeString: " + qrcodeString + "\n" +
                "  qrcodeArrByte: " + qrcodeArrByte + "\n" +
                "  pixCopiaECola: " + pixCopiaECola + "\n" +
                "}\n";
        return sb;
    }
}
