/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;

@ApiModel(description = "")
public class ConcursoNovoDTO implements Serializable {

    @SerializedName("numero")
    protected Long numero;
    @SerializedName("aberto")
    protected Boolean aberto;
    @SerializedName("naoInicializado")
    protected Boolean naoInicializado;

    public Long getNumero() {
        return numero;
    }

    public void setNumero(Long numero) {
        this.numero = numero;
    }

    public Boolean getAberto() {
        return aberto;
    }

    public void setAberto(Boolean aberto) {
        this.aberto = aberto;
    }

    public Boolean getNaoInicializado() {
        return naoInicializado;
    }

    public void setNaoInicializado(Boolean naoInicializado) {
        this.naoInicializado = naoInicializado;
    }

  
}
