/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.List;

import io.swagger.annotations.ApiModel;

@ApiModel(description = "")
public class ConcursosNovoDTO implements Serializable {

    @SerializedName("concurso")
    protected ConcursoNovoDTO concurso;

    @SerializedName("valorBruto")
    protected Double valorBruto;

    @SerializedName("valorLiquido")
    protected Double valorLiquido;

    @SerializedName("valorIRRF")
    protected Double valorIRRF;

    @SerializedName("situacao")
    protected String situacao;

    @SerializedName("faixas")
    protected List<FaixasDTO> faixas;

    public ConcursoNovoDTO getConcurso() {
        return concurso;
    }

    public void setConcurso(ConcursoNovoDTO concurso) {
        this.concurso = concurso;
    }

    public Double getValorBruto() {
        return valorBruto;
    }

    public void setValorBruto(Double valorBruto) {
        this.valorBruto = valorBruto;
    }

    public Double getValorLiquido() {
        return valorLiquido;
    }

    public void setValorLiquido(Double valorLiquido) {
        this.valorLiquido = valorLiquido;
    }

    public Double getValorIRRF() {
        return valorIRRF;
    }

    public void setValorIRRF(Double valorIRRF) {
        this.valorIRRF = valorIRRF;
    }

    public String getSituacao() {
        return situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    public List<FaixasDTO> getFaixas() {
        return faixas;
    }

    public void setFaixas(List<FaixasDTO> faixas) {
        this.faixas = faixas;
    }
}
