/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ConcursoDTO implements Serializable {
    @SerializedName("modalidade")
    protected ModalidadeEnum modalidade = null;
    @SerializedName("modalidadeDetalhada")
    protected ModalidadeDTO modalidadeDetalhada = null;
    @SerializedName("tipoConcurso")
    protected TipoConcursoEnum tipoConcurso = null;
    @SerializedName("numero")
    protected Integer numero = null;
    @SerializedName("dataFechamento")
    protected String dataFechamento = null;
    @SerializedName("dataAbertura")
    protected String dataAbertura = null;
    @SerializedName("dataHoraSorteio")
    protected String dataHoraSorteio = null;
    @SerializedName("dataSorteio")
    protected String dataSorteio = null;
    @SerializedName("valorApostaMinima")
    protected BigDecimal valorApostaMinima = null;
    @SerializedName("situacao")
    protected SituacaoEnum situacao = null;
    @SerializedName("bloqueado")
    protected Boolean bloqueado = null;
    @SerializedName("dataFinalBloqueio")
    protected String dataFinalBloqueio = null;
    @SerializedName("estimativa")
    protected BigDecimal estimativa = null;
    @SerializedName("acumulado")
    protected BigDecimal acumulado = null;
    @SerializedName("naoInicializado")
    protected Boolean naoInicializado = null;
    @SerializedName("aberto")
    protected Boolean aberto = null;

    /**
     * Modalidade relacionada com o concurso
     **/
    @ApiModelProperty(value = "Modalidade relacionada com o concurso")
    public ModalidadeEnum getModalidade() {
        return modalidade;
    }

    public void setModalidade(ModalidadeEnum modalidade) {
        this.modalidade = modalidade;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ModalidadeDTO getModalidadeDetalhada() {
        return modalidadeDetalhada;
    }

    public void setModalidadeDetalhada(ModalidadeDTO modalidadeDetalhada) {
        this.modalidadeDetalhada = modalidadeDetalhada;
    }

    /**
     * Tipo de concurso da modalidade
     **/
    @ApiModelProperty(value = "Tipo de concurso da modalidade")
    public TipoConcursoEnum getTipoConcurso() {
        return tipoConcurso;
    }

    public void setTipoConcurso(TipoConcursoEnum tipoConcurso) {
        this.tipoConcurso = tipoConcurso;
    }

    /**
     * Número do concurso
     **/
    @ApiModelProperty(value = "Número do concurso")
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * Data de Encerramento do Concurso
     **/
    @ApiModelProperty(value = "Data de Encerramento do Concurso")
    public String getDataFechamento() {
        return dataFechamento;
    }

    public void setDataFechamento(String dataFechamento) {
        this.dataFechamento = dataFechamento;
    }

    /**
     * Data de Abertura do Concurso
     **/
    @ApiModelProperty(value = "Data de Abertura do Concurso")
    public String getDataAbertura() {
        return dataAbertura;
    }

    public void setDataAbertura(String dataAbertura) {
        this.dataAbertura = dataAbertura;
    }

    /**
     * Data e Hora da Realização do Sorteio
     **/
    @ApiModelProperty(value = "Data e Hora da Realização do Sorteio")
    public String getDataHoraSorteio() {
        return dataHoraSorteio;
    }

    public void setDataHoraSorteio(String dataHoraSorteio) {
        this.dataHoraSorteio = dataHoraSorteio;
    }

    /**
     * Data do sorteio do concurso
     **/
    @ApiModelProperty(value = "Data do sorteio do concurso")
    public String getDataSorteio() {
        return dataSorteio;
    }

    public void setDataSorteio(String dataSorteio) {
        this.dataSorteio = dataSorteio;
    }

    /**
     * Valor Minimo da Aposta da Modalidade
     **/
    @ApiModelProperty(value = "Valor Minimo da Aposta da Modalidade")
    public BigDecimal getValorApostaMinima() {
        return valorApostaMinima;
    }

    public void setValorApostaMinima(BigDecimal valorApostaMinima) {
        this.valorApostaMinima = valorApostaMinima;
    }

    /**
     * Situação do concurso
     **/
    @ApiModelProperty(value = "Situação do concurso")
    public SituacaoEnum getSituacao() {
        return situacao;
    }

    public void setSituacao(SituacaoEnum situacao) {
        this.situacao = situacao;
    }

    /**
     * Indica se o concurso está bloqueado para captação
     **/
    @ApiModelProperty(value = "Indica se o concurso está bloqueado para captação")
    public Boolean getBloqueado() {
        return bloqueado;
    }

    public void setBloqueado(Boolean bloqueado) {
        this.bloqueado = bloqueado;
    }

    /**
     * Data final do bloqueio do concurso
     **/
    @ApiModelProperty(value = "Data final do bloqueio do concurso")
    public String getDataFinalBloqueio() {
        return dataFinalBloqueio;
    }

    public void setDataFinalBloqueio(String dataFinalBloqueio) {
        this.dataFinalBloqueio = dataFinalBloqueio;
    }

    /**
     * Estimativa de prêmio do concurso
     **/
    @ApiModelProperty(value = "Estimativa de prêmio do concurso")
    public BigDecimal getEstimativa() {
        return estimativa;
    }

    public void setEstimativa(BigDecimal estimativa) {
        this.estimativa = estimativa;
    }

    /**
     * Valor acumulado do prêmio para o próximo concurso
     **/
    @ApiModelProperty(value = "Valor acumulado do prêmio para o próximo concurso")
    public BigDecimal getAcumulado() {
        return acumulado;
    }

    public void setAcumulado(BigDecimal acumulado) {
        this.acumulado = acumulado;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getNaoInicializado() {
        return naoInicializado;
    }

    public void setNaoInicializado(Boolean naoInicializado) {
        this.naoInicializado = naoInicializado;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getAberto() {
        return aberto;
    }

    public void setAberto(Boolean aberto) {
        this.aberto = aberto;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConcursoDTO concursoDTO = (ConcursoDTO) o;
        return (this.modalidade == null ? concursoDTO.modalidade == null : this.modalidade.equals(concursoDTO.modalidade)) &&
                (this.modalidadeDetalhada == null ? concursoDTO.modalidadeDetalhada == null : this.modalidadeDetalhada.equals(concursoDTO.modalidadeDetalhada)) &&
                (this.tipoConcurso == null ? concursoDTO.tipoConcurso == null : this.tipoConcurso.equals(concursoDTO.tipoConcurso)) &&
                (this.numero == null ? concursoDTO.numero == null : this.numero.equals(concursoDTO.numero)) &&
                (this.dataFechamento == null ? concursoDTO.dataFechamento == null : this.dataFechamento.equals(concursoDTO.dataFechamento)) &&
                (this.dataAbertura == null ? concursoDTO.dataAbertura == null : this.dataAbertura.equals(concursoDTO.dataAbertura)) &&
                (this.dataHoraSorteio == null ? concursoDTO.dataHoraSorteio == null : this.dataHoraSorteio.equals(concursoDTO.dataHoraSorteio)) &&
                (this.dataSorteio == null ? concursoDTO.dataSorteio == null : this.dataSorteio.equals(concursoDTO.dataSorteio)) &&
                (this.valorApostaMinima == null ? concursoDTO.valorApostaMinima == null : this.valorApostaMinima.equals(concursoDTO.valorApostaMinima)) &&
                (this.situacao == null ? concursoDTO.situacao == null : this.situacao.equals(concursoDTO.situacao)) &&
                (this.bloqueado == null ? concursoDTO.bloqueado == null : this.bloqueado.equals(concursoDTO.bloqueado)) &&
                (this.dataFinalBloqueio == null ? concursoDTO.dataFinalBloqueio == null : this.dataFinalBloqueio.equals(concursoDTO.dataFinalBloqueio)) &&
                (this.estimativa == null ? concursoDTO.estimativa == null : this.estimativa.equals(concursoDTO.estimativa)) &&
                (this.acumulado == null ? concursoDTO.acumulado == null : this.acumulado.equals(concursoDTO.acumulado)) &&
                (this.naoInicializado == null ? concursoDTO.naoInicializado == null : this.naoInicializado.equals(concursoDTO.naoInicializado)) &&
                (this.aberto == null ? concursoDTO.aberto == null : this.aberto.equals(concursoDTO.aberto));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.modalidade == null ? 0 : this.modalidade.hashCode());
        result = 31 * result + (this.modalidadeDetalhada == null ? 0 : this.modalidadeDetalhada.hashCode());
        result = 31 * result + (this.tipoConcurso == null ? 0 : this.tipoConcurso.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.dataFechamento == null ? 0 : this.dataFechamento.hashCode());
        result = 31 * result + (this.dataAbertura == null ? 0 : this.dataAbertura.hashCode());
        result = 31 * result + (this.dataHoraSorteio == null ? 0 : this.dataHoraSorteio.hashCode());
        result = 31 * result + (this.dataSorteio == null ? 0 : this.dataSorteio.hashCode());
        result = 31 * result + (this.valorApostaMinima == null ? 0 : this.valorApostaMinima.hashCode());
        result = 31 * result + (this.situacao == null ? 0 : this.situacao.hashCode());
        result = 31 * result + (this.bloqueado == null ? 0 : this.bloqueado.hashCode());
        result = 31 * result + (this.dataFinalBloqueio == null ? 0 : this.dataFinalBloqueio.hashCode());
        result = 31 * result + (this.estimativa == null ? 0 : this.estimativa.hashCode());
        result = 31 * result + (this.acumulado == null ? 0 : this.acumulado.hashCode());
        result = 31 * result + (this.naoInicializado == null ? 0 : this.naoInicializado.hashCode());
        result = 31 * result + (this.aberto == null ? 0 : this.aberto.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ConcursoDTO {\n" +
                "  modalidade: " + modalidade + "\n" +
                "  modalidadeDetalhada: " + modalidadeDetalhada + "\n" +
                "  tipoConcurso: " + tipoConcurso + "\n" +
                "  numero: " + numero + "\n" +
                "  dataFechamento: " + dataFechamento + "\n" +
                "  dataAbertura: " + dataAbertura + "\n" +
                "  dataHoraSorteio: " + dataHoraSorteio + "\n" +
                "  dataSorteio: " + dataSorteio + "\n" +
                "  valorApostaMinima: " + valorApostaMinima + "\n" +
                "  situacao: " + situacao + "\n" +
                "  bloqueado: " + bloqueado + "\n" +
                "  dataFinalBloqueio: " + dataFinalBloqueio + "\n" +
                "  estimativa: " + estimativa + "\n" +
                "  acumulado: " + acumulado + "\n" +
                "  naoInicializado: " + naoInicializado + "\n" +
                "  aberto: " + aberto + "\n" +
                "}\n";
        return sb;
    }
}
