/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ConcursoPremiadoDTO implements Serializable {

    @SerializedName("id")
    protected Long id = null;
    @SerializedName("concurso")
    protected ConcursoDTO concurso = null;
    @SerializedName("valorBruto")
    protected BigDecimal valorBruto = null;
    @SerializedName("valorLiquido")
    protected BigDecimal valorLiquido = null;
    @SerializedName("valorIRRF")
    protected BigDecimal valorIRRF = null;
    @SerializedName("faixas")
    protected List<FaixaPremiadaDTO> faixas = null;
    @SerializedName("situacao")
    protected String situacao;

    /**
     * Identificação do concurso premiado
     **/
    @ApiModelProperty(value = "Identificação do concurso premiado")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ConcursoDTO getConcurso() {
        return concurso;
    }

    public void setConcurso(ConcursoDTO concurso) {
        this.concurso = concurso;
    }

    /**
     * Valor Bruto do prêmio do concurso
     **/
    @ApiModelProperty(value = "Valor Bruto do prêmio do concurso")
    public BigDecimal getValorBruto() {
        return valorBruto;
    }

    public void setValorBruto(BigDecimal valorBruto) {
        this.valorBruto = valorBruto;
    }

    /**
     * Valor líquido do prêmio do concurso.
     **/
    @ApiModelProperty(value = "Valor líquido do prêmio do concurso.")
    public BigDecimal getValorLiquido() {
        return valorLiquido;
    }

    public void setValorLiquido(BigDecimal valorLiquido) {
        this.valorLiquido = valorLiquido;
    }

    /**
     * Valor da retenção de IRRF do prêmio do concurso
     **/
    @ApiModelProperty(value = "Valor da retenção de IRRF do prêmio do concurso")
    public BigDecimal getValorIRRF() {
        return valorIRRF;
    }

    public void setValorIRRF(BigDecimal valorIRRF) {
        this.valorIRRF = valorIRRF;
    }

    /**
     * Lista com as Faixas de Premiação da Modalidade/Concurso
     **/
    @ApiModelProperty(value = "Lista com as Faixas de Premiação da Modalidade/Concurso")
    public List<FaixaPremiadaDTO> getFaixas() {
        return faixas;
    }

    public void setFaixas(List<FaixaPremiadaDTO> faixas) {
        this.faixas = faixas;
    }

    public String getSituacao() {
        return situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConcursoPremiadoDTO concursoPremiadoDTO = (ConcursoPremiadoDTO) o;
        return (this.id == null ? concursoPremiadoDTO.id == null : this.id.equals(concursoPremiadoDTO.id)) &&
                (this.concurso == null ? concursoPremiadoDTO.concurso == null : this.concurso.equals(concursoPremiadoDTO.concurso)) &&
                (this.valorBruto == null ? concursoPremiadoDTO.valorBruto == null : this.valorBruto.equals(concursoPremiadoDTO.valorBruto)) &&
                (this.valorLiquido == null ? concursoPremiadoDTO.valorLiquido == null : this.valorLiquido.equals(concursoPremiadoDTO.valorLiquido)) &&
                (this.valorIRRF == null ? concursoPremiadoDTO.valorIRRF == null : this.valorIRRF.equals(concursoPremiadoDTO.valorIRRF)) &&
                (this.faixas == null ? concursoPremiadoDTO.faixas == null : this.faixas.equals(concursoPremiadoDTO.faixas) &&
                (this.situacao == null ? concursoPremiadoDTO.situacao == null : this.situacao.equals(concursoPremiadoDTO.situacao)));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.concurso == null ? 0 : this.concurso.hashCode());
        result = 31 * result + (this.valorBruto == null ? 0 : this.valorBruto.hashCode());
        result = 31 * result + (this.valorLiquido == null ? 0 : this.valorLiquido.hashCode());
        result = 31 * result + (this.valorIRRF == null ? 0 : this.valorIRRF.hashCode());
        result = 31 * result + (this.faixas == null ? 0 : this.faixas.hashCode());
        result = 31 * result + (this.situacao == null ? 0 : this.situacao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ConcursoPremiadoDTO {\n" +
                "  id: " + id + "\n" +
                "  concurso: " + concurso + "\n" +
                "  valorBruto: " + valorBruto + "\n" +
                "  valorLiquido: " + valorLiquido + "\n" +
                "  valorIRRF: " + valorIRRF + "\n" +
                "  faixas: " + faixas + "\n" +
                "  situacao: " + situacao + "\n" +
                "}\n";
        return sb;
    }
}
