/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ConsultaBilheteDTO {

    @SerializedName("codigo")
    private String codigo = null;

    /**
     * Código do bilhete
     **/
    @ApiModelProperty(value = "Código do bilhete")
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConsultaBilheteDTO consultaBilheteDTO = (ConsultaBilheteDTO) o;
        return (this.codigo == null ? consultaBilheteDTO.codigo == null : this.codigo.equals(consultaBilheteDTO.codigo));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.codigo == null ? 0 : this.codigo.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ConsultaBilheteDTO {\n" +
                "  codigo: " + codigo + "\n" +
                "}\n";
        return sb;
    }
}
