/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class CPF {

    @SerializedName("cpfSemMascara")
    private String cpfSemMascara = null;
    @SerializedName("cpfComMascara")
    private String cpfComMascara = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public String getCpfSemMascara() {
        return cpfSemMascara;
    }

    public void setCpfSemMascara(String cpfSemMascara) {
        this.cpfSemMascara = cpfSemMascara;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getCpfComMascara() {
        return cpfComMascara;
    }

    public void setCpfComMascara(String cpfComMascara) {
        this.cpfComMascara = cpfComMascara;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CPF CPF = (CPF) o;
        return (this.cpfSemMascara == null ? CPF.cpfSemMascara == null : this.cpfSemMascara.equals(CPF.cpfSemMascara)) &&
                (this.cpfComMascara == null ? CPF.cpfComMascara == null : this.cpfComMascara.equals(CPF.cpfComMascara));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.cpfSemMascara == null ? 0 : this.cpfSemMascara.hashCode());
        result = 31 * result + (this.cpfComMascara == null ? 0 : this.cpfComMascara.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class CPF {\n" +
                "  cpfSemMascara: " + cpfSemMascara + "\n" +
                "  cpfComMascara: " + cpfComMascara + "\n" +
                "}\n";
        return sb;
    }
}
