/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class Data {

    @SerializedName("time")
    private Date time = null;
    @SerializedName("timeInMillis")
    private Long timeInMillis = null;
    @SerializedName("calendar")
    private Date calendar = null;
    @SerializedName("diaSemana")
    private Boolean diaSemana = null;
    @SerializedName("finalDeSemana")
    private Boolean finalDeSemana = null;
    @SerializedName("passado")
    private Boolean passado = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getTimeInMillis() {
        return timeInMillis;
    }

    public void setTimeInMillis(Long timeInMillis) {
        this.timeInMillis = timeInMillis;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Date getCalendar() {
        return calendar;
    }

    public void setCalendar(Date calendar) {
        this.calendar = calendar;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getDiaSemana() {
        return diaSemana;
    }

    public void setDiaSemana(Boolean diaSemana) {
        this.diaSemana = diaSemana;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getFinalDeSemana() {
        return finalDeSemana;
    }

    public void setFinalDeSemana(Boolean finalDeSemana) {
        this.finalDeSemana = finalDeSemana;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getPassado() {
        return passado;
    }

    public void setPassado(Boolean passado) {
        this.passado = passado;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Data data = (Data) o;
        return (this.time == null ? data.time == null : this.time.equals(data.time)) &&
                (this.timeInMillis == null ? data.timeInMillis == null : this.timeInMillis.equals(data.timeInMillis)) &&
                (this.calendar == null ? data.calendar == null : this.calendar.equals(data.calendar)) &&
                (this.diaSemana == null ? data.diaSemana == null : this.diaSemana.equals(data.diaSemana)) &&
                (this.finalDeSemana == null ? data.finalDeSemana == null : this.finalDeSemana.equals(data.finalDeSemana)) &&
                (this.passado == null ? data.passado == null : this.passado.equals(data.passado));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.time == null ? 0 : this.time.hashCode());
        result = 31 * result + (this.timeInMillis == null ? 0 : this.timeInMillis.hashCode());
        result = 31 * result + (this.calendar == null ? 0 : this.calendar.hashCode());
        result = 31 * result + (this.diaSemana == null ? 0 : this.diaSemana.hashCode());
        result = 31 * result + (this.finalDeSemana == null ? 0 : this.finalDeSemana.hashCode());
        result = 31 * result + (this.passado == null ? 0 : this.passado.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class Data {\n" +
                "  time: " + time + "\n" +
                "  timeInMillis: " + timeInMillis + "\n" +
                "  calendar: " + calendar + "\n" +
                "  diaSemana: " + diaSemana + "\n" +
                "  finalDeSemana: " + finalDeSemana + "\n" +
                "  passado: " + passado + "\n" +
                "}\n";
        return sb;
    }
}
