/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Esta entidade é utilizada para representar domínios, que tem apenas os atributos chave/valor
 **/
@ApiModel(description = "Esta entidade é utilizada para representar domínios, que tem apenas os atributos chave/valor")
public class DTOEnumLong implements Serializable {
    @SerializedName("valor")
    protected Long valor = null;
    @SerializedName("descricao")
    protected String descricao = null;

    /**
     * Identificador do domínio
     **/
    @ApiModelProperty(value = "Identificador do domínio")
    public Long getValor() {
        return valor;
    }

    public void setValor(Long valor) {
        this.valor = valor;
    }

    /**
     * Descrição deste domínio
     **/
    @ApiModelProperty(value = "Descrição deste domínio")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DTOEnumLong dTOEnumLong = (DTOEnumLong) o;
        return (this.valor == null ? dTOEnumLong.valor == null : this.valor.equals(dTOEnumLong.valor)) &&
                (this.descricao == null ? dTOEnumLong.descricao == null : this.descricao.equals(dTOEnumLong.descricao));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.valor == null ? 0 : this.valor.hashCode());
        result = 31 * result + (this.descricao == null ? 0 : this.descricao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class DTOEnumLong {\n" +
                "  valor: " + valor + "\n" +
                "  descricao: " + descricao + "\n" +
                "}\n";
        return sb;
    }
}
