/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class EquipeDTO implements Serializable {
    @SerializedName("placar")
    protected String placar = null;
    @SerializedName("vitoria")
    protected Boolean vitoria = null;
    @SerializedName("parametroEquipe")
    protected ParametroEquipe parametroEquipe = null;
    @SerializedName("nome")
    protected String nome = null;
    @SerializedName("numero")
    protected Integer numero = null;
    @SerializedName("numeroPais")
    protected Integer numeroPais = null;
    @SerializedName("pais")
    protected String pais = null;
    @SerializedName("siglaPais")
    protected String siglaPais = null;
    @SerializedName("uf")
    protected String uf = null;
    @SerializedName("nomeClass")
    protected String nomeClass = null;
    @SerializedName("indicadorSelecao")
    protected Boolean indicadorSelecao = null;
    @SerializedName("descricaoCurta")
    protected String descricaoCurta = null;
    @SerializedName("descricaoLonga")
    protected String descricaoLonga = null;
    @Expose(deserialize = false, serialize = false)
    protected Long idDB;

    /**
     * Identificação do Placar de cada jogo da Lotogol
     **/
    @ApiModelProperty(value = "Identificação do Placar de cada jogo da Lotogol")
    public String getPlacar() {
        return placar;
    }

    public void setPlacar(String placar) {
        this.placar = placar;
    }

    /**
     * Identificação do Time que teve vitória no jogo da Loteca
     **/
    @ApiModelProperty(value = "Identificação do Time que teve vitória no jogo da Loteca")
    public Boolean getVitoria() {
        return vitoria;
    }

    public void setVitoria(Boolean vitoria) {
        this.vitoria = vitoria;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ParametroEquipe getParametroEquipe() {
        return parametroEquipe;
    }

    public void setParametroEquipe(ParametroEquipe parametroEquipe) {
        this.parametroEquipe = parametroEquipe;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getNumeroPais() {
        return numeroPais;
    }

    public void setNumeroPais(Integer numeroPais) {
        this.numeroPais = numeroPais;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getPais() {
        return pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getSiglaPais() {
        return siglaPais;
    }

    public void setSiglaPais(String siglaPais) {
        this.siglaPais = siglaPais;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getUf() {
        return uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNomeClass() {
        return nomeClass;
    }

    public void setNomeClass(String nomeClass) {
        this.nomeClass = nomeClass;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getIndicadorSelecao() {
        return indicadorSelecao;
    }

    public void setIndicadorSelecao(Boolean indicadorSelecao) {
        this.indicadorSelecao = indicadorSelecao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getDescricaoCurta() {
        return descricaoCurta;
    }

    public void setDescricaoCurta(String descricaoCurta) {
        this.descricaoCurta = descricaoCurta;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getDescricaoLonga() {
        return descricaoLonga;
    }

    public void setDescricaoLonga(String descricaoLonga) {
        this.descricaoLonga = descricaoLonga;
    }

    public Long getIdDB() {
        return idDB;
    }

    public void setIdDB(Long idDB) {
        this.idDB = idDB;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EquipeDTO equipeDTO = (EquipeDTO) o;
        return (this.placar == null ? equipeDTO.placar == null : this.placar.equals(equipeDTO.placar)) &&
                (this.vitoria == null ? equipeDTO.vitoria == null : this.vitoria.equals(equipeDTO.vitoria)) &&
                (this.parametroEquipe == null ? equipeDTO.parametroEquipe == null : this.parametroEquipe.equals(equipeDTO.parametroEquipe)) &&
                (this.nome == null ? equipeDTO.nome == null : this.nome.equals(equipeDTO.nome)) &&
                (this.numero == null ? equipeDTO.numero == null : this.numero.equals(equipeDTO.numero)) &&
                (this.numeroPais == null ? equipeDTO.numeroPais == null : this.numeroPais.equals(equipeDTO.numeroPais)) &&
                (this.pais == null ? equipeDTO.pais == null : this.pais.equals(equipeDTO.pais)) &&
                (this.siglaPais == null ? equipeDTO.siglaPais == null : this.siglaPais.equals(equipeDTO.siglaPais)) &&
                (this.uf == null ? equipeDTO.uf == null : this.uf.equals(equipeDTO.uf)) &&
                (this.nomeClass == null ? equipeDTO.nomeClass == null : this.nomeClass.equals(equipeDTO.nomeClass)) &&
                (this.indicadorSelecao == null ? equipeDTO.indicadorSelecao == null : this.indicadorSelecao.equals(equipeDTO.indicadorSelecao)) &&
                (this.descricaoCurta == null ? equipeDTO.descricaoCurta == null : this.descricaoCurta.equals(equipeDTO.descricaoCurta)) &&
                (this.descricaoLonga == null ? equipeDTO.descricaoLonga == null : this.descricaoLonga.equals(equipeDTO.descricaoLonga));
    }

    public boolean customEquals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EquipeDTO equipeDTO = (EquipeDTO) o;
        return (this.placar == null ? equipeDTO.placar == null : this.placar.equals(equipeDTO.placar)) &&
                (this.parametroEquipe == null ? equipeDTO.parametroEquipe == null : this.parametroEquipe.equals(equipeDTO.parametroEquipe)) &&
                (this.nome == null ? equipeDTO.nome == null : this.nome.equals(equipeDTO.nome)) &&
                (this.numero == null ? equipeDTO.numero == null : this.numero.equals(equipeDTO.numero)) &&
                (this.numeroPais == null ? equipeDTO.numeroPais == null : this.numeroPais.equals(equipeDTO.numeroPais)) &&
                (this.pais == null ? equipeDTO.pais == null : this.pais.equals(equipeDTO.pais)) &&
                (this.siglaPais == null ? equipeDTO.siglaPais == null : this.siglaPais.equals(equipeDTO.siglaPais)) &&
                (this.uf == null ? equipeDTO.uf == null : this.uf.equals(equipeDTO.uf)) &&
                (this.nomeClass == null ? equipeDTO.nomeClass == null : this.nomeClass.equals(equipeDTO.nomeClass)) &&
                (this.indicadorSelecao == null ? equipeDTO.indicadorSelecao == null : this.indicadorSelecao.equals(equipeDTO.indicadorSelecao)) &&
                (this.descricaoCurta == null ? equipeDTO.descricaoCurta == null : this.descricaoCurta.equals(equipeDTO.descricaoCurta)) &&
                (this.descricaoLonga == null ? equipeDTO.descricaoLonga == null : this.descricaoLonga.equals(equipeDTO.descricaoLonga));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.placar == null ? 0 : this.placar.hashCode());
        result = 31 * result + (this.vitoria == null ? 0 : this.vitoria.hashCode());
        result = 31 * result + (this.parametroEquipe == null ? 0 : this.parametroEquipe.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.numeroPais == null ? 0 : this.numeroPais.hashCode());
        result = 31 * result + (this.pais == null ? 0 : this.pais.hashCode());
        result = 31 * result + (this.siglaPais == null ? 0 : this.siglaPais.hashCode());
        result = 31 * result + (this.uf == null ? 0 : this.uf.hashCode());
        result = 31 * result + (this.nomeClass == null ? 0 : this.nomeClass.hashCode());
        result = 31 * result + (this.indicadorSelecao == null ? 0 : this.indicadorSelecao.hashCode());
        result = 31 * result + (this.descricaoCurta == null ? 0 : this.descricaoCurta.hashCode());
        result = 31 * result + (this.descricaoLonga == null ? 0 : this.descricaoLonga.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class EquipeDTO {\n" +
                "  placar: " + placar + "\n" +
                "  vitoria: " + vitoria + "\n" +
                "  parametroEquipe: " + parametroEquipe + "\n" +
                "  nome: " + nome + "\n" +
                "  numero: " + numero + "\n" +
                "  numeroPais: " + numeroPais + "\n" +
                "  pais: " + pais + "\n" +
                "  siglaPais: " + siglaPais + "\n" +
                "  uf: " + uf + "\n" +
                "  nomeClass: " + nomeClass + "\n" +
                "  indicadorSelecao: " + indicadorSelecao + "\n" +
                "  descricaoCurta: " + descricaoCurta + "\n" +
                "  descricaoLonga: " + descricaoLonga + "\n" +
                "}\n";
        return sb;
    }
}