/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ErroValidacao implements Serializable {

    @SerializedName("mensagem")
    protected String mensagem = null;

    /**
     * Mensagem de erro de validação
     **/
    @ApiModelProperty(value = "Mensagem de erro de validação")
    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ErroValidacao erroValidacao = (ErroValidacao) o;
        return (this.mensagem == null ? erroValidacao.mensagem == null : this.mensagem.equals(erroValidacao.mensagem));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.mensagem == null ? 0 : this.mensagem.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ErroValidacao {\n" +
                "  mensagem: " + mensagem + "\n" +
                "}\n";
        return sb;
    }
}
