/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class EsqueciMinhaSenhaDTO {

    @SerializedName("cpf")
    private String cpf = null;
    @SerializedName("nome")
    private String nome = null;
    @SerializedName("nomeDaMae")
    private String nomeDaMae = null;
    @SerializedName("email")
    private String email = null;
    @SerializedName("dataNascimento")
    private String dataNascimento = null;

    /**
     * CPF do apostador
     **/
    @ApiModelProperty(value = "CPF do apostador")
    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    /**
     * Nome do apostador
     **/
    @ApiModelProperty(value = "Nome do apostador")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * Nome da Mãe do Apostador
     **/
    @ApiModelProperty(value = "Nome da Mãe do Apostador")
    public String getNomeDaMae() {
        return nomeDaMae;
    }

    public void setNomeDaMae(String nomeDaMae) {
        this.nomeDaMae = nomeDaMae;
    }

    /**
     * Email  do apostador
     **/
    @ApiModelProperty(value = "Email  do apostador")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Data de nascimento do apostador
     **/
    @ApiModelProperty(value = "Data de nascimento do apostador")
    public String getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EsqueciMinhaSenhaDTO esqueciMinhaSenhaDTO = (EsqueciMinhaSenhaDTO) o;
        return (this.cpf == null ? esqueciMinhaSenhaDTO.cpf == null : this.cpf.equals(esqueciMinhaSenhaDTO.cpf)) &&
                (this.nome == null ? esqueciMinhaSenhaDTO.nome == null : this.nome.equals(esqueciMinhaSenhaDTO.nome)) &&
                (this.nomeDaMae == null ? esqueciMinhaSenhaDTO.nomeDaMae == null : this.nomeDaMae.equals(esqueciMinhaSenhaDTO.nomeDaMae)) &&
                (this.email == null ? esqueciMinhaSenhaDTO.email == null : this.email.equals(esqueciMinhaSenhaDTO.email)) &&
                (this.dataNascimento == null ? esqueciMinhaSenhaDTO.dataNascimento == null : this.dataNascimento.equals(esqueciMinhaSenhaDTO.dataNascimento));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.cpf == null ? 0 : this.cpf.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        result = 31 * result + (this.nomeDaMae == null ? 0 : this.nomeDaMae.hashCode());
        result = 31 * result + (this.email == null ? 0 : this.email.hashCode());
        result = 31 * result + (this.dataNascimento == null ? 0 : this.dataNascimento.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class EsqueciMinhaSenhaDTO {\n" +
                "  cpf: " + cpf + "\n" +
                "  nome: " + nome + "\n" +
                "  nomeDaMae: " + nomeDaMae + "\n" +
                "  email: " + email + "\n" +
                "  dataNascimento: " + dataNascimento + "\n" +
                "}\n";
        return sb;
    }
}
