/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ExtracaoDTO {

    @SerializedName("municipioSorteio")
    private MunicipioDTO municipioSorteio = null;
    @SerializedName("ufSorteio")
    private UnidadeFederacaoDTO ufSorteio = null;
    @SerializedName("planoSorteio")
    private Long planoSorteio = null;
    @SerializedName("dataSorteio")
    private Date dataSorteio = null;
    @SerializedName("numero")
    private Long numero = null;
    @SerializedName("dv")
    private Long dv = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public MunicipioDTO getMunicipioSorteio() {
        return municipioSorteio;
    }

    public void setMunicipioSorteio(MunicipioDTO municipioSorteio) {
        this.municipioSorteio = municipioSorteio;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public UnidadeFederacaoDTO getUfSorteio() {
        return ufSorteio;
    }

    public void setUfSorteio(UnidadeFederacaoDTO ufSorteio) {
        this.ufSorteio = ufSorteio;
    }

    /**
     * Plano do Sorteio da Extraçao
     **/
    @ApiModelProperty(value = "Plano do Sorteio da Extraçao")
    public Long getPlanoSorteio() {
        return planoSorteio;
    }

    public void setPlanoSorteio(Long planoSorteio) {
        this.planoSorteio = planoSorteio;
    }

    /**
     * Data do sorteio da extração
     **/
    @ApiModelProperty(value = "Data do sorteio da extração")
    public Date getDataSorteio() {
        return dataSorteio;
    }

    public void setDataSorteio(Date dataSorteio) {
        this.dataSorteio = dataSorteio;
    }

    /**
     * Número do que????
     **/
    @ApiModelProperty(value = "Número do que????")
    public Long getNumero() {
        return numero;
    }

    public void setNumero(Long numero) {
        this.numero = numero;
    }

    /**
     * DV do que????
     **/
    @ApiModelProperty(value = "DV do que????")
    public Long getDv() {
        return dv;
    }

    public void setDv(Long dv) {
        this.dv = dv;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExtracaoDTO extracaoDTO = (ExtracaoDTO) o;
        return (this.municipioSorteio == null ? extracaoDTO.municipioSorteio == null : this.municipioSorteio.equals(extracaoDTO.municipioSorteio)) &&
                (this.ufSorteio == null ? extracaoDTO.ufSorteio == null : this.ufSorteio.equals(extracaoDTO.ufSorteio)) &&
                (this.planoSorteio == null ? extracaoDTO.planoSorteio == null : this.planoSorteio.equals(extracaoDTO.planoSorteio)) &&
                (this.dataSorteio == null ? extracaoDTO.dataSorteio == null : this.dataSorteio.equals(extracaoDTO.dataSorteio)) &&
                (this.numero == null ? extracaoDTO.numero == null : this.numero.equals(extracaoDTO.numero)) &&
                (this.dv == null ? extracaoDTO.dv == null : this.dv.equals(extracaoDTO.dv));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.municipioSorteio == null ? 0 : this.municipioSorteio.hashCode());
        result = 31 * result + (this.ufSorteio == null ? 0 : this.ufSorteio.hashCode());
        result = 31 * result + (this.planoSorteio == null ? 0 : this.planoSorteio.hashCode());
        result = 31 * result + (this.dataSorteio == null ? 0 : this.dataSorteio.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.dv == null ? 0 : this.dv.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ExtracaoDTO {\n" +
                "  municipioSorteio: " + municipioSorteio + "\n" +
                "  ufSorteio: " + ufSorteio + "\n" +
                "  planoSorteio: " + planoSorteio + "\n" +
                "  dataSorteio: " + dataSorteio + "\n" +
                "  numero: " + numero + "\n" +
                "  dv: " + dv + "\n" +
                "}\n";
        return sb;
    }
}
