/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class FaixaPremiadaDTO implements Serializable {

    @SerializedName("id")
    protected Long id = null;
    @SerializedName("numero")
    protected Integer numero = null;
    @SerializedName("sorteio")
    protected Integer sorteio = null;
    @SerializedName("nome")
    protected String nome = null;
    @SerializedName("valorLiquido")
    protected BigDecimal valorLiquido = null;
    @SerializedName("valorPremioCota")
    protected BigDecimal valorPremioCota = null;
    @SerializedName("quantidadeAcertos")
    protected Integer quantidadeAcertos = null;
    @SerializedName("descricaoAcerto")
    protected String descricaoAcerto = null;

    private String situacao;
    private int qtd;

    /**
     * Identificação do faixa de premiação da modalidade/concurso
     **/
    @ApiModelProperty(value = "Identificação do faixa de premiação da modalidade/concurso")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Número da faixa de premiação
     **/
    @ApiModelProperty(value = "Número da faixa de premiação")
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * Número do sorteio relacionado com a faixa de premiação
     **/
    @ApiModelProperty(value = "Número do sorteio relacionado com a faixa de premiação")
    public Integer getSorteio() {
        return sorteio;
    }

    public void setSorteio(Integer sorteio) {
        this.sorteio = sorteio;
    }

    /**
     * Nome da faixa de premiação
     **/
    @ApiModelProperty(value = "Nome da faixa de premiação")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * Valor líquido do prêmio da faixa de premiação
     **/
    @ApiModelProperty(value = "Valor líquido do prêmio da faixa de premiação")
    public BigDecimal getValorLiquido() {
        return valorLiquido;
    }

    public void setValorLiquido(BigDecimal valorLiquido) {
        this.valorLiquido = valorLiquido;
    }

    public String getSituacao() {
        return situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    public int getQtd() {
        return qtd;
    }

    public void setQtd(int qtd) {
        this.qtd = qtd;
    }

    public BigDecimal getValorPremioCota() {
        return valorPremioCota;
    }

    public void setValorPremioCota(BigDecimal valorPremioCota) {
        this.valorPremioCota = valorPremioCota;
    }

    public Integer getQuantidadeAcertos() {
        return quantidadeAcertos;
    }

    public void setQuantidadeAcertos(Integer quantidadeAcertos) {
        this.quantidadeAcertos = quantidadeAcertos;
    }

    public String getDescricaoAcerto() {
        return descricaoAcerto;
    }

    public void setDescricaoAcerto(String descricaoAcerto) {
        this.descricaoAcerto = descricaoAcerto;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FaixaPremiadaDTO faixaPremiadaDTO = (FaixaPremiadaDTO) o;
        return (this.id == null ? faixaPremiadaDTO.id == null : this.id.equals(faixaPremiadaDTO.id)) &&
                (this.numero == null ? faixaPremiadaDTO.numero == null : this.numero.equals(faixaPremiadaDTO.numero)) &&
                (this.sorteio == null ? faixaPremiadaDTO.sorteio == null : this.sorteio.equals(faixaPremiadaDTO.sorteio)) &&
                (this.nome == null ? faixaPremiadaDTO.nome == null : this.nome.equals(faixaPremiadaDTO.nome)) &&
                (this.valorLiquido == null ? faixaPremiadaDTO.valorLiquido == null : this.valorLiquido.equals(faixaPremiadaDTO.valorLiquido)) &&
                (this.valorPremioCota == null ? faixaPremiadaDTO.valorPremioCota == null : this.valorPremioCota.equals(faixaPremiadaDTO.valorPremioCota)) &&
                (this.quantidadeAcertos == null ? faixaPremiadaDTO.quantidadeAcertos == null : this.quantidadeAcertos.equals(faixaPremiadaDTO.quantidadeAcertos));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.sorteio == null ? 0 : this.sorteio.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        result = 31 * result + (this.valorLiquido == null ? 0 : this.valorLiquido.hashCode());
        result = 31 * result + (this.valorPremioCota == null ? 0 : this.valorPremioCota.hashCode());
        result = 31 * result + (this.quantidadeAcertos == null ? 0 : this.quantidadeAcertos.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class FaixaPremiadaDTO {\n" +
                "  id: " + id + "\n" +
                "  numero: " + numero + "\n" +
                "  sorteio: " + sorteio + "\n" +
                "  nome: " + nome + "\n" +
                "  valorLiquido: " + valorLiquido + "\n" +
                "  descricaoAcerto: " + descricaoAcerto + "\n" +
                "  valorPremioCota: " + valorPremioCota + "\n" +
                "  QuantidadeAcertos: " + quantidadeAcertos + "\n" +
                "}\n";
        return sb;
    }
}
