/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;

@ApiModel(description = "")
public class FaixasDTO implements Serializable {

    @SerializedName("numero")
    protected Long numero;
    @SerializedName("sorteio")
    protected Integer sorteio;
    @SerializedName("nome")
    protected String nome;
    @SerializedName("valorLiquido")
    protected Double valorLiquido;

    public Long getNumero() {
        return numero;
    }

    public void setNumero(Long numero) {
        this.numero = numero;
    }

    public Integer getSorteio() {
        return sorteio;
    }

    public void setSorteio(Integer sorteio) {
        this.sorteio = sorteio;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Double getValorLiquido() {
        return valorLiquido;
    }

    public void setValorLiquido(Double valorLiquido) {
        this.valorLiquido = valorLiquido;
    }


}
