/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class GanhadoresPorRegiaoDTO implements Serializable {

    @SerializedName("municipioSorteio")
    protected MunicipioDTO municipioSorteio = null;
    @SerializedName("ufSorteio")
    protected UnidadeFederacaoDTO ufSorteio = null;
    @SerializedName("descricao")
    protected String descricao = null;

    /**
     *
     **/
    @ApiModelProperty(value = "")
    public MunicipioDTO getMunicipioSorteio() {
        return municipioSorteio;
    }

    public void setMunicipioSorteio(MunicipioDTO municipioSorteio) {
        this.municipioSorteio = municipioSorteio;
    }

    /**
     *
     **/
    @ApiModelProperty(value = "")
    public UnidadeFederacaoDTO getUfSorteio() {
        return ufSorteio;
    }

    public void setUfSorteio(UnidadeFederacaoDTO ufSorteio) {
        this.ufSorteio = ufSorteio;
    }

    /**
     * Descrição relacionada a localidade onde houve ganhadores dos principais prêmios do concurso
     **/
    @ApiModelProperty(value = "Descrição relacionada a localidade onde houve ganhadores dos principais prêmios do concurso")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GanhadoresPorRegiaoDTO ganhadoresPorRegiaoDTO = (GanhadoresPorRegiaoDTO) o;
        return (this.municipioSorteio == null ? ganhadoresPorRegiaoDTO.municipioSorteio == null : this.municipioSorteio.equals(ganhadoresPorRegiaoDTO.municipioSorteio)) &&
                (this.ufSorteio == null ? ganhadoresPorRegiaoDTO.ufSorteio == null : this.ufSorteio.equals(ganhadoresPorRegiaoDTO.ufSorteio)) &&
                (this.descricao == null ? ganhadoresPorRegiaoDTO.descricao == null : this.descricao.equals(ganhadoresPorRegiaoDTO.descricao));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.municipioSorteio == null ? 0 : this.municipioSorteio.hashCode());
        result = 31 * result + (this.ufSorteio == null ? 0 : this.ufSorteio.hashCode());
        result = 31 * result + (this.descricao == null ? 0 : this.descricao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class GanhadoresPorRegiaoDTO {\n" +
                "  municipioSorteio: " + municipioSorteio + "\n" +
                "  ufSorteio: " + ufSorteio + "\n" +
                "  descricao: " + descricao + "\n" +
                "}\n";
        return sb;
    }
}
