/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.Duration;
import org.joda.time.Seconds;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.annotations.ApiModel;

@ApiModel(description = "")
public class GerarPixDTO implements Serializable {

    @SerializedName("pixCopiaECola")
    private String pixCopiaECola = null;
    @SerializedName("txId")
    private String txId = null;
    @SerializedName("qrcodeArrByte")
    private String qrcodeArrByte = null;
    @SerializedName("dataHoraExpiracao")
    private String dataHoraExpiracao;
    @SerializedName("dataHoraCriacao")
    private String dataHoraCriacao;
    @SerializedName("idCompra")
    private Long idCompra = null;
    @SerializedName("valorCobranca")
    private BigDecimal valorTotal;
    @SerializedName("isDetalhesCompras")
    private Boolean isDetalhesCompras = false;

    public String getPixCopiaECola() {
        return pixCopiaECola;
    }

    public void setPixCopiaECola(String pixCopiaECola) {
        this.pixCopiaECola = pixCopiaECola;
    }

    public String getTxId() {
        return txId;
    }

    public String getQrcodeArrByte() {
        return qrcodeArrByte;
    }

    public String getDataHoraExpiracao() {
        return dataHoraExpiracao;
    }

    public void setDataHoraExpiracao(String dataHoraExpiracao) {
        this.dataHoraExpiracao = dataHoraExpiracao;
    }

    public String getDataHoraCriacao() {
        return dataHoraCriacao;
    }

    public void setDataHoraCriacao(String dataHoraCriacao) {
        this.dataHoraCriacao = dataHoraCriacao;
    }

    public Long getIdCompra() {
        return idCompra;
    }

    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    public Boolean isDetalhesCompras() {
        return isDetalhesCompras;
    }

    public void setDetalhesCompras(Boolean detalhesCompras) {
        isDetalhesCompras = detalhesCompras;
    }

    public int getTimerSeconds() {
        DateTime agora     = new DateTime();
        DateTime expiracao = DateTime.parse(this.getDataHoraExpiracao());

        Seconds seconds = Seconds.secondsBetween(agora, expiracao);
        int     sec     = seconds.getSeconds();

        return sec * 1000;
    }

    public int getTimerZoneMilleSeconds(String dataHoraServidor) {
        DateTimeZone timeZone = DateTimeZone.forID("America/Sao_Paulo");

        DateTimeFormatter formatter = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS").withZone(timeZone);
        DateTime agora ;
        try {
            if (dataHoraServidor != null){
                agora = formatter.parseDateTime(dataHoraServidor);
            } else {
                DateTimeFormatter formatterWithZone = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ").withZone(timeZone);
                agora = formatterWithZone.parseDateTime(this.getDataHoraCriacao());
            }
        } catch (Exception e){
            agora = DateTime.now(timeZone);
        }

        DateTime expiracao = formatter.parseDateTime(this.getDataHoraExpiracao());

        Duration duration = new Duration(agora, expiracao);
        long diffInSeconds = duration.getStandardSeconds();

        return (int) diffInSeconds * 1000;
    }

    public Boolean estaNoPrazo(){
        final DateTimeZone zoneBrasil = DateTimeZone.forID("America/Sao_Paulo");
        DateTimeFormatter inputFormatter = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS");

        DateTime agora = DateTime.now(zoneBrasil);

        final DateTime expiracao = inputFormatter.withZone(zoneBrasil).parseDateTime(this.getDataHoraExpiracao());

        return agora.isBefore(expiracao);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        GerarPixDTO that = (GerarPixDTO) o;
        return dataHoraCriacao.equals(that.dataHoraCriacao) && pixCopiaECola.equals(that.pixCopiaECola) && txId.equals(that.txId) && qrcodeArrByte.equals(that.qrcodeArrByte) && dataHoraExpiracao.equals(that.dataHoraExpiracao) && idCompra.equals(that.idCompra) && isDetalhesCompras.equals(that.isDetalhesCompras);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pixCopiaECola, txId, qrcodeArrByte, dataHoraExpiracao, idCompra, isDetalhesCompras, dataHoraCriacao);
    }

    @Override
    public String toString() {
        return "GerarPixDTO{" +
                "pixCopiaECola='" + pixCopiaECola + '\'' +
                ", txId='" + txId + '\'' +
                ", qrcodeArrByte='" + qrcodeArrByte + '\'' +
                ", dataHoraExpiracao='" + dataHoraExpiracao + '\'' +
                ", dataHoraCriacao='" + dataHoraCriacao + '\'' +
                ", idCompra=" + idCompra +
                ", isDetalhesCompras=" + isDetalhesCompras +
                '}';
    }
}
