/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;
import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HistoricoCompraDTO
 */
public class HistoricoCompraDTO {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("situacao")
  private DTOEnumLong situacao = null;

  @SerializedName("loterica")
  private LotericaDTO loterica = null;

  @SerializedName("dataInicioCompra")
  private String dataInicioCompra = null;

  @SerializedName("dataEfetivacaoDebito")
  private String dataEfetivacaoDebito = null;

  @SerializedName("horaInicioCompra")
  private String horaInicioCompra = null;

  @SerializedName("dataFinalizacaoCompra")
  private String dataFinalizacaoCompra = null;

  @SerializedName("horaFinalizacaoCompra")
  private String horaFinalizacaoCompra = null;

  @SerializedName("valorTotal")
  private BigDecimal valorTotal = null;

  @SerializedName("timestampUltimaAlteracao")
  private String timestampUltimaAlteracao = null;

  @SerializedName("meioPagamento")
  private DTOEnumLong meioPagamento = null;

  @SerializedName("codigoMensageErro")
  private String codigoMensageErro = null;

  public HistoricoCompraDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador do histórico da compra
   * @return id
  **/
  @ApiModelProperty(value = "Identificador do histórico da compra")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public HistoricoCompraDTO situacao(DTOEnumLong situacao) {
    this.situacao = situacao;
    return this;
  }

   /**
   * Situação do histórico da compra
   * @return situacao
  **/
  @ApiModelProperty(value = "Situação do histórico da compra")
  public DTOEnumLong getSituacao() {
    return situacao;
  }

  public void setSituacao(DTOEnumLong situacao) {
    this.situacao = situacao;
  }

  public HistoricoCompraDTO loterica(LotericaDTO loterica) {
    this.loterica = loterica;
    return this;
  }

   /**
   * Lotérica da compra
   * @return loterica
  **/
  @ApiModelProperty(value = "Lotérica da compra")
  public LotericaDTO getLoterica() {
    return loterica;
  }

  public void setLoterica(LotericaDTO loterica) {
    this.loterica = loterica;
  }

  public HistoricoCompraDTO dataInicioCompra(String dataInicioCompra) {
    this.dataInicioCompra = dataInicioCompra;
    return this;
  }

   /**
   * Data de início da compra
   * @return dataInicioCompra
  **/
  @ApiModelProperty(value = "Data de início da compra")
  public String getDataInicioCompra() {
    return dataInicioCompra;
  }

  public void setDataInicioCompra(String dataInicioCompra) {
    this.dataInicioCompra = dataInicioCompra;
  }

  public HistoricoCompraDTO dataEfetivacaoDebito(String dataEfetivacaoDebito) {
    this.dataEfetivacaoDebito = dataEfetivacaoDebito;
    return this;
  }

   /**
   * Data em que o débito da compra foi efetivado
   * @return dataEfetivacaoDebito
  **/
  @ApiModelProperty(value = "Data em que o débito da compra foi efetivado")
  public String getDataEfetivacaoDebito() {
    return dataEfetivacaoDebito;
  }

  public void setDataEfetivacaoDebito(String dataEfetivacaoDebito) {
    this.dataEfetivacaoDebito = dataEfetivacaoDebito;
  }

  public HistoricoCompraDTO horaInicioCompra(String horaInicioCompra) {
    this.horaInicioCompra = horaInicioCompra;
    return this;
  }

   /**
   * Hora de início da compra
   * @return horaInicioCompra
  **/
  @ApiModelProperty(value = "Hora de início da compra")
  public String getHoraInicioCompra() {
    return horaInicioCompra;
  }

  public void setHoraInicioCompra(String horaInicioCompra) {
    this.horaInicioCompra = horaInicioCompra;
  }

  public HistoricoCompraDTO dataFinalizacaoCompra(String dataFinalizacaoCompra) {
    this.dataFinalizacaoCompra = dataFinalizacaoCompra;
    return this;
  }

   /**
   * Data de Finalização da compra. Ou seja, quando ela ficou na situação final
   * @return dataFinalizacaoCompra
  **/
  @ApiModelProperty(value = "Data de Finalização da compra. Ou seja, quando ela ficou na situação final")
  public String getDataFinalizacaoCompra() {
    return dataFinalizacaoCompra;
  }

  public void setDataFinalizacaoCompra(String dataFinalizacaoCompra) {
    this.dataFinalizacaoCompra = dataFinalizacaoCompra;
  }

  public HistoricoCompraDTO horaFinalizacaoCompra(String horaFinalizacaoCompra) {
    this.horaFinalizacaoCompra = horaFinalizacaoCompra;
    return this;
  }

   /**
   * Hora de Finalização da compra. Ou seja, quando ela ficou na situação final
   * @return horaFinalizacaoCompra
  **/
  @ApiModelProperty(value = "Hora de Finalização da compra. Ou seja, quando ela ficou na situação final")
  public String getHoraFinalizacaoCompra() {
    return horaFinalizacaoCompra;
  }

  public void setHoraFinalizacaoCompra(String horaFinalizacaoCompra) {
    this.horaFinalizacaoCompra = horaFinalizacaoCompra;
  }

  public HistoricoCompraDTO valorTotal(BigDecimal valorTotal) {
    this.valorTotal = valorTotal;
    return this;
  }

   /**
   * Valor total da compra
   * @return valorTotal
  **/
  @ApiModelProperty(value = "Valor total da compra")
  public BigDecimal getValorTotal() {
    return valorTotal;
  }

  public void setValorTotal(BigDecimal valorTotal) {
    this.valorTotal = valorTotal;
  }

  public HistoricoCompraDTO timestampUltimaAlteracao(String timestampUltimaAlteracao) {
    this.timestampUltimaAlteracao = timestampUltimaAlteracao;
    return this;
  }

   /**
   * Data/hora em que a compra foi atualizada pela última vez
   * @return timestampUltimaAlteracao
  **/
  @ApiModelProperty(value = "Data/hora em que a compra foi atualizada pela última vez")
  public String getTimestampUltimaAlteracao() {
    return timestampUltimaAlteracao;
  }

  public void setTimestampUltimaAlteracao(String timestampUltimaAlteracao) {
    this.timestampUltimaAlteracao = timestampUltimaAlteracao;
  }

  public HistoricoCompraDTO meioPagamento(DTOEnumLong meioPagamento) {
    this.meioPagamento = meioPagamento;
    return this;
  }

   /**
   * Identificação do meio de pagamento que foi utilizado para efetivar a compra
   * @return meioPagamento
  **/
  @ApiModelProperty(value = "Identificação do meio de pagamento que foi utilizado para efetivar a compra")
  public DTOEnumLong getMeioPagamento() {
    return meioPagamento;
  }

  public void setMeioPagamento(DTOEnumLong meioPagamento) {
    this.meioPagamento = meioPagamento;
  }

  public HistoricoCompraDTO codigoMensageErro(String codigoMensageErro) {
    this.codigoMensageErro = codigoMensageErro;
    return this;
  }

   /**
   * Código da mensagem de erro da compra retornado pelo Meio de Pagamento
   * @return codigoMensageErro
  **/
  @ApiModelProperty(value = "Código da mensagem de erro da compra retornado pelo Meio de Pagamento")
  public String getCodigoMensageErro() {
    return codigoMensageErro;
  }

  public void setCodigoMensageErro(String codigoMensageErro) {
    this.codigoMensageErro = codigoMensageErro;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricoCompraDTO historicoCompraDTO = (HistoricoCompraDTO) o;
    return Objects.equals(this.id, historicoCompraDTO.id) &&
        Objects.equals(this.situacao, historicoCompraDTO.situacao) &&
        Objects.equals(this.loterica, historicoCompraDTO.loterica) &&
        Objects.equals(this.dataInicioCompra, historicoCompraDTO.dataInicioCompra) &&
        Objects.equals(this.dataEfetivacaoDebito, historicoCompraDTO.dataEfetivacaoDebito) &&
        Objects.equals(this.horaInicioCompra, historicoCompraDTO.horaInicioCompra) &&
        Objects.equals(this.dataFinalizacaoCompra, historicoCompraDTO.dataFinalizacaoCompra) &&
        Objects.equals(this.horaFinalizacaoCompra, historicoCompraDTO.horaFinalizacaoCompra) &&
        Objects.equals(this.valorTotal, historicoCompraDTO.valorTotal) &&
        Objects.equals(this.timestampUltimaAlteracao, historicoCompraDTO.timestampUltimaAlteracao) &&
        Objects.equals(this.meioPagamento, historicoCompraDTO.meioPagamento) &&
        Objects.equals(this.codigoMensageErro, historicoCompraDTO.codigoMensageErro);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, situacao, loterica, dataInicioCompra, dataEfetivacaoDebito, horaInicioCompra, dataFinalizacaoCompra, horaFinalizacaoCompra, valorTotal, timestampUltimaAlteracao, meioPagamento, codigoMensageErro);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricoCompraDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    situacao: ").append(toIndentedString(situacao)).append("\n");
    sb.append("    loterica: ").append(toIndentedString(loterica)).append("\n");
    sb.append("    dataInicioCompra: ").append(toIndentedString(dataInicioCompra)).append("\n");
    sb.append("    dataEfetivacaoDebito: ").append(toIndentedString(dataEfetivacaoDebito)).append("\n");
    sb.append("    horaInicioCompra: ").append(toIndentedString(horaInicioCompra)).append("\n");
    sb.append("    dataFinalizacaoCompra: ").append(toIndentedString(dataFinalizacaoCompra)).append("\n");
    sb.append("    horaFinalizacaoCompra: ").append(toIndentedString(horaFinalizacaoCompra)).append("\n");
    sb.append("    valorTotal: ").append(toIndentedString(valorTotal)).append("\n");
    sb.append("    timestampUltimaAlteracao: ").append(toIndentedString(timestampUltimaAlteracao)).append("\n");
    sb.append("    meioPagamento: ").append(toIndentedString(meioPagamento)).append("\n");
    sb.append("    codigoMensageErro: ").append(toIndentedString(codigoMensageErro)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

