/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HistoricoApostaDTO
 */
public class HistoricoApostaDTO {
  @SerializedName("id")
  private Long id = null;

  /**
   * Modalidade relacionada com a aposta
   */
  @JsonAdapter(ModalidadeEnum.Adapter.class)
  public enum ModalidadeEnum {
    DIA_DE_SORTE("DIA_DE_SORTE"),
    
    DUPLA_SENA("DUPLA_SENA"),
    
    LOTECA("LOTECA"),
    
    LOTOFACIL("LOTOFACIL"),
    
    LOTOGOL("LOTOGOL"),
    
    LOTOMANIA("LOTOMANIA"),
    
    MEGA_SENA("MEGA_SENA"),
    
    QUINA("QUINA"),
    
    TIMEMANIA("TIMEMANIA");

    private String value;

    ModalidadeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModalidadeEnum fromValue(String text) {
      for (ModalidadeEnum b : ModalidadeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ModalidadeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModalidadeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModalidadeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ModalidadeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("modalidade")
  private ModalidadeEnum modalidade = null;

  @SerializedName("tipoConcurso")
  private DTOEnumCharacter tipoConcurso = null;

  @SerializedName("partidasLotogol")
  private List<PartidaLotogolDTO> partidasLotogol = null;

  @SerializedName("partidasLoteca")
  private List<PartidaLotecaDTO> partidasLoteca = null;

  @SerializedName("numerosSelecionados")
  private List<Integer> numerosSelecionados = null;

  @SerializedName("indicadorSurpresinha")
  private DTOEnumInteger indicadorSurpresinha = null;

  @SerializedName("valor")
  private BigDecimal valor = null;

  @SerializedName("concursoAlvo")
  private Integer concursoAlvo = null;

  @SerializedName("quantidadeTeimosinhas")
  private Integer quantidadeTeimosinhas = null;

  @SerializedName("quantidadeApostas")
  private Integer quantidadeApostas = null;

  @SerializedName("espelho")
  private Boolean espelho = null;

  @SerializedName("timeDoCoracao")
  private ParametroEquipe timeDoCoracao = null;

  @SerializedName("mesDeSorte")
  private ParametroMesDeSorte mesDeSorte = null;

  @SerializedName("concursoInicial")
  private Integer concursoInicial = null;

  @SerializedName("situacao")
  private DTOEnumLong situacao = null;

  @SerializedName("troca")
  private Boolean troca = null;

  @SerializedName("dataEfetivacao")
  private String dataEfetivacao = null;

  @SerializedName("horaEfetivacao")
  private String horaEfetivacao = null;

  @SerializedName("loterica")
  private LotericaDTO loterica = null;

  @SerializedName("vinculoEspelho")
  private Long vinculoEspelho = null;

  @SerializedName("quantidadeNumeros")
  private Integer quantidadeNumeros = null;

  @SerializedName("surpresinha")
  private Boolean surpresinha = null;

  public HistoricoApostaDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador da Aposta
   * @return id
  **/
  @ApiModelProperty(value = "Identificador da Aposta")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public HistoricoApostaDTO modalidade(ModalidadeEnum modalidade) {
    this.modalidade = modalidade;
    return this;
  }

   /**
   * Modalidade relacionada com a aposta
   * @return modalidade
  **/
  @ApiModelProperty(required = true, value = "Modalidade relacionada com a aposta")
  public ModalidadeEnum getModalidade() {
    return modalidade;
  }

  public void setModalidade(ModalidadeEnum modalidade) {
    this.modalidade = modalidade;
  }

  public HistoricoApostaDTO tipoConcurso(DTOEnumCharacter tipoConcurso) {
    this.tipoConcurso = tipoConcurso;
    return this;
  }

   /**
   * Identificador do tipo de concurso. 1 &#x3D; Normal, 2 &#x3D; Especial
   * @return tipoConcurso
  **/
  @ApiModelProperty(required = true, value = "Identificador do tipo de concurso. 1 = Normal, 2 = Especial")
  public DTOEnumCharacter getTipoConcurso() {
    return tipoConcurso;
  }

  public void setTipoConcurso(DTOEnumCharacter tipoConcurso) {
    this.tipoConcurso = tipoConcurso;
  }

  public HistoricoApostaDTO partidasLotogol(List<PartidaLotogolDTO> partidasLotogol) {
    this.partidasLotogol = partidasLotogol;
    return this;
  }

  public HistoricoApostaDTO addPartidasLotogolItem(PartidaLotogolDTO partidasLotogolItem) {
    if (this.partidasLotogol == null) {
      this.partidasLotogol = new ArrayList<PartidaLotogolDTO>();
    }
    this.partidasLotogol.add(partidasLotogolItem);
    return this;
  }

   /**
   * Resultado das partidas de futebol relacionadas com a aposta, quando essa for relacionada com a modalidade Lotogol
   * @return partidasLotogol
  **/
  @ApiModelProperty(value = "Resultado das partidas de futebol relacionadas com a aposta, quando essa for relacionada com a modalidade Lotogol")
  public List<PartidaLotogolDTO> getPartidasLotogol() {
    return partidasLotogol;
  }

  public void setPartidasLotogol(List<PartidaLotogolDTO> partidasLotogol) {
    this.partidasLotogol = partidasLotogol;
  }

  public HistoricoApostaDTO partidasLoteca(List<PartidaLotecaDTO> partidasLoteca) {
    this.partidasLoteca = partidasLoteca;
    return this;
  }

  public HistoricoApostaDTO addPartidasLotecaItem(PartidaLotecaDTO partidasLotecaItem) {
    if (this.partidasLoteca == null) {
      this.partidasLoteca = new ArrayList<PartidaLotecaDTO>();
    }
    this.partidasLoteca.add(partidasLotecaItem);
    return this;
  }

   /**
   * Resultado das partidas de futebol, informada pelo apostador, quando a aposta estiver relacionada com a modalidade Loteca
   * @return partidasLoteca
  **/
  @ApiModelProperty(value = "Resultado das partidas de futebol, informada pelo apostador, quando a aposta estiver relacionada com a modalidade Loteca")
  public List<PartidaLotecaDTO> getPartidasLoteca() {
    return partidasLoteca;
  }

  public void setPartidasLoteca(List<PartidaLotecaDTO> partidasLoteca) {
    this.partidasLoteca = partidasLoteca;
  }

  public HistoricoApostaDTO numerosSelecionados(List<Integer> numerosSelecionados) {
    this.numerosSelecionados = numerosSelecionados;
    return this;
  }

  public HistoricoApostaDTO addNumerosSelecionadosItem(Integer numerosSelecionadosItem) {
    if (this.numerosSelecionados == null) {
      this.numerosSelecionados = new ArrayList<Integer>();
    }
    this.numerosSelecionados.add(numerosSelecionadosItem);
    return this;
  }

   /**
   * Prognósticos relacionados com a aposta, no caso de aposta NÃO EFETIVADA e SURPRESINHA, esse campo pode ser informado vazio
   * @return numerosSelecionados
  **/
  @ApiModelProperty(value = "Prognósticos relacionados com a aposta, no caso de aposta NÃO EFETIVADA e SURPRESINHA, esse campo pode ser informado vazio")
  public List<Integer> getNumerosSelecionados() {
    return numerosSelecionados;
  }

  public void setNumerosSelecionados(List<Integer> numerosSelecionados) {
    this.numerosSelecionados = numerosSelecionados;
  }

  public HistoricoApostaDTO indicadorSurpresinha(DTOEnumInteger indicadorSurpresinha) {
    this.indicadorSurpresinha = indicadorSurpresinha;
    return this;
  }

   /**
   * Identificador se é surpresinha. 1 &#x3D; Não surpresinha, 2 &#x3D; Surpresinha, 3 &#x3D; Surpresinha numérica
   * @return indicadorSurpresinha
  **/
  @ApiModelProperty(required = true, value = "Identificador se é surpresinha. 1 = Não surpresinha, 2 = Surpresinha, 3 = Surpresinha numérica")
  public DTOEnumInteger getIndicadorSurpresinha() {
    return indicadorSurpresinha;
  }

  public void setIndicadorSurpresinha(DTOEnumInteger indicadorSurpresinha) {
    this.indicadorSurpresinha = indicadorSurpresinha;
  }

  public HistoricoApostaDTO valor(BigDecimal valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor da Aposta
   * @return valor
  **/
  @ApiModelProperty(required = true, value = "Valor da Aposta")
  public BigDecimal getValor() {
    return valor;
  }

  public void setValor(BigDecimal valor) {
    this.valor = valor;
  }

  public HistoricoApostaDTO concursoAlvo(Integer concursoAlvo) {
    this.concursoAlvo = concursoAlvo;
    return this;
  }

   /**
   * Número do concurso que estava disponível no momento da inclusão da aposta no carrinho
   * @return concursoAlvo
  **/
  @ApiModelProperty(required = true, value = "Número do concurso que estava disponível no momento da inclusão da aposta no carrinho")
  public Integer getConcursoAlvo() {
    return concursoAlvo;
  }

  public void setConcursoAlvo(Integer concursoAlvo) {
    this.concursoAlvo = concursoAlvo;
  }

  public HistoricoApostaDTO quantidadeTeimosinhas(Integer quantidadeTeimosinhas) {
    this.quantidadeTeimosinhas = quantidadeTeimosinhas;
    return this;
  }

   /**
   * Quantidade de Teimosinhas relacionadas com a aposta
   * @return quantidadeTeimosinhas
  **/
  @ApiModelProperty(value = "Quantidade de Teimosinhas relacionadas com a aposta")
  public Integer getQuantidadeTeimosinhas() {
    return quantidadeTeimosinhas;
  }

  public void setQuantidadeTeimosinhas(Integer quantidadeTeimosinhas) {
    this.quantidadeTeimosinhas = quantidadeTeimosinhas;
  }

  public HistoricoApostaDTO quantidadeApostas(Integer quantidadeApostas) {
    this.quantidadeApostas = quantidadeApostas;
    return this;
  }

   /**
   * Quantidade de apostas jogadas, utilizado apenas para a modalidade Lotogol
   * @return quantidadeApostas
  **/
  @ApiModelProperty(value = "Quantidade de apostas jogadas, utilizado apenas para a modalidade Lotogol")
  public Integer getQuantidadeApostas() {
    return quantidadeApostas;
  }

  public void setQuantidadeApostas(Integer quantidadeApostas) {
    this.quantidadeApostas = quantidadeApostas;
  }

  public HistoricoApostaDTO espelho(Boolean espelho) {
    this.espelho = espelho;
    return this;
  }

   /**
   * Identificação se a aposta e uma aposta espelho, tendo o valor TRUE apenas para apostas da Lotomania, caso seja selecionada pelo apostador
   * @return espelho
  **/
  @ApiModelProperty(value = "Identificação se a aposta e uma aposta espelho, tendo o valor TRUE apenas para apostas da Lotomania, caso seja selecionada pelo apostador")
  public Boolean isEspelho() {
    return espelho;
  }

  public void setEspelho(Boolean espelho) {
    this.espelho = espelho;
  }

  public HistoricoApostaDTO timeDoCoracao(ParametroEquipe timeDoCoracao) {
    this.timeDoCoracao = timeDoCoracao;
    return this;
  }

   /**
   * Time do coração da aposta, referente a apostas da Timemania
   * @return timeDoCoracao
  **/
  @ApiModelProperty(value = "Time do coração da aposta, referente a apostas da Timemania")
  public ParametroEquipe getTimeDoCoracao() {
    return timeDoCoracao;
  }

  public void setTimeDoCoracao(ParametroEquipe timeDoCoracao) {
    this.timeDoCoracao = timeDoCoracao;
  }

  public HistoricoApostaDTO mesDeSorte(ParametroMesDeSorte mesDeSorte) {
    this.mesDeSorte = mesDeSorte;
    return this;
  }

   /**
   * Mês de sorte da aposta, referente a apostas do dia de sorte
   * @return mesDeSorte
  **/
  @ApiModelProperty(value = "Mês de sorte da aposta, referente a apostas do dia de sorte")
  public ParametroMesDeSorte getMesDeSorte() {
    return mesDeSorte;
  }

  public void setMesDeSorte(ParametroMesDeSorte mesDeSorte) {
    this.mesDeSorte = mesDeSorte;
  }

  public HistoricoApostaDTO concursoInicial(Integer concursoInicial) {
    this.concursoInicial = concursoInicial;
    return this;
  }

   /**
   * Quando a aposta tiver sido efetivada, o concurso inicial será informado com o número do concurso em que a aposta foi registrada
   * @return concursoInicial
  **/
  @ApiModelProperty(value = "Quando a aposta tiver sido efetivada, o concurso inicial será informado com o número do concurso em que a aposta foi registrada")
  public Integer getConcursoInicial() {
    return concursoInicial;
  }

  public void setConcursoInicial(Integer concursoInicial) {
    this.concursoInicial = concursoInicial;
  }

  public HistoricoApostaDTO situacao(DTOEnumLong situacao) {
    this.situacao = situacao;
    return this;
  }

   /**
   * Get situacao
   * @return situacao
  **/
  @ApiModelProperty(value = "")
  public DTOEnumLong getSituacao() {
    return situacao;
  }

  public void setSituacao(DTOEnumLong situacao) {
    this.situacao = situacao;
  }

  public HistoricoApostaDTO troca(Boolean troca) {
    this.troca = troca;
    return this;
  }

   /**
   * Identificação se existe recibo de troca relacionado a aposta
   * @return troca
  **/
  @ApiModelProperty(value = "Identificação se existe recibo de troca relacionado a aposta")
  public Boolean isTroca() {
    return troca;
  }

  public void setTroca(Boolean troca) {
    this.troca = troca;
  }

  public HistoricoApostaDTO dataEfetivacao(String dataEfetivacao) {
    this.dataEfetivacao = dataEfetivacao;
    return this;
  }

   /**
   * Data de Efetivação da Aposta
   * @return dataEfetivacao
  **/
  @ApiModelProperty(value = "Data de Efetivação da Aposta")
  public String getDataEfetivacao() {
    return dataEfetivacao;
  }

  public void setDataEfetivacao(String dataEfetivacao) {
    this.dataEfetivacao = dataEfetivacao;
  }

  public HistoricoApostaDTO horaEfetivacao(String horaEfetivacao) {
    this.horaEfetivacao = horaEfetivacao;
    return this;
  }

   /**
   * Horário emque foi efetivada a aposta
   * @return horaEfetivacao
  **/
  @ApiModelProperty(value = "Horário emque foi efetivada a aposta")
  public String getHoraEfetivacao() {
    return horaEfetivacao;
  }

  public void setHoraEfetivacao(String horaEfetivacao) {
    this.horaEfetivacao = horaEfetivacao;
  }

  public HistoricoApostaDTO loterica(LotericaDTO loterica) {
    this.loterica = loterica;
    return this;
  }

   /**
   * Get loterica
   * @return loterica
  **/
  @ApiModelProperty(value = "")
  public LotericaDTO getLoterica() {
    return loterica;
  }

  public void setLoterica(LotericaDTO loterica) {
    this.loterica = loterica;
  }

  public HistoricoApostaDTO vinculoEspelho(Long vinculoEspelho) {
    this.vinculoEspelho = vinculoEspelho;
    return this;
  }

   /**
   * Indica se a aposta possuí uma aposta espelho, válido apenas para a modalidade Lotomania
   * @return vinculoEspelho
  **/
  @ApiModelProperty(value = "Indica se a aposta possuí uma aposta espelho, válido apenas para a modalidade Lotomania")
  public Long getVinculoEspelho() {
    return vinculoEspelho;
  }

  public void setVinculoEspelho(Long vinculoEspelho) {
    this.vinculoEspelho = vinculoEspelho;
  }

  public HistoricoApostaDTO quantidadeNumeros(Integer quantidadeNumeros) {
    this.quantidadeNumeros = quantidadeNumeros;
    return this;
  }

   /**
   * Quantidade de Números de prognósticos da aposta
   * @return quantidadeNumeros
  **/
  @ApiModelProperty(value = "Quantidade de Números de prognósticos da aposta")
  public Integer getQuantidadeNumeros() {
    return quantidadeNumeros;
  }

  public void setQuantidadeNumeros(Integer quantidadeNumeros) {
    this.quantidadeNumeros = quantidadeNumeros;
  }

  public HistoricoApostaDTO surpresinha(Boolean surpresinha) {
    this.surpresinha = surpresinha;
    return this;
  }

   /**
   * Get surpresinha
   * @return surpresinha
  **/
  @ApiModelProperty(value = "")
  public Boolean isSurpresinha() {
    return surpresinha;
  }

  public void setSurpresinha(Boolean surpresinha) {
    this.surpresinha = surpresinha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricoApostaDTO historicoApostaDTO = (HistoricoApostaDTO) o;
    return Objects.equals(this.id, historicoApostaDTO.id) &&
        Objects.equals(this.modalidade, historicoApostaDTO.modalidade) &&
        Objects.equals(this.tipoConcurso, historicoApostaDTO.tipoConcurso) &&
        Objects.equals(this.partidasLotogol, historicoApostaDTO.partidasLotogol) &&
        Objects.equals(this.partidasLoteca, historicoApostaDTO.partidasLoteca) &&
        Objects.equals(this.numerosSelecionados, historicoApostaDTO.numerosSelecionados) &&
        Objects.equals(this.indicadorSurpresinha, historicoApostaDTO.indicadorSurpresinha) &&
        Objects.equals(this.valor, historicoApostaDTO.valor) &&
        Objects.equals(this.concursoAlvo, historicoApostaDTO.concursoAlvo) &&
        Objects.equals(this.quantidadeTeimosinhas, historicoApostaDTO.quantidadeTeimosinhas) &&
        Objects.equals(this.quantidadeApostas, historicoApostaDTO.quantidadeApostas) &&
        Objects.equals(this.espelho, historicoApostaDTO.espelho) &&
        Objects.equals(this.timeDoCoracao, historicoApostaDTO.timeDoCoracao) &&
        Objects.equals(this.mesDeSorte, historicoApostaDTO.mesDeSorte) &&
        Objects.equals(this.concursoInicial, historicoApostaDTO.concursoInicial) &&
        Objects.equals(this.situacao, historicoApostaDTO.situacao) &&
        Objects.equals(this.troca, historicoApostaDTO.troca) &&
        Objects.equals(this.dataEfetivacao, historicoApostaDTO.dataEfetivacao) &&
        Objects.equals(this.horaEfetivacao, historicoApostaDTO.horaEfetivacao) &&
        Objects.equals(this.loterica, historicoApostaDTO.loterica) &&
        Objects.equals(this.vinculoEspelho, historicoApostaDTO.vinculoEspelho) &&
        Objects.equals(this.quantidadeNumeros, historicoApostaDTO.quantidadeNumeros) &&
        Objects.equals(this.surpresinha, historicoApostaDTO.surpresinha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, modalidade, tipoConcurso, partidasLotogol, partidasLoteca, numerosSelecionados, indicadorSurpresinha, valor, concursoAlvo, quantidadeTeimosinhas, quantidadeApostas, espelho, timeDoCoracao, mesDeSorte, concursoInicial, situacao, troca, dataEfetivacao, horaEfetivacao, loterica, vinculoEspelho, quantidadeNumeros, surpresinha);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricoApostaDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modalidade: ").append(toIndentedString(modalidade)).append("\n");
    sb.append("    tipoConcurso: ").append(toIndentedString(tipoConcurso)).append("\n");
    sb.append("    partidasLotogol: ").append(toIndentedString(partidasLotogol)).append("\n");
    sb.append("    partidasLoteca: ").append(toIndentedString(partidasLoteca)).append("\n");
    sb.append("    numerosSelecionados: ").append(toIndentedString(numerosSelecionados)).append("\n");
    sb.append("    indicadorSurpresinha: ").append(toIndentedString(indicadorSurpresinha)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    concursoAlvo: ").append(toIndentedString(concursoAlvo)).append("\n");
    sb.append("    quantidadeTeimosinhas: ").append(toIndentedString(quantidadeTeimosinhas)).append("\n");
    sb.append("    quantidadeApostas: ").append(toIndentedString(quantidadeApostas)).append("\n");
    sb.append("    espelho: ").append(toIndentedString(espelho)).append("\n");
    sb.append("    timeDoCoracao: ").append(toIndentedString(timeDoCoracao)).append("\n");
    sb.append("    mesDeSorte: ").append(toIndentedString(mesDeSorte)).append("\n");
    sb.append("    concursoInicial: ").append(toIndentedString(concursoInicial)).append("\n");
    sb.append("    situacao: ").append(toIndentedString(situacao)).append("\n");
    sb.append("    troca: ").append(toIndentedString(troca)).append("\n");
    sb.append("    dataEfetivacao: ").append(toIndentedString(dataEfetivacao)).append("\n");
    sb.append("    horaEfetivacao: ").append(toIndentedString(horaEfetivacao)).append("\n");
    sb.append("    loterica: ").append(toIndentedString(loterica)).append("\n");
    sb.append("    vinculoEspelho: ").append(toIndentedString(vinculoEspelho)).append("\n");
    sb.append("    quantidadeNumeros: ").append(toIndentedString(quantidadeNumeros)).append("\n");
    sb.append("    surpresinha: ").append(toIndentedString(surpresinha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

