/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HistoricoFaixaPremiadaDTO
 */
public class HistoricoFaixaPremiadaDTO {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("numero")
  private Integer numero = null;

  @SerializedName("sorteio")
  private Integer sorteio = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("valorLiquido")
  private BigDecimal valorLiquido = null;

  public HistoricoFaixaPremiadaDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Identificação do faixa de premiação da modalidade/concurso
   * @return id
  **/
  @ApiModelProperty(value = "Identificação do faixa de premiação da modalidade/concurso")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public HistoricoFaixaPremiadaDTO numero(Integer numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número da faixa de premiação
   * @return numero
  **/
  @ApiModelProperty(value = "Número da faixa de premiação")
  public Integer getNumero() {
    return numero;
  }

  public void setNumero(Integer numero) {
    this.numero = numero;
  }

  public HistoricoFaixaPremiadaDTO sorteio(Integer sorteio) {
    this.sorteio = sorteio;
    return this;
  }

   /**
   * Número do sorteio relacionado com a faixa de premiação
   * @return sorteio
  **/
  @ApiModelProperty(value = "Número do sorteio relacionado com a faixa de premiação")
  public Integer getSorteio() {
    return sorteio;
  }

  public void setSorteio(Integer sorteio) {
    this.sorteio = sorteio;
  }

  public HistoricoFaixaPremiadaDTO nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome da faixa de premiação
   * @return nome
  **/
  @ApiModelProperty(value = "Nome da faixa de premiação")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public HistoricoFaixaPremiadaDTO valorLiquido(BigDecimal valorLiquido) {
    this.valorLiquido = valorLiquido;
    return this;
  }

   /**
   * Valor líquido do prêmio da faixa de premiação
   * @return valorLiquido
  **/
  @ApiModelProperty(value = "Valor líquido do prêmio da faixa de premiação")
  public BigDecimal getValorLiquido() {
    return valorLiquido;
  }

  public void setValorLiquido(BigDecimal valorLiquido) {
    this.valorLiquido = valorLiquido;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricoFaixaPremiadaDTO historicoFaixaPremiadaDTO = (HistoricoFaixaPremiadaDTO) o;
    return Objects.equals(this.id, historicoFaixaPremiadaDTO.id) &&
        Objects.equals(this.numero, historicoFaixaPremiadaDTO.numero) &&
        Objects.equals(this.sorteio, historicoFaixaPremiadaDTO.sorteio) &&
        Objects.equals(this.nome, historicoFaixaPremiadaDTO.nome) &&
        Objects.equals(this.valorLiquido, historicoFaixaPremiadaDTO.valorLiquido);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, numero, sorteio, nome, valorLiquido);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricoFaixaPremiadaDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    sorteio: ").append(toIndentedString(sorteio)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    valorLiquido: ").append(toIndentedString(valorLiquido)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

