/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;
import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HistoricoConcursoPremiadoDTO
 */
public class HistoricoConcursoPremiadoDTO {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("concurso")
  private ConcursoDTO concurso = null;

  @SerializedName("valorBruto")
  private BigDecimal valorBruto = null;

  @SerializedName("valorLiquido")
  private BigDecimal valorLiquido = null;

  @SerializedName("valorIRRF")
  private BigDecimal valorIRRF = null;

  @SerializedName("faixas")
  private List<HistoricoFaixaPremiadaDTO> faixas = null;

  public HistoricoConcursoPremiadoDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Identificação do concurso premiado
   * @return id
  **/
  @ApiModelProperty(value = "Identificação do concurso premiado")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public HistoricoConcursoPremiadoDTO concurso(ConcursoDTO concurso) {
    this.concurso = concurso;
    return this;
  }

   /**
   * Get concurso
   * @return concurso
  **/
  @ApiModelProperty(value = "")
  public ConcursoDTO getConcurso() {
    return concurso;
  }

  public void setConcurso(ConcursoDTO concurso) {
    this.concurso = concurso;
  }

  public HistoricoConcursoPremiadoDTO valorBruto(BigDecimal valorBruto) {
    this.valorBruto = valorBruto;
    return this;
  }

   /**
   * Valor Bruto do prêmio do concurso
   * @return valorBruto
  **/
  @ApiModelProperty(value = "Valor Bruto do prêmio do concurso")
  public BigDecimal getValorBruto() {
    return valorBruto;
  }

  public void setValorBruto(BigDecimal valorBruto) {
    this.valorBruto = valorBruto;
  }

  public HistoricoConcursoPremiadoDTO valorLiquido(BigDecimal valorLiquido) {
    this.valorLiquido = valorLiquido;
    return this;
  }

   /**
   * Valor líquido do prêmio do concurso.
   * @return valorLiquido
  **/
  @ApiModelProperty(value = "Valor líquido do prêmio do concurso.")
  public BigDecimal getValorLiquido() {
    return valorLiquido;
  }

  public void setValorLiquido(BigDecimal valorLiquido) {
    this.valorLiquido = valorLiquido;
  }

  public HistoricoConcursoPremiadoDTO valorIRRF(BigDecimal valorIRRF) {
    this.valorIRRF = valorIRRF;
    return this;
  }

   /**
   * Valor da retenção de IRRF do prêmio do concurso
   * @return valorIRRF
  **/
  @ApiModelProperty(value = "Valor da retenção de IRRF do prêmio do concurso")
  public BigDecimal getValorIRRF() {
    return valorIRRF;
  }

  public void setValorIRRF(BigDecimal valorIRRF) {
    this.valorIRRF = valorIRRF;
  }

  public HistoricoConcursoPremiadoDTO faixas(List<HistoricoFaixaPremiadaDTO> faixas) {
    this.faixas = faixas;
    return this;
  }

  public HistoricoConcursoPremiadoDTO addFaixasItem(HistoricoFaixaPremiadaDTO faixasItem) {
    if (this.faixas == null) {
      this.faixas = new ArrayList<HistoricoFaixaPremiadaDTO>();
    }
    this.faixas.add(faixasItem);
    return this;
  }

   /**
   * Lista com as Faixas de Premiação da Modalidade/Concurso
   * @return faixas
  **/
  @ApiModelProperty(value = "Lista com as Faixas de Premiação da Modalidade/Concurso")
  public List<HistoricoFaixaPremiadaDTO> getFaixas() {
    return faixas;
  }

  public void setFaixas(List<HistoricoFaixaPremiadaDTO> faixas) {
    this.faixas = faixas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricoConcursoPremiadoDTO historicoConcursoPremiadoDTO = (HistoricoConcursoPremiadoDTO) o;
    return Objects.equals(this.id, historicoConcursoPremiadoDTO.id) &&
        Objects.equals(this.concurso, historicoConcursoPremiadoDTO.concurso) &&
        Objects.equals(this.valorBruto, historicoConcursoPremiadoDTO.valorBruto) &&
        Objects.equals(this.valorLiquido, historicoConcursoPremiadoDTO.valorLiquido) &&
        Objects.equals(this.valorIRRF, historicoConcursoPremiadoDTO.valorIRRF) &&
        Objects.equals(this.faixas, historicoConcursoPremiadoDTO.faixas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, concurso, valorBruto, valorLiquido, valorIRRF, faixas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricoConcursoPremiadoDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    concurso: ").append(toIndentedString(concurso)).append("\n");
    sb.append("    valorBruto: ").append(toIndentedString(valorBruto)).append("\n");
    sb.append("    valorLiquido: ").append(toIndentedString(valorLiquido)).append("\n");
    sb.append("    valorIRRF: ").append(toIndentedString(valorIRRF)).append("\n");
    sb.append("    faixas: ").append(toIndentedString(faixas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

