/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import br.gov.caixa.loterias.apostas.model.bean.SessaoUsuario;
import br.gov.caixa.loterias.apostas.utils.AppUtils;
import br.gov.caixa.loterias.apostas.utils.Utils;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class
IdentificaoDeUmaApostaDas8Modalidades<T> implements Serializable {

	@SerializedName("id")
	protected Long id = null;
	@SerializedName("modalidade")
	protected ModalidadeEnum modalidade = null;
	@SerializedName("tipoConcurso")
	protected DTOEnumCharacter tipoConcurso = null;
	@SerializedName("partidasLotogol")
	protected List<PartidaLotogolDTO> partidasLotogol = null;
	@SerializedName("partidasLoteca")
	protected List<PartidaLotecaDTO> partidasLoteca = null;
	@SerializedName(value = "numerosSelecionados")
	public T numerosSelecionados = null;
	@SerializedName(value = "numerosSelecionadosMaisMilionariaTrevo")
	public List<Integer> trevosSelecionados = null;
	@SerializedName("indicadorSurpresinha")
	protected DTOEnumInteger indicadorSurpresinha = null;
	@SerializedName("valor")
	protected BigDecimal valor = null;
	@SerializedName("concursoAlvo")
	protected Integer concursoAlvo = null;
	@SerializedName("quantidadeTeimosinhas")
	protected Integer quantidadeTeimosinhas = null;
	@SerializedName("quantidadeApostas")
	protected Integer quantidadeApostas = null;
	@SerializedName("espelho")
	protected Boolean espelho = null;
	@SerializedName("geraEspelho")
	protected Boolean geraEspelho = null;
	@SerializedName("timeDoCoracao")
	protected ParametroEquipe timeDoCoracao = null;
	@SerializedName("concursoInicial")
	protected Integer concursoInicial = null;
	@SerializedName("situacao")
	protected DTOEnumLong situacao = null;
	@SerializedName("troca")
	protected Boolean troca = null;
	@SerializedName("dataEfetivacao")
	protected String dataEfetivacao = null;
	@SerializedName("horaEfetivacao")
	protected String horaEfetivacao = null;
	@SerializedName("dataSorteio")
	private String dataSorteio = null;
	@SerializedName("dataCompra")
	protected String dataCompra = null;
	@SerializedName("horaCompra")
	protected String horaCompra = null;
	@SerializedName("subcanalPagamento")
	protected String subcanalPagamento = null;
	//@SerializedName("loterica")
	//protected LotericaDTO loterica = null;
	@SerializedName("vinculoEspelho")
	protected Long vinculoEspelho = null;
	@SerializedName("quantidadeNumeros")
	protected Integer quantidadeNumeros = null;
	@SerializedName("quantidadeNumerosMaisMilionariaTrevo")
	protected Integer quantidadeTrevos = null;
	@SerializedName("surpresinha")
	protected Boolean surpresinha = null;
	@SerializedName("mesDeSorte")
	protected ParametroMesDeSorte mesDeSorte = null;
	@Expose(serialize = false, deserialize = false)
	protected transient Long idDB;
	@Expose(serialize = false, deserialize = false)
	protected transient Integer quantidadeSurpresinhas = null;

	@SerializedName("dataInclusao")
	private String dataInclusao = null;
	@SerializedName("combo")
	private Boolean combo = null;
	@SerializedName("especialInclusoTeimosinha")
	private Boolean especialInclusoTeimosinha = null;
	@SerializedName("indicadorCotaBolao")
	private Boolean indicadorCotaBolao = false;
	@SerializedName("reservaCotaBolao")
	private CotaDTO reservaCotaBolao = null;

	@ApiModelProperty(value = "Gerar aposta espelho")
	public Boolean getGerarApostaEspelho() {
		return geraEspelho;
	}

	public void setGerarEspelho(Boolean geraEspelho) {
		this.geraEspelho = geraEspelho;
	}

	public List<Integer> getListaNumerosSelecionados() {
		if (numerosSelecionados != null) {
			return AppUtils.converteListaInteiros((List<Integer>) numerosSelecionados);
		} else {
			return null;
		}
	}

	public ArrayList<ArrayList<Integer>> getMatrizNumerosSelecionados() {
		return AppUtils.converteMatrizInteiros((List<List<Integer>>) numerosSelecionados);
	}

	public int getCountMatrizNumerosSelecionados() {
		int                           count  = 0;
		ArrayList<ArrayList<Integer>> matriz = getMatrizNumerosSelecionados();
		if (matriz != null) {
			for (ArrayList<Integer> coluna : matriz) {
				for (Integer linha : coluna) {
					count++;
				}
			}
		}
		return count;
	}

	/**
	 * Identificador da Aposta
	 **/
	@ApiModelProperty(value = "Identificador da Aposta")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Modalidade relacionada com a aposta
	 **/
	@ApiModelProperty(required = true, value = "Modalidade relacionada com a aposta")
	public ModalidadeEnum getModalidade() {
		return modalidade;
	}

	public void setModalidade(ModalidadeEnum modalidade) {
		this.modalidade = modalidade;
	}

	/**
	 *
	 **/
	@ApiModelProperty(required = true, value = "")
	public DTOEnumCharacter getTipoConcurso() {
		return tipoConcurso;
	}

	public void setTipoConcurso(DTOEnumCharacter tipoConcurso) {
		this.tipoConcurso = tipoConcurso;
	}

	/**
	 * Resultado das partidas de futebol relacionadas com a aposta, quando essa for relacionada com a modalidade Lotogol
	 **/
	@ApiModelProperty(value = "Resultado das partidas de futebol relacionadas com a aposta, quando essa for relacionada com a modalidade Lotogol")
	public List<PartidaLotogolDTO> getPartidasLotogol() {
		return partidasLotogol;
	}

	public void setPartidasLotogol(List<PartidaLotogolDTO> partidasLotogol) {
		this.partidasLotogol = partidasLotogol;
	}

	/**
	 * Resultado das partidas de futebol, informada pelo apostador, quando a aposta estiver relacionada com a modalidade Loteca
	 **/
	@ApiModelProperty(value = "Resultado das partidas de futebol, informada pelo apostador, quando a aposta estiver relacionada com a modalidade Loteca")
	public List<PartidaLotecaDTO> getPartidasLoteca() {
		return partidasLoteca;
	}

	public void setPartidasLoteca(List<PartidaLotecaDTO> partidasLoteca) {
		this.partidasLoteca = partidasLoteca;
	}

	/**
	 * Prognósticos relacionados com a aposta, no caso de aposta NÃO EFETIVADA e SURPRESINHA, esse campo pode ser informado vazio
	 **/
	@ApiModelProperty(value = "Prognósticos relacionados com a aposta, no caso de aposta NÃO EFETIVADA e SURPRESINHA, esse campo pode ser informado vazio")
	public T getNumerosSelecionados() {
		return numerosSelecionados;
	}

	public void setNumerosSelecionados(T numerosSelecionados) {
		this.numerosSelecionados = numerosSelecionados;
	}

	/**
	 *
	 **/
	@ApiModelProperty(required = true, value = "")
	public DTOEnumInteger getIndicadorSurpresinha() {
		return indicadorSurpresinha;
	}

	public void setIndicadorSurpresinha(DTOEnumInteger indicadorSurpresinha) {
		this.indicadorSurpresinha = indicadorSurpresinha;
	}

	/**
	 * Valor da Aposta
	 **/
	@ApiModelProperty(required = true, value = "Valor da Aposta")
	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	/**
	 * Número do concurso que estava disponível no momento da inclusão da aposta no carrinho
	 **/
	@ApiModelProperty(required = true, value = "Número do concurso que estava disponível no momento da inclusão da aposta no carrinho")
	public Integer getConcursoAlvo() {
		return concursoAlvo;
	}

	public void setConcursoAlvo(Integer concursoAlvo) {
		this.concursoAlvo = concursoAlvo;
	}

	/**
	 * Quantidade de Teimosinhas relacionadas com a aposta
	 **/
	@ApiModelProperty(value = "Quantidade de Teimosinhas relacionadas com a aposta")
	public Integer getQuantidadeTeimosinhas() {
		return quantidadeTeimosinhas;
	}

	public void setQuantidadeTeimosinhas(Integer quantidadeTeimosinhas) {
		this.quantidadeTeimosinhas = quantidadeTeimosinhas;
	}

	/**
	 * Quantidade de apostas jogadas, utilizado apenas para a modalidade Lotogol
	 **/
	@ApiModelProperty(value = "Quantidade de apostas jogadas, utilizado apenas para a modalidade Lotogol")
	public Integer getQuantidadeApostas() {
		return quantidadeApostas;
	}

	public void setQuantidadeApostas(Integer quantidadeApostas) {
		this.quantidadeApostas = quantidadeApostas;
	}

	/**
	 *
	 **/
	@ApiModelProperty(value = "")
	public Boolean getEspelho() {
		return espelho;
	}

	public void setEspelho(Boolean espelho) {
		this.espelho = espelho;
	}

	/**
	 *
	 **/
	@ApiModelProperty(value = "")
	public ParametroEquipe getTimeDoCoracao() {
		return timeDoCoracao;
	}

	public void setTimeDoCoracao(ParametroEquipe timeDoCoracao) {
		this.timeDoCoracao = timeDoCoracao;
	}

	/**
	 * Quando a aposta tiver sido efetivada, o concurso inicial será informado com o número do concurso em que a aposta foi registrada
	 **/
	@ApiModelProperty(value = "Quando a aposta tiver sido efetivada, o concurso inicial será informado com o número do concurso em que a aposta foi registrada")
	public Integer getConcursoInicial() {
		return concursoInicial;
	}

	public void setConcursoInicial(Integer concursoInicial) {
		this.concursoInicial = concursoInicial;
	}

	/**
	 *
	 **/
	@ApiModelProperty(value = "")
	public DTOEnumLong getSituacao() {
		return situacao;
	}

	public void setSituacao(DTOEnumLong situacao) {
		this.situacao = situacao;
	}

	/**
	 * Identificação se existe recibo de troca relacionado a aposta
	 **/
	@ApiModelProperty(value = "Identificação se existe recibo de troca relacionado a aposta")
	public Boolean getTroca() {
		return troca;
	}

	public void setTroca(Boolean troca) {
		this.troca = troca;
	}

	/**
	 * Data de Efetivação da Aposta
	 **/
	@ApiModelProperty(value = "Data de Efetivação da Aposta")
	public String getDataEfetivacao() {
		return dataEfetivacao;
	}

	public void setDataEfetivacao(String dataEfetivacao) {
		this.dataEfetivacao = dataEfetivacao;
	}

	/**
	 * Horário emque foi efetivada a aposta
	 **/
	@ApiModelProperty(value = "Horário em que foi efetivada a aposta")
	public String getHoraEfetivacao() {
		return horaEfetivacao;
	}

	public void setHoraEfetivacao(String horaEfetivacao) {
		this.horaEfetivacao = horaEfetivacao;
	}

	public String getDataSorteio() {
		return dataSorteio;
	}

	public void setDataSorteio(String dataSorteio) {
		this.dataSorteio = dataSorteio;
	}

	public String getDataCompra() {
		return dataCompra;
	}

	public void setDataCompra(String dataCompra) {
		this.dataCompra = dataCompra;
	}

	public String getHoraCompra() {
		return horaCompra;
	}

	public void setHoraCompra(String horaCompra) {
		this.horaCompra = horaCompra;
	}

	public String getSubcanalPagamento() {
		return subcanalPagamento;
	}

	public void setSubcanalPagamento(String subcanalPagamento) {
		this.subcanalPagamento = subcanalPagamento;
	}

/**

	 @ApiModelProperty(value = "")
	 public LotericaDTO getLoterica() {
	 return loterica;
	 }

	 public void setLoterica(LotericaDTO loterica) {
	 this.loterica = loterica;
	 }
	 **/
	/**
	 * Indica se a aposta possuí uma aposta espelho, válido apenas para a modalidade Lotomania
	 **/
	@ApiModelProperty(value = "Indica se a aposta possuí uma aposta espelho, válido apenas para a modalidade Lotomania")
	public Long getVinculoEspelho() {
		return vinculoEspelho;
	}

	public void setVinculoEspelho(Long vinculoEspelho) {
		this.vinculoEspelho = vinculoEspelho;
	}

	/**
	 * Quantidade de Números de prognósticos da aposta
	 **/
	@ApiModelProperty(value = "Quantidade de Números de prognósticos da aposta")
	public Integer getQuantidadeNumeros() {
		if (quantidadeNumeros != null && quantidadeNumeros != 0) {
			return quantidadeNumeros;
		} else {
			if (modalidade != null) {
				if (modalidade == ModalidadeEnum.SUPER_7) {
					if (getMatrizNumerosSelecionados() != null) {
						return getCountMatrizNumerosSelecionados();
					}
				} else {
					if (getListaNumerosSelecionados() != null) {
						return getListaNumerosSelecionados().size();
					}
				}
			}
			return -1;
		}
	}

	public void setQuantidadeNumeros(Integer quantidadeNumeros) {
		this.quantidadeNumeros = quantidadeNumeros;
	}

	public Integer getQuantidadeSurpresinhas() {
		return quantidadeSurpresinhas;
	}

	public void setQuantidadeSurpresinhas(Integer quantidadeSurpresinhas) {
		this.quantidadeSurpresinhas = quantidadeSurpresinhas;
	}

	/**
	 *
	 **/
	@ApiModelProperty(value = "")
	public Boolean getSurpresinha() {
		return surpresinha;
	}

	public void setSurpresinha(Boolean surpresinha) {
		this.surpresinha = surpresinha;
	}

	public Long getIdDB() {
		return idDB;
	}

	public void setIdDB(Long idDB) {
		this.idDB = idDB;
	}

	public ParametroMesDeSorte getMesDeSorte() {
		return mesDeSorte;
	}

	public void setMesDeSorte(ParametroMesDeSorte mesDeSorte) {
		this.mesDeSorte = mesDeSorte;
	}

	public List<Integer> getTrevosSelecionados() {
		return trevosSelecionados;
	}

	public void setTrevosSelecionados(List<Integer> trevosSelecionados) {
		this.trevosSelecionados = trevosSelecionados;
	}

	public Integer getQuantidadeTrevos() {
		return quantidadeTrevos;
	}

	public void setQuantidadeTrevos(Integer quantidadeTrevos) {
		this.quantidadeTrevos = quantidadeTrevos;
	}

	public String getDataInclusao() {
		return dataInclusao;
	}

	public void setDataInclusao(String dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	public Boolean getCombo() {
		return combo;
	}

	public void setCombo(Boolean combo) {
		this.combo = combo;
	}

	public Boolean getEspecialInclusoTeimosinha() {
		return especialInclusoTeimosinha;
	}

	public void setEspecialInclusoTeimosinha(Boolean especialInclusoTeimosinha) {
		this.especialInclusoTeimosinha = especialInclusoTeimosinha;
	}

	public Boolean getIndicadorCotaBolao() {
		return indicadorCotaBolao;
	}

	public void setIndicadorCotaBolao(Boolean indicadorCotaBolao) {
		this.indicadorCotaBolao = indicadorCotaBolao;
	}

	public CotaDTO getReservaCotaBolao() {
		return reservaCotaBolao;
	}

	public void setReservaCotaBolao(CotaDTO reservaCotaBolao) {
		this.reservaCotaBolao = reservaCotaBolao;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		IdentificaoDeUmaApostaDas8Modalidades<?> that = (IdentificaoDeUmaApostaDas8Modalidades<?>) o;
		boolean numerosIguais = false, equals;
		if(getModalidade().equals(ModalidadeEnum.SUPER_7) && that.getModalidade().equals(ModalidadeEnum.SUPER_7)){
			List<List<Integer>> matriz = new ArrayList<>();
			List<List<Integer>> thatMatriz = new ArrayList<>();
			matriz.addAll(getMatrizNumerosSelecionados());
			thatMatriz.addAll(that.getMatrizNumerosSelecionados());
			if (matriz!= null && thatMatriz != null){
				matriz = Utils.ordenaMatrizInteiro(matriz);
				thatMatriz = Utils.ordenaMatrizInteiro(thatMatriz);
				numerosIguais = Objects.equals(matriz, thatMatriz);
			}
		} else {
			if(!getModalidade().equals(ModalidadeEnum.SUPER_7) && !that.getModalidade().equals(ModalidadeEnum.SUPER_7)){
				if(!getModalidade().equals(ModalidadeEnum.LOTECA)) {
					List<Integer> nums = getListaNumerosSelecionados(),
							thatNums = that.getListaNumerosSelecionados();
					if(nums != null && thatNums!= null) {
						Collections.sort(nums);
						Collections.sort(thatNums);
						numerosIguais = Objects.equals(nums, thatNums);
					}
				} else {
					numerosIguais = true;
				}
			}
		}
		equals = getModalidade() == that.getModalidade() &&
				Objects.equals(getTipoConcurso().getValor(), that.getTipoConcurso().getValor()) &&
				Objects.equals(getPartidasLotogol(), that.getPartidasLotogol()) &&
				Objects.equals(getPartidasLoteca(), that.getPartidasLoteca()) &&
				numerosIguais &&
				Objects.equals(getQuantidadeNumeros(), that.getQuantidadeNumeros());

		if (getModalidade().equals(ModalidadeEnum.TIMEMANIA) && that.getModalidade().equals(ModalidadeEnum.TIMEMANIA)){
			return equals && Objects.equals(getTimeDoCoracao(), that.getTimeDoCoracao());
		}

		if (getModalidade().equals(ModalidadeEnum.DIA_DE_SORTE) && that.getModalidade().equals(ModalidadeEnum.DIA_DE_SORTE)) {
			return equals && Objects.equals(getMesDeSorte(), that.getMesDeSorte());
		}

		if (getModalidade().equals(ModalidadeEnum.LOTECA) && that.getModalidade().equals(ModalidadeEnum.LOTECA)) {
			return equals && Objects.equals(getPartidasLoteca(), that.getPartidasLoteca());
		}
		return equals;

	}

	@Override
	public int hashCode() {
		return Objects.hash(getModalidade(), getTipoConcurso(), getPartidasLotogol(), getPartidasLoteca(), getNumerosSelecionados(), getValor(), getConcursoAlvo(), getTimeDoCoracao(), getConcursoInicial(), getQuantidadeNumeros(), getMesDeSorte());
	}

	@Override
	public String toString() {

		String sb = "class IdentificaoDeUmaApostaDas8Modalidades {\n" +
				"  id: " + id + "\n" +
				"  modalidade: " + modalidade + "\n" +
				"  tipoConcurso: " + tipoConcurso + "\n" +
				"  partidasLotogol: " + partidasLotogol + "\n" +
				"  partidasLoteca: " + partidasLoteca + "\n" +
				"  numerosSelecionados: " + numerosSelecionados + "\n" +
				"  indicadorSurpresinha: " + indicadorSurpresinha + "\n" +
				"  valor: " + valor + "\n" +
				"  concursoAlvo: " + concursoAlvo + "\n" +
				"  quantidadeTeimosinhas: " + quantidadeTeimosinhas + "\n" +
				"  quantidadeApostas: " + quantidadeApostas + "\n" +
				"  espelho: " + espelho + "\n" +
				"  geraEspelho: " + geraEspelho + "\n" +
				"  timeDoCoracao: " + timeDoCoracao + "\n" +
				"  concursoInicial: " + concursoInicial + "\n" +
				"  situacao: " + situacao + "\n" +
				"  troca: " + troca + "\n" +
				"  dataEfetivacao: " + dataEfetivacao + "\n" +
				"  horaEfetivacao: " + horaEfetivacao + "\n" +
				"  dataSorteio: " + dataSorteio + "\n" +
				"  dataCompra: " + dataCompra + "\n" +
				"  horaCompra: " + horaCompra + "\n" +
				"  subcanalPagamento: " + subcanalPagamento + "\n" +
				//"  loterica: " + loterica + "\n" +
				"  vinculoEspelho: " + vinculoEspelho + "\n" +
				"  quantidadeNumeros: " + quantidadeNumeros + "\n" +
				"  surpresinha: " + surpresinha + "\n" +
				"}\n";
		return sb;
	}

	public final static IdentificaoDeUmaApostaDas8Modalidades clone(IdentificaoDeUmaApostaDas8Modalidades aposta) {
		IdentificaoDeUmaApostaDas8Modalidades identificaoDeUmaApostaDas8Modalidades = new IdentificaoDeUmaApostaDas8Modalidades();
		identificaoDeUmaApostaDas8Modalidades.setModalidade(aposta.getModalidade());
		identificaoDeUmaApostaDas8Modalidades.setConcursoAlvo(aposta.getConcursoAlvo());
		identificaoDeUmaApostaDas8Modalidades.setConcursoInicial(aposta.getConcursoInicial());
		identificaoDeUmaApostaDas8Modalidades.setDataEfetivacao(aposta.getDataEfetivacao());
		identificaoDeUmaApostaDas8Modalidades.setDataSorteio(aposta.getDataSorteio());
		identificaoDeUmaApostaDas8Modalidades.setEspelho(aposta.getEspelho());
		identificaoDeUmaApostaDas8Modalidades.setGerarEspelho(aposta.getGerarApostaEspelho());
		identificaoDeUmaApostaDas8Modalidades.setHoraEfetivacao(aposta.getHoraEfetivacao());
		identificaoDeUmaApostaDas8Modalidades.setDataCompra(aposta.getDataCompra());
		identificaoDeUmaApostaDas8Modalidades.setHoraCompra(aposta.getHoraCompra());
		identificaoDeUmaApostaDas8Modalidades.setSubcanalPagamento(aposta.getSubcanalPagamento());
		identificaoDeUmaApostaDas8Modalidades.setId(aposta.getId());
		//identificaoDeUmaApostaDas8Modalidades.setLoterica( aposta.getLoterica() );
		identificaoDeUmaApostaDas8Modalidades.setTipoConcurso(aposta.getTipoConcurso());
		identificaoDeUmaApostaDas8Modalidades.setPartidasLotogol(aposta.getPartidasLotogol());
		identificaoDeUmaApostaDas8Modalidades.setPartidasLoteca(aposta.getPartidasLoteca());
		identificaoDeUmaApostaDas8Modalidades.setNumerosSelecionados(aposta.getNumerosSelecionados());
		identificaoDeUmaApostaDas8Modalidades.setIndicadorSurpresinha(aposta.getIndicadorSurpresinha());
		identificaoDeUmaApostaDas8Modalidades.setValor(aposta.getValor());
		identificaoDeUmaApostaDas8Modalidades.setQuantidadeTeimosinhas(aposta.getQuantidadeTeimosinhas());
		identificaoDeUmaApostaDas8Modalidades.setQuantidadeApostas(aposta.getQuantidadeApostas());
		identificaoDeUmaApostaDas8Modalidades.setTimeDoCoracao(aposta.getTimeDoCoracao());
		identificaoDeUmaApostaDas8Modalidades.setSituacao(aposta.getSituacao());
		identificaoDeUmaApostaDas8Modalidades.setTroca(aposta.getTroca());
		identificaoDeUmaApostaDas8Modalidades.setQuantidadeNumeros(aposta.getQuantidadeNumeros());
		identificaoDeUmaApostaDas8Modalidades.setMesDeSorte(aposta.getMesDeSorte());
		return identificaoDeUmaApostaDas8Modalidades;
	}

	public static Boolean checkExisteUmaApostaIgualCarrinho(final IdentificaoDeUmaApostaDas8Modalidades identificaoDeUmaApostaDas8Modalidades, final CarrinhoDTO carrinhoDTO) {
		if (identificaoDeUmaApostaDas8Modalidades.getModalidade() == ModalidadeEnum.LOTECA ||
				identificaoDeUmaApostaDas8Modalidades.getModalidade() == ModalidadeEnum.LOTOGOL) {
			return false;
		}


		for (IdentificaoDeUmaApostaDas8Modalidades item : carrinhoDTO.getApostas()) {
			if (item.getModalidade() != ModalidadeEnum.SUPER_7) {
				if (item.getModalidade() == identificaoDeUmaApostaDas8Modalidades.getModalidade()) {
					List<Integer> numerosItem = item.getListaNumerosSelecionados();
					Collections.sort(numerosItem);
					List<Integer> numerosSelecionados = identificaoDeUmaApostaDas8Modalidades.getListaNumerosSelecionados();
					Collections.sort(numerosSelecionados);
					if (numerosSelecionados.equals(numerosItem)) {
						return true;
					}
				}
			} else {
				if (item.getModalidade() == identificaoDeUmaApostaDas8Modalidades.getModalidade()) {
					List<List<Integer>> matrizSelecionados = identificaoDeUmaApostaDas8Modalidades.getMatrizNumerosSelecionados();
					List<List<Integer>> matrizItem         = item.getMatrizNumerosSelecionados();
					matrizSelecionados = Utils.ordenaMatrizInteiro(matrizSelecionados);
					matrizItem = Utils.ordenaMatrizInteiro(matrizItem);
					if (matrizSelecionados.equals(matrizItem)) {
						return true;
					}
				}
			}
		}
		return false;
	}

	public static Boolean checkExisteUmaApostaIgualCarrinho(final ApostaFavoritaDTO apostaFavoritaDTO, final CarrinhoDTO carrinhoDTO) {
		if (ModalidadeEnum.fromInteger(apostaFavoritaDTO.getModalidade().getValor()) == ModalidadeEnum.LOTECA ||
				ModalidadeEnum.fromInteger(apostaFavoritaDTO.getModalidade().getValor()) == ModalidadeEnum.LOTOGOL) {
			return false;
		}
		for (IdentificaoDeUmaApostaDas8Modalidades item : carrinhoDTO.getApostas()) {
			if (item.getModalidade() != ModalidadeEnum.SUPER_7 && item.getModalidade() != ModalidadeEnum.MAIS_MILIONARIA) {
				if (item.getModalidade().equals(ModalidadeEnum.fromInteger(apostaFavoritaDTO.getModalidade().getValor()))) {
					List<Integer> numerosSelecionados = apostaFavoritaDTO.getListaNumerosSelecionados();
					Collections.sort(numerosSelecionados);
					List<Integer> numerosItem = item.getListaNumerosSelecionados();
					Collections.sort(numerosItem);

					if (numerosSelecionados.equals(numerosItem)) {
						return true;
					}
				}
			} else if (item.getModalidade().equals(ModalidadeEnum.MAIS_MILIONARIA)){
				if (item.getModalidade().equals(ModalidadeEnum.fromInteger(apostaFavoritaDTO.getModalidade().getValor()))) {
					List<Integer> numerosSelecionados = apostaFavoritaDTO.getListaNumerosSelecionados();
					Collections.sort(numerosSelecionados);
					List<Integer> numerosItem = item.getListaNumerosSelecionados();
					Collections.sort(numerosItem);

					if (numerosSelecionados.equals(numerosItem)) {
						List<Integer> trevosSelecionados = apostaFavoritaDTO.getParametroTrevo().getTrevosSelecionados();
						Collections.sort(trevosSelecionados);
						List<Integer> trevosItem = item.getTrevosSelecionados();
						Collections.sort(trevosItem);
						if (trevosSelecionados.equals(trevosItem)) {
							return true;
						}
					}
				}
			} else {
				if (item.getModalidade().equals(apostaFavoritaDTO.getModalidade())) {
					List<List<Integer>> matrizSelecionados = apostaFavoritaDTO.getMatrizNumerosSelecionados();
					List<List<Integer>> matrizItem         = item.getMatrizNumerosSelecionados();
					matrizSelecionados = Utils.ordenaMatrizInteiro(matrizSelecionados);
					matrizSelecionados = Utils.ordenaMatrizInteiro(matrizSelecionados);

					if (matrizSelecionados.equals(matrizItem)) {
						return true;
					}
				}
			}
		}
		return false;
	}

	public static BigDecimal getValorApostaFavoritaPorProagnostico(ApostaFavoritaDTO apostaFavoritaDTO) {
		if (apostaFavoritaDTO == null || apostaFavoritaDTO.getModalidade() == null)
			return BigDecimal.ZERO;

		ModalidadeEnum           modalidadeEnum         = ModalidadeEnum.fromInteger(apostaFavoritaDTO.getModalidade().getValor());

		SessaoUsuario sessao = SessaoUsuario.getInstance();
		if(sessao == null || sessao.getParametrosSimulacao() == null)
			return BigDecimal.ZERO;

		List<ParametroSimulacao> parametroSimulacaoList = sessao.getParametrosSimulacao().getParametros();
		if(parametroSimulacaoList == null){
			return BigDecimal.ZERO;
		}

		for (ParametroSimulacao parametroSimulacao : parametroSimulacaoList) {
			if (parametroSimulacao == null) continue;
			if (parametroSimulacao.getParametroJogo() == null) continue;
			if (parametroSimulacao.getParametroJogo().getConcurso() == null) continue;
			if (parametroSimulacao.getParametroJogo().getConcurso().getModalidade() == null) continue;

			if (parametroSimulacao.getParametroJogo().getConcurso().getModalidade() == modalidadeEnum) {
				if (modalidadeEnum == ModalidadeEnum.LOTECA) {
					return parametroSimulacao.getParametroJogo().getValorApostaMinima();
				} else if (modalidadeEnum == ModalidadeEnum.LOTOGOL) {
					return parametroSimulacao.getParametroJogo().getValorApostaMinima();
				} else {
					List<ParametroValorApostaDTO> parametroValorApostaDTOList = parametroSimulacao.getParametroJogo().getValoresAposta();
					if(parametroValorApostaDTOList == null){
						return BigDecimal.valueOf(-1);
					}
					for (ParametroValorApostaDTO parametroValorApostaDTO : parametroValorApostaDTOList) {
						if (apostaFavoritaDTO.getModalidade().getValor() != 7) {
							if (parametroValorApostaDTO.getNumeroPrognosticos() == apostaFavoritaDTO.getListaNumerosSelecionados().size()) {
								return parametroValorApostaDTO.getValor();
							}
						} else {
							if (parametroValorApostaDTO.getNumeroPrognosticos() == apostaFavoritaDTO.getCountMatrizNumerosSelecionados()) {
								return parametroValorApostaDTO.getValor();
							}
						}
					}
				}
			}
		}
		return BigDecimal.ZERO;
	}

	public static BigDecimal getValorApostaPorPrognostico(IdentificaoDeUmaApostaDas8Modalidades<List<Integer>> identificaoDeUmaApostaDas8Modalidades) {
		List<ParametroSimulacao> parametroSimulacaoList = SessaoUsuario.getInstance().getParametrosSimulacao().getParametros();
		for (ParametroSimulacao parametroSimulacao : parametroSimulacaoList) {
			if (parametroSimulacao.getParametroJogo().getConcurso().getModalidade() == identificaoDeUmaApostaDas8Modalidades.getModalidade()) {
				if (identificaoDeUmaApostaDas8Modalidades.getModalidade() == ModalidadeEnum.LOTECA) {
					return parametroSimulacao.getParametroJogo().getValorApostaMinima();
				} else if (identificaoDeUmaApostaDas8Modalidades.getModalidade() == ModalidadeEnum.LOTOGOL) {
					return parametroSimulacao.getParametroJogo().getValoresAposta().get(0).getValor();
				} else {
					List<ParametroValorApostaDTO> parametroValorApostaDTOList = parametroSimulacao.getParametroJogo().getValoresAposta();
					for (ParametroValorApostaDTO parametroValorApostaDTO : parametroValorApostaDTOList) {
						if (parametroValorApostaDTO.getNumeroPrognosticos() == identificaoDeUmaApostaDas8Modalidades.getNumerosSelecionados().size()) {
							return parametroValorApostaDTO.getValor();
						}
					}
				}
			}
		}
		return new BigDecimal("0");
	}
}
