/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * IncluirComboDTO
 */
public class IncluirComboDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("qtdApostas")
  private Integer qtdApostas = null;

  @SerializedName("isSurpresinha")
  private Boolean isSurpresinha = null;

  @SerializedName("limparCarrinho")
  private Boolean limparCarrinho = null;

  public IncluirComboDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public IncluirComboDTO qtdApostas(Integer qtdApostas) {
    this.qtdApostas = qtdApostas;
    return this;
  }

   /**
   * Get qtdApostas
   * @return qtdApostas
  **/
  @ApiModelProperty(value = "")
  public Integer getQtdApostas() {
    return qtdApostas;
  }

  public void setQtdApostas(Integer qtdApostas) {
    this.qtdApostas = qtdApostas;
  }

  public IncluirComboDTO isSurpresinha(Boolean isSurpresinha) {
    this.isSurpresinha = isSurpresinha;
    return this;
  }

   /**
   * Get isSurpresinha
   * @return isSurpresinha
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsSurpresinha() {
    return isSurpresinha;
  }

  public void setIsSurpresinha(Boolean isSurpresinha) {
    this.isSurpresinha = isSurpresinha;
  }

  public IncluirComboDTO limparCarrinho(Boolean limparCarrinho) {
    this.limparCarrinho = limparCarrinho;
    return this;
  }

   /**
   * Get limparCarrinho
   * @return limparCarrinho
  **/
  @ApiModelProperty(value = "")
  public Boolean isLimparCarrinho() {
    return limparCarrinho;
  }

  public void setLimparCarrinho(Boolean limparCarrinho) {
    this.limparCarrinho = limparCarrinho;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IncluirComboDTO incluirComboDTO = (IncluirComboDTO) o;
    return Objects.equals(this.id, incluirComboDTO.id) &&
        Objects.equals(this.qtdApostas, incluirComboDTO.qtdApostas) &&
        Objects.equals(this.isSurpresinha, incluirComboDTO.isSurpresinha) &&
        Objects.equals(this.limparCarrinho, incluirComboDTO.limparCarrinho);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, qtdApostas, isSurpresinha, limparCarrinho);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IncluirComboDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    qtdApostas: ").append(toIndentedString(qtdApostas)).append("\n");
    sb.append("    isSurpresinha: ").append(toIndentedString(isSurpresinha)).append("\n");
    sb.append("    limparCarrinho: ").append(toIndentedString(limparCarrinho)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

