/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class IncluirSurpresinhaDTO {
    @SerializedName("modalidade")
    private ModalidadeEnum modalidade = null;
    @SerializedName("tipoConcurso")
    private DTOEnumCharacter tipoConcurso = null;
    @SerializedName("indicadorSurpresinha")
    private DTOEnumInteger indicadorSurpresinha = null;
    @SerializedName("surpresinha")
    private Boolean surpresinha = null;
    @SerializedName("concursoAlvo")
    private Integer concursoAlvo = null;
    @SerializedName("quantidadeNumeros")
    private Integer quantidadeNumeros = null;
    @SerializedName("quantidadeTeimosinhas")
    private Integer quantidadeTeimosinhas = null;
    @SerializedName("quantidadeSurpresinhas")
    private Integer quantidadeSurpresinhas = null;
    @SerializedName("quantidadeNumerosMaisMilionariaTrevo")
    private Integer qtdTrevos = null;
    @SerializedName("gerarEspelho")
    private Boolean gerarEspelho = null;
    @SerializedName("quantidadeApostas")
    private Integer quantidadeApostas = null;
    @SerializedName("timeDoCoracao")
    private ParametroEquipe timeDoCoracao = null;
    @Expose(serialize = false, deserialize = false)
    protected transient BigDecimal valor = null;
    @Expose(serialize = false, deserialize = false)
    protected transient List<ParametroEquipe> listaTimeDoCoracao = null;


    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public ModalidadeEnum getModalidade() {
        return modalidade;
    }

    public void setModalidade(ModalidadeEnum modalidade) {
        this.modalidade = modalidade;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public DTOEnumCharacter getTipoConcurso() {
        return tipoConcurso;
    }

    public void setTipoConcurso(DTOEnumCharacter tipoConcurso) {
        this.tipoConcurso = tipoConcurso;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public DTOEnumInteger getIndicadorSurpresinha() {
        return indicadorSurpresinha;
    }

    public void setIndicadorSurpresinha(DTOEnumInteger indicadorSurpresinha) {
        this.indicadorSurpresinha = indicadorSurpresinha;
    }

    public Boolean getSurpresinha() {
        return surpresinha;
    }

    public void setSurpresinha(Boolean surpresinha) {
        this.surpresinha = surpresinha;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public Integer getConcursoAlvo() {
        return concursoAlvo;
    }

    public void setConcursoAlvo(Integer concursoAlvo) {
        this.concursoAlvo = concursoAlvo;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public Integer getQuantidadeNumeros() {
        return quantidadeNumeros;
    }

    public void setQuantidadeNumeros(Integer quantidadeNumeros) {
        this.quantidadeNumeros = quantidadeNumeros;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public Integer getQuantidadeTeimosinhas() {
        return quantidadeTeimosinhas;
    }

    public void setQuantidadeTeimosinhas(Integer quantidadeTeimosinhas) {
        this.quantidadeTeimosinhas = quantidadeTeimosinhas;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public Integer getQuantidadeSurpresinhas() {
        return quantidadeSurpresinhas;
    }

    public void setQuantidadeSurpresinhas(Integer quantidadeSurpresinhas) {
        this.quantidadeSurpresinhas = quantidadeSurpresinhas;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getGerarEspelho() {
        return gerarEspelho;
    }

    public void setGerarEspelho(Boolean gerarEspelho) {
        this.gerarEspelho = gerarEspelho;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getQuantidadeApostas() {
        return quantidadeApostas;
    }

    public void setQuantidadeApostas(Integer quantidadeApostas) {
        this.quantidadeApostas = quantidadeApostas;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ParametroEquipe getTimeDoCoracao() {
        return timeDoCoracao;
    }

    public void setTimeDoCoracao(ParametroEquipe timeDoCoracao) {
        this.timeDoCoracao = timeDoCoracao;
    }

    public BigDecimal getValor() {
        return valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public List<ParametroEquipe> getListaTimeDoCoracao() {
        return listaTimeDoCoracao;
    }

    public void setListaTimeDoCoracao(List<ParametroEquipe> listaTimeDoCoracao) {
        this.listaTimeDoCoracao = listaTimeDoCoracao;
    }

    public void setQtdTrevos(int qtdTrevos) {
        this.qtdTrevos = qtdTrevos;
    }

    public int getQtdTrevos(){
        return qtdTrevos;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IncluirSurpresinhaDTO incluirSurpresinhaDTO = (IncluirSurpresinhaDTO) o;
        return (this.modalidade == null ? incluirSurpresinhaDTO.modalidade == null : this.modalidade.equals(incluirSurpresinhaDTO.modalidade)) &&
                (this.tipoConcurso == null ? incluirSurpresinhaDTO.tipoConcurso == null : this.tipoConcurso.equals(incluirSurpresinhaDTO.tipoConcurso)) &&
                (this.indicadorSurpresinha == null ? incluirSurpresinhaDTO.indicadorSurpresinha == null : this.indicadorSurpresinha.equals(incluirSurpresinhaDTO.indicadorSurpresinha)) &&
                (this.concursoAlvo == null ? incluirSurpresinhaDTO.concursoAlvo == null : this.concursoAlvo.equals(incluirSurpresinhaDTO.concursoAlvo)) &&
                (this.quantidadeNumeros == null ? incluirSurpresinhaDTO.quantidadeNumeros == null : this.quantidadeNumeros.equals(incluirSurpresinhaDTO.quantidadeNumeros)) &&
                (this.quantidadeTeimosinhas == null ? incluirSurpresinhaDTO.quantidadeTeimosinhas == null : this.quantidadeTeimosinhas.equals(incluirSurpresinhaDTO.quantidadeTeimosinhas)) &&
                (this.quantidadeSurpresinhas == null ? incluirSurpresinhaDTO.quantidadeSurpresinhas == null : this.quantidadeSurpresinhas.equals(incluirSurpresinhaDTO.quantidadeSurpresinhas)) &&
                (this.gerarEspelho == null ? incluirSurpresinhaDTO.gerarEspelho == null : this.gerarEspelho.equals(incluirSurpresinhaDTO.gerarEspelho)) &&
                (this.quantidadeApostas == null ? incluirSurpresinhaDTO.quantidadeApostas == null : this.quantidadeApostas.equals(incluirSurpresinhaDTO.quantidadeApostas)) &&
                (this.timeDoCoracao == null ? incluirSurpresinhaDTO.timeDoCoracao == null : this.timeDoCoracao.equals(incluirSurpresinhaDTO.timeDoCoracao));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.modalidade == null ? 0 : this.modalidade.hashCode());
        result = 31 * result + (this.tipoConcurso == null ? 0 : this.tipoConcurso.hashCode());
        result = 31 * result + (this.indicadorSurpresinha == null ? 0 : this.indicadorSurpresinha.hashCode());
        result = 31 * result + (this.concursoAlvo == null ? 0 : this.concursoAlvo.hashCode());
        result = 31 * result + (this.quantidadeNumeros == null ? 0 : this.quantidadeNumeros.hashCode());
        result = 31 * result + (this.quantidadeTeimosinhas == null ? 0 : this.quantidadeTeimosinhas.hashCode());
        result = 31 * result + (this.quantidadeSurpresinhas == null ? 0 : this.quantidadeSurpresinhas.hashCode());
        result = 31 * result + (this.gerarEspelho == null ? 0 : this.gerarEspelho.hashCode());
        result = 31 * result + (this.quantidadeApostas == null ? 0 : this.quantidadeApostas.hashCode());
        result = 31 * result + (this.timeDoCoracao == null ? 0 : this.timeDoCoracao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class IncluirSurpresinhaDTO {\n" +
                "  modalidade: " + modalidade + "\n" +
                "  tipoConcurso: " + tipoConcurso + "\n" +
                "  indicadorSurpresinha: " + indicadorSurpresinha + "\n" +
                "  concursoAlvo: " + concursoAlvo + "\n" +
                "  quantidadeNumeros: " + quantidadeNumeros + "\n" +
                "  quantidadeTeimosinhas: " + quantidadeTeimosinhas + "\n" +
                "  quantidadeSurpresinhas: " + quantidadeSurpresinhas + "\n" +
                "  gerarEspelho: " + gerarEspelho + "\n" +
                "  quantidadeApostas: " + quantidadeApostas + "\n" +
                "  timeDoCoracao: " + timeDoCoracao + "\n" +
                "}\n";
        return sb;
    }
}
