/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Map;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class InformacaoPagamentoDTO {

    @SerializedName("meioPagamento")
    private Long meioPagamento = null;
    @SerializedName("parametrosPagamento")
    private Map<String, String> parametrosPagamento = null;
    @SerializedName("chavePix")
    private String chavePix;

    /**
     * Identificação do meio de pagamento selecionado para o pagamento da compra ou resgate do prêmio
     **/
    @ApiModelProperty(required = true, value = "Identificação do meio de pagamento selecionado para o pagamento da compra ou resgate do prêmio")
    public Long getMeioPagamento() {
        return meioPagamento;
    }

    public void setMeioPagamento(Long meioPagamento) {
        this.meioPagamento = meioPagamento;
    }

    /**
     * Lista dos possíveis meios de pagamento para o pagamento da compra ou resgate do prêmio
     **/
    @ApiModelProperty(value = "Lista dos possíveis meios de pagamento para o pagamento da compra ou resgate do prêmio")
    public Map<String, String> getParametrosPagamento() {
        return parametrosPagamento;
    }

    public void setParametrosPagamento(Map<String, String> parametrosPagamento) {
        this.parametrosPagamento = parametrosPagamento;
    }

    public String getChavePix() {
        return chavePix;
    }

    public void setChavePix(String chavePix) {
        this.chavePix = chavePix;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InformacaoPagamentoDTO informacaoPagamentoDTO = (InformacaoPagamentoDTO) o;
        return (this.meioPagamento == null ? informacaoPagamentoDTO.meioPagamento == null : this.meioPagamento.equals(informacaoPagamentoDTO.meioPagamento)) &&
                (this.parametrosPagamento == null ? informacaoPagamentoDTO.parametrosPagamento == null : this.parametrosPagamento.equals(informacaoPagamentoDTO.parametrosPagamento));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.meioPagamento == null ? 0 : this.meioPagamento.hashCode());
        result = 31 * result + (this.parametrosPagamento == null ? 0 : this.parametrosPagamento.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class InformacaoPagamentoDTO {\n" +
                "  meioPagamento: " + meioPagamento + "\n" +
                "  parametrosPagamento: " + parametrosPagamento + "\n" +
                "}\n";
        return sb;
    }
}
