/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import java.util.List;
/**
 * ListCarrinhoFavoritoResponse
 */
public class ListCarrinhoFavoritoResponse extends SilceResponse<List<CarrinhoFavoritoDTO>> { }

