/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

public class LotericaComposition {

    private boolean isFavorite = false;
    private LotericaDTO lotericaDTO;

    public LotericaComposition(LotericaDTO lotericaDTO) {
        this.lotericaDTO = lotericaDTO;
    }

    public LotericaDTO getLotericaDTO() {
        return lotericaDTO;
    }

    public boolean isFavorite() {
        return isFavorite;
    }

    public void setFavorite(boolean favorite) {
        isFavorite = favorite;
    }
}
