/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class MeioPagamentoDTO {

    @SerializedName("id")
    private Long id = null;
    @SerializedName("nomePagamentoCompra")
    private String nomePagamentoCompra = null;
    @SerializedName("nomePagamentoPremio")
    private String nomePagamentoPremio = null;
    @SerializedName("padrao")
    private Boolean padrao;
    @SerializedName("publicKey")
    private String publicKey = null;

    /**
     * Identificação do meio de pagamento
     **/
    @ApiModelProperty(value = "Identificação do meio de pagamento")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Nome do meio de Pagamento disponíveis para Realização de Compras de Aposta
     **/
    @ApiModelProperty(value = "Nome do meio de Pagamento disponíveis para Realização de Compras de Aposta")
    public String getNomePagamentoCompra() {
        return nomePagamentoCompra;
    }

    public void setNomePagamentoCompra(String nomePagamentoCompra) {
        this.nomePagamentoCompra = nomePagamentoCompra;
    }

    /**
     * Nome do meio de pagamento disponíveis para a realização do resgate de um prêmio
     **/
    @ApiModelProperty(value = "Nome do meio de pagamento disponíveis para a realização do resgate de um prêmio")
    public String getNomePagamentoPremio() {
        return nomePagamentoPremio;
    }

    public void setNomePagamentoPremio(String nomePagamentoPremio) {
        this.nomePagamentoPremio = nomePagamentoPremio;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public Boolean getPadrao() {
        return padrao;
    }

    public void setPadrao(Boolean padrao) {
        this.padrao = padrao;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MeioPagamentoDTO meioPagamentoDTO = (MeioPagamentoDTO) o;
        return (this.id == null ? meioPagamentoDTO.id == null : this.id.equals(meioPagamentoDTO.id)) &&
                (this.nomePagamentoCompra == null ? meioPagamentoDTO.nomePagamentoCompra == null : this.nomePagamentoCompra.equals(meioPagamentoDTO.nomePagamentoCompra)) &&
                (this.nomePagamentoPremio == null ? meioPagamentoDTO.nomePagamentoPremio == null : this.nomePagamentoPremio.equals(meioPagamentoDTO.nomePagamentoPremio)) &&
                (this.padrao == null ? meioPagamentoDTO.padrao == null : this.padrao.equals(meioPagamentoDTO.padrao)) &&
                (this.publicKey == null ? meioPagamentoDTO.publicKey == null : this.publicKey.equals(meioPagamentoDTO.publicKey));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.nomePagamentoCompra == null ? 0 : this.nomePagamentoCompra.hashCode());
        result = 31 * result + (this.nomePagamentoPremio == null ? 0 : this.nomePagamentoPremio.hashCode());
        result = 31 * result + (this.publicKey == null ? 0 : this.publicKey.hashCode());
        result = 31 * result + (this.padrao == null ? 0 : this.padrao.hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "MeioPagamentoDTO{" +
                "id=" + id +
                ", nomePagamentoCompra='" + nomePagamentoCompra + '\'' +
                ", nomePagamentoPremio='" + nomePagamentoPremio + '\'' +
                ", padrao=" + padrao +
                ", publicKey='" + publicKey + '\'' +
                '}';
    }
}
