/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import android.os.Parcel;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ModalidadeDTO implements Serializable {

    @SerializedName("valor")
    protected Integer valor = null;
    @SerializedName("descricao")
    protected String descricao = null;
    @SerializedName("descricaoEspecial")
    protected String descricaoEspecial = null;
    @SerializedName("descricaoGestor")
    protected String descricaoGestor = null;

    public ModalidadeDTO() {
        valor = null;
        descricao = null;
        descricaoEspecial = null;
    }


    protected ModalidadeDTO(Parcel in) {
        if (in.readByte() == 0) {
            valor = null;
        } else {
            valor = in.readInt();
        }
        descricao = in.readString();
        descricaoEspecial = in.readString();
    }

    /**
     * Identificação da modalidade
     **/
    @ApiModelProperty(value = "Identificação da modalidade")
    public Integer getValor() {
        return valor;
    }

    public void setValor(Integer valor) {
        this.valor = valor;
    }

    /**
     * Descrição da modalidade
     **/
    @ApiModelProperty(value = "Descrição da modalidade")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    /**
     * Descrição da modalidade, quando houver concurso especial.
     **/
    @ApiModelProperty(value = "Descrição da modalidade, quando houver concurso especial.")
    public String getDescricaoEspecial() {
        return descricaoEspecial;
    }

    public void setDescricaoEspecial(String descricaoEspecial) {
        this.descricaoEspecial = descricaoEspecial;
    }

    /**
     * Descrição da modalidade, quando houver concurso especial.
     **/
    @ApiModelProperty(value = "Descrição da modalidade, quando houver concurso especial.")
    public String getDescricaoGestor() {
        return descricaoGestor;
    }

    public void setDescricaoGestor(String descricaoGestor) {
        this.descricaoGestor = descricaoGestor;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModalidadeDTO modalidadeDTO = (ModalidadeDTO) o;
        return (this.valor == null ? modalidadeDTO.valor == null : this.valor.equals(modalidadeDTO.valor)) &&
                (this.descricao == null ? modalidadeDTO.descricao == null : this.descricao.equals(modalidadeDTO.descricao)) &&
                (this.descricaoEspecial == null ? modalidadeDTO.descricaoEspecial == null : this.descricaoEspecial.equals(modalidadeDTO.descricaoEspecial) &&
                (this.descricaoGestor == null ? modalidadeDTO.descricaoGestor == null : this.descricaoGestor.equals(modalidadeDTO.descricaoGestor)));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.valor == null ? 0 : this.valor.hashCode());
        result = 31 * result + (this.descricao == null ? 0 : this.descricao.hashCode());
        result = 31 * result + (this.descricaoEspecial == null ? 0 : this.descricaoEspecial.hashCode());
        result = 31 * result + (this.descricaoGestor == null ? 0 : this.descricaoGestor.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ModalidadeDTO {\n" +
                "  valor: " + valor + "\n" +
                "  descricao: " + descricao + "\n" +
                "  descricaoEspecial: " + descricaoEspecial + "\n" +
                "  descricaoGestor: " + descricaoGestor + "\n" +
                "}\n";
        return sb;
    }
}
