/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;
import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * NotificacaoDTO
 */
public class NotificacaoCentralDTO {
  @SerializedName("titulo")
  private String titulo = null;

  @SerializedName("conteudo")
  private String conteudo = null;

//  @SerializedName("imagem")
//  private String imagem = null; //NAO utilizada nesse momento

  @SerializedName("dataVisualizacao")
  //private Data dataVisualizacao = null;
  private DataNotificacao dataVisualizacao = null;

  @SerializedName("id")
  private Long id = null;

  public NotificacaoCentralDTO titulo(String titulo) {
    this.titulo = titulo;
    return this;
  }

  public NotificacaoCentralDTO(Long id, String titulo, String conteudo, DataNotificacao dataVisualizacao) {
    this.id = id;
    this.titulo = titulo;
    this.conteudo = conteudo;
    this.dataVisualizacao = dataVisualizacao;
  }

  public NotificacaoCentralDTO(Long id, String titulo, String conteudo) {
    this.id = id;
    this.titulo = titulo;
    this.conteudo = conteudo;
  }
  /**
   * Get titulo
   * @return titulo
  **/
  @ApiModelProperty(value = "")
  public String getTitulo() {
    return titulo;
  }

  public void setTitulo(String titulo) {
    this.titulo = titulo;
  }

  @ApiModelProperty(value = "")
  public String getConteudo() {
    return conteudo;
  }

  public void setConteudo(String conteudo) {
    this.conteudo = conteudo;
  }

  @ApiModelProperty(value = "")
  public DataNotificacao getDataVisualizacao() {
    return dataVisualizacao;
  }

  public void setDataVisualizacao(DataNotificacao dataVisualizacao) {
    this.dataVisualizacao = dataVisualizacao;
  }

  public boolean isLida() {
    return dataVisualizacao != null;
  }
  public NotificacaoCentralDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificacaoCentralDTO notificacaoDTO = (NotificacaoCentralDTO) o;
    return Objects.equals(this.titulo, notificacaoDTO.titulo) &&
        Objects.equals(this.conteudo, notificacaoDTO.conteudo) &&
        Objects.equals(this.dataVisualizacao, notificacaoDTO.dataVisualizacao) &&
        Objects.equals(this.id, notificacaoDTO.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(titulo, conteudo, dataVisualizacao, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificacaoDTO {\n");
    
    sb.append("    titulo: ").append(toIndentedString(titulo)).append("\n");
    sb.append("    conteudo: ").append(toIndentedString(conteudo)).append("\n");
    sb.append("    dataVisualizacao: ").append(toIndentedString(dataVisualizacao)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

