/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class NovaSenhaDTO {

    @SerializedName("senhaAtual")
    private String senhaAtual = null;
    @SerializedName("novaSenha")
    private String novaSenha = null;

    /**
     * Senha atual do apostador
     **/
    @ApiModelProperty(value = "Senha atual do apostador")
    public String getSenhaAtual() {
        return senhaAtual;
    }

    public void setSenhaAtual(String senhaAtual) {
        this.senhaAtual = senhaAtual;
    }

    /**
     * Nova senha do apostador
     **/
    @ApiModelProperty(value = "Nova senha do apostador")
    public String getNovaSenha() {
        return novaSenha;
    }

    public void setNovaSenha(String novaSenha) {
        this.novaSenha = novaSenha;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NovaSenhaDTO novaSenhaDTO = (NovaSenhaDTO) o;
        return (this.senhaAtual == null ? novaSenhaDTO.senhaAtual == null : this.senhaAtual.equals(novaSenhaDTO.senhaAtual)) &&
                (this.novaSenha == null ? novaSenhaDTO.novaSenha == null : this.novaSenha.equals(novaSenhaDTO.novaSenha));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.senhaAtual == null ? 0 : this.senhaAtual.hashCode());
        result = 31 * result + (this.novaSenha == null ? 0 : this.novaSenha.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class NovaSenhaDTO {\n" +
                "  senhaAtual: " + senhaAtual + "\n" +
                "  novaSenha: " + novaSenha + "\n" +
                "}\n";
        return sb;
    }
}
