/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ParametroMesDeSorte implements Serializable {
  
  @SerializedName("numero")
  protected Integer numero = null;
  @SerializedName("nome")
  protected String nome = null;
  @SerializedName("abreviacao")
  protected String abreviacao = null;
  @Expose(serialize = false, deserialize = false)
  protected boolean isSelecionado;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getNumero() {
    return numero;
  }
  public void setNumero(Integer numero) {
    this.numero = numero;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }
  public void setNome(String nome) {
    this.nome = nome;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAbreviacao() {
    return abreviacao;
  }
  public void setAbreviacao(String abreviacao) {
    this.abreviacao = abreviacao;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParametroMesDeSorte parametroMesDeSorte = (ParametroMesDeSorte) o;
    return (this.numero == null ? parametroMesDeSorte.numero == null : this.numero.equals(parametroMesDeSorte.numero)) &&
        (this.nome == null ? parametroMesDeSorte.nome == null : this.nome.equals(parametroMesDeSorte.nome)) &&
        (this.abreviacao == null ? parametroMesDeSorte.abreviacao == null : this.abreviacao.equals(parametroMesDeSorte.abreviacao));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.numero == null ? 0: this.numero.hashCode());
    result = 31 * result + (this.nome == null ? 0: this.nome.hashCode());
    result = 31 * result + (this.abreviacao == null ? 0: this.abreviacao.hashCode());
    return result;
  }

  @Override
  public String toString()  {

      String sb = "class ParametroMesDeSorte {\n" +
              "  numero: " + numero + "\n" +
              "  nome: " + nome + "\n" +
              "  abreviacao: " + abreviacao + "\n" +
              "}\n";
      return sb;
  }

  public boolean isSelecionado() {
    return isSelecionado;
  }

  public void setSelecionado(boolean selecionado) {
    isSelecionado = selecionado;
  }
}
