/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ParametroPartida implements Serializable {

    @SerializedName("numero")
    protected Integer numero = null;
    @SerializedName("equipe1")
    protected ParametroEquipe equipe1 = null;
    @SerializedName("equipe2")
    protected ParametroEquipe equipe2 = null;
    @SerializedName("descricaoLegenda")
    protected String descricaoLegenda = null;
    @SerializedName("letraLegenda")
    protected String letraLegenda = null;

    @Expose(serialize = false, deserialize = false)
    protected transient boolean selecionado;
    @Expose(serialize = false, deserialize = false)
    protected transient boolean empate;
    @Expose(serialize = false, deserialize = false)
    protected transient int qtdItensSelecionados;
    @Expose(serialize = false, deserialize = false)
    protected transient int qtdItensSelecionadosAnterior;

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ParametroEquipe getEquipe1() {
        return equipe1;
    }

    public void setEquipe1(ParametroEquipe equipe1) {
        this.equipe1 = equipe1;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ParametroEquipe getEquipe2() {
        return equipe2;
    }

    public void setEquipe2(ParametroEquipe equipe2) {
        this.equipe2 = equipe2;
    }

    @ApiModelProperty(value = "")
    public String getDescricaoLegenda() {
        return descricaoLegenda;
    }

    public void setDescricaoLegenda(String descricaoLegenda) {
        this.descricaoLegenda = descricaoLegenda;
    }

    @ApiModelProperty(value = "")
    public String getLetraLegenda() {
        return letraLegenda;
    }

    public void setLetraLegenda(String letraLegenda) {
        this.letraLegenda = letraLegenda;
    }

    public String getLegendaAbreviada() {
        if (descricaoLegenda != null && descricaoLegenda.length() > 4)
            return " (" + descricaoLegenda.substring(4) + ")";
        else
            return "";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ParametroPartida parametroPartida = (ParametroPartida) o;
        return (this.numero == null ? parametroPartida.numero == null : this.numero.equals(parametroPartida.numero)) &&
                (this.equipe1 == null ? parametroPartida.equipe1 == null : this.equipe1.equals(parametroPartida.equipe1)) &&
                (this.equipe2 == null ? parametroPartida.equipe2 == null : this.equipe2.equals(parametroPartida.equipe2));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.equipe1 == null ? 0 : this.equipe1.hashCode());
        result = 31 * result + (this.equipe2 == null ? 0 : this.equipe2.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ParametroPartida {\n" +
                "  numero: " + numero + "\n" +
                "  equipe1: " + equipe1 + "\n" +
                "  equipe2: " + equipe2 + "\n" +
                "}\n";
        return sb;
    }

    public boolean isSelecionado() {
        return selecionado;
    }

    public void setSelecionado(boolean selecionado) {
        this.selecionado = selecionado;
    }

    public boolean isEmpate() {
        return empate;
    }

    public void setEmpate(boolean empate) {
        this.empate = empate;
    }

    public int getQtdItensSelecionados() {
        return qtdItensSelecionados;
    }

    public void setQtdItensSelecionados(int qtdItensSelecionados) {
        this.qtdItensSelecionados = qtdItensSelecionados;
    }

    public int getQtdItensSelecionadosAnterior() {
        return qtdItensSelecionadosAnterior;
    }

    public void setQtdItensSelecionadosAnterior(int qtdItensSelecionadosAnterior) {
        this.qtdItensSelecionadosAnterior = qtdItensSelecionadosAnterior;
    }
}
