/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;
import com.google.gson.annotations.SerializedName;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Parametros
 */
public class Parametros {
  @SerializedName("mapa")
  private Map<String, Object> mapa = null;

  public Parametros mapa(Map<String, Object> mapa) {
    this.mapa = mapa;
    return this;
  }

  public Parametros putMapaItem(String key, Object mapaItem) {
    if (this.mapa == null) {
      this.mapa = new HashMap<String, Object>();
    }
    this.mapa.put(key, mapaItem);
    return this;
  }

   /**
   * Mapa de conversâo para JSON
   * @return mapa
  **/
  @ApiModelProperty(value = "Mapa de conversâo para JSON")
  public Map<String, Object> getMapa() {
    return mapa;
  }

  public void setMapa(Map<String, Object> mapa) {
    this.mapa = mapa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Parametros parametros = (Parametros) o;
    return Objects.equals(this.mapa, parametros.mapa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mapa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Parametros {\n");
    
    sb.append("    mapa: ").append(toIndentedString(mapa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

