/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ParametroTrevo<T> implements Serializable {
  
  @SerializedName("trevosSelecionados")
  protected List<Integer> trevosSelecionados = null;


  @ApiModelProperty(value = "")
  public List<Integer> getTrevosSelecionados() {
    return trevosSelecionados;
  }

  public void setTrevosSelecionados(List<Integer> trevosSelecionados) {
    this.trevosSelecionados = trevosSelecionados;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    ParametroTrevo<?> that = (ParametroTrevo<?>) o;
    return Objects.equals(trevosSelecionados, that.trevosSelecionados);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trevosSelecionados);
  }

  @Override
  public String toString() {
    return "ParametroTrevo{" +
            "trevosSelecionados=" + trevosSelecionados +
            '}';
  }
}
