/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import br.gov.caixa.loterias.apostas.R;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class PartidaLotecaDTO implements Serializable {
    @SerializedName("equipe1")
    protected EquipeDTO equipe1 = null;
    @SerializedName("equipe2")
    protected EquipeDTO equipe2 = null;
    @SerializedName("empate")
    protected Boolean empate = null;
    @SerializedName("numero")
    protected Integer numero = null;
    @Expose(serialize = false, deserialize = false)
    protected transient Long idDB;
    @SerializedName("descricaoLegenda")
    protected String descricaoLegenda = null;
    @SerializedName("letraLegenda")
    protected String letraLegenda = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public EquipeDTO getEquipe1() {
        return equipe1;
    }

    public void setEquipe1(EquipeDTO equipe1) {
        this.equipe1 = equipe1;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public EquipeDTO getEquipe2() {
        return equipe2;
    }

    public void setEquipe2(EquipeDTO equipe2) {
        this.equipe2 = equipe2;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getEmpate() {
        return empate;
    }

    public void setEmpate(Boolean empate) {
        this.empate = empate;
    }

    public Long getIdDB() {
        return idDB;
    }

    public void setIdDB(Long idDB) {
        this.idDB = idDB;
    }

    @ApiModelProperty(value = "")
    public String getDescricaoLegenda() {
        return descricaoLegenda;
    }

    public void setDescricaoLegenda(String descricaoLegenda) {
        this.descricaoLegenda = descricaoLegenda;
    }

    @ApiModelProperty(value = "")
    public String getLetraLegenda() {
        return letraLegenda;
    }

    public void setLetraLegenda(String letraLegenda) {
        this.letraLegenda = letraLegenda;
    }

    @ApiModelProperty(value = "")
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }


    public String getLegendaAbreviada() {
        if (descricaoLegenda != null && descricaoLegenda.length() > 4)
            return " (" + descricaoLegenda.substring(4) + ")";
        else
            return "";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartidaLotecaDTO partidaLotecaDTO = (PartidaLotecaDTO) o;
        return (this.equipe1 == null ? partidaLotecaDTO.equipe1 == null : this.equipe1.equals(partidaLotecaDTO.equipe1)) &&
                (this.equipe2 == null ? partidaLotecaDTO.equipe2 == null : this.equipe2.equals(partidaLotecaDTO.equipe2)) &&
                (this.empate == null ? partidaLotecaDTO.empate == null : this.empate.equals(partidaLotecaDTO.empate));
    }

    public boolean customEquals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartidaLotecaDTO partidaLotecaDTO = (PartidaLotecaDTO) o;
        return (this.equipe1 == null ? partidaLotecaDTO.equipe1 == null : this.equipe1.customEquals(partidaLotecaDTO.equipe1)) &&
                (this.equipe2 == null ? partidaLotecaDTO.equipe2 == null : this.equipe2.customEquals(partidaLotecaDTO.equipe2)) &&
                (this.numero == null ? partidaLotecaDTO.numero == null : this.numero.equals(partidaLotecaDTO.numero)) &&
                (this.empate == null ? partidaLotecaDTO.empate == null : this.empate.equals(partidaLotecaDTO.empate));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.equipe1 == null ? 0 : this.equipe1.hashCode());
        result = 31 * result + (this.equipe2 == null ? 0 : this.equipe2.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.empate == null ? 0 : this.empate.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class PartidaLotecaDTO {\n" +
                "  numero: " + numero + "\n" +
                "  equipe1: " + equipe1 + "\n" +
                "  equipe2: " + equipe2 + "\n" +
                "  empate: " + empate + "\n" +
                "}\n";
        return sb;
    }
}
