/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class PartidaLotogolDTO implements Serializable {

    @SerializedName("equipe1")
    protected EquipeDTO equipe1 = null;
    @SerializedName("equipe2")
    protected EquipeDTO equipe2 = null;
    @SerializedName("indexPlacarEquipe1")
    protected Integer indexPlacarEquipe1 = null;
    @SerializedName("indexPlacarEquipe2")
    protected Integer indexPlacarEquipe2 = null;
    @Expose(serialize = false, deserialize = false)
    protected transient Long idDB;

    /**
     **/
    @ApiModelProperty(value = "")
    public EquipeDTO getEquipe1() {
        return equipe1;
    }

    public void setEquipe1(EquipeDTO equipe1) {
        this.equipe1 = equipe1;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public EquipeDTO getEquipe2() {
        return equipe2;
    }

    public void setEquipe2(EquipeDTO equipe2) {
        this.equipe2 = equipe2;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getIndexPlacarEquipe1() {
        return indexPlacarEquipe1;
    }

    public void setIndexPlacarEquipe1(Integer indexPlacarEquipe1) {
        this.indexPlacarEquipe1 = indexPlacarEquipe1;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getIndexPlacarEquipe2() {
        return indexPlacarEquipe2;
    }

    public void setIndexPlacarEquipe2(Integer indexPlacarEquipe2) {
        this.indexPlacarEquipe2 = indexPlacarEquipe2;
    }

    public Long getIdDB() {
        return idDB;
    }

    public void setIdDB(Long idDB) {
        this.idDB = idDB;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartidaLotogolDTO partidaLotogolDTO = (PartidaLotogolDTO) o;
        return (this.equipe1 == null ? partidaLotogolDTO.equipe1 == null : this.equipe1.equals(partidaLotogolDTO.equipe1)) &&
                (this.equipe2 == null ? partidaLotogolDTO.equipe2 == null : this.equipe2.equals(partidaLotogolDTO.equipe2)) &&
                (this.indexPlacarEquipe1 == null ? partidaLotogolDTO.indexPlacarEquipe1 == null : this.indexPlacarEquipe1.equals(partidaLotogolDTO.indexPlacarEquipe1)) &&
                (this.indexPlacarEquipe2 == null ? partidaLotogolDTO.indexPlacarEquipe2 == null : this.indexPlacarEquipe2.equals(partidaLotogolDTO.indexPlacarEquipe2));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.equipe1 == null ? 0 : this.equipe1.hashCode());
        result = 31 * result + (this.equipe2 == null ? 0 : this.equipe2.hashCode());
        result = 31 * result + (this.indexPlacarEquipe1 == null ? 0 : this.indexPlacarEquipe1.hashCode());
        result = 31 * result + (this.indexPlacarEquipe2 == null ? 0 : this.indexPlacarEquipe2.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class PartidaLotogolDTO {\n" +
                "  equipe1: " + equipe1 + "\n" +
                "  equipe2: " + equipe2 + "\n" +
                "  indexPlacarEquipe1: " + indexPlacarEquipe1 + "\n" +
                "  indexPlacarEquipe2: " + indexPlacarEquipe2 + "\n" +
                "}\n";
        return sb;
    }
}
