/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;

/**
 * Esta entidade é utilizada para representar domínios, que tem apenas os atributos chave/valor
 **/
@ApiModel(description = "Esta entidade é utilizada para representar domínios, que tem apenas os atributos chave/valor")
public class PeriodoConsultaDTO implements Serializable {
    @SerializedName("mes")
    protected DTOEnumLong mes = null;
    @SerializedName("ano")
    protected Long ano = null;

    public DTOEnumLong getMes() {
        return mes;
    }

    public Long getAno() {
        return ano;
    }
}
