/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class PremioDTO implements Serializable {

    @SerializedName("id")
    protected Long id = null;
    @SerializedName("valorBruto")
    protected BigDecimal valorBruto = null;
    @SerializedName("valorLiquido")
    protected BigDecimal valorLiquido = null;
    @SerializedName("concursos")
    protected List<ConcursoPremiadoDTO> concursos = null;
    @SerializedName("dataPagamento")
    protected String dataPagamento = null;
    @SerializedName("horaPagamento")
    protected String horaPagamento = null;
    @SerializedName("localPagamento")
    protected String localPagamento = null;
    @SerializedName("nsuPagamento")
    protected Long nsuPagamento = null;

    @SerializedName("concursosNaoPremiado")
    protected List<ConcursoPremiadoDTO> concursosNaoPremiado;

    /**
     * Identificação do prêmio
     **/
    @ApiModelProperty(value = "Identificação do prêmio")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Valor bruto do prêmio
     **/
    @ApiModelProperty(value = "Valor bruto do prêmio")
    public BigDecimal getValorBruto() {
        return valorBruto;
    }

    public void setValorBruto(BigDecimal valorBruto) {
        this.valorBruto = valorBruto;
    }

    /**
     * Valor líquido do prêmio
     **/
    @ApiModelProperty(value = "Valor líquido do prêmio")
    public BigDecimal getValorLiquido() {
        return valorLiquido;
    }

    public void setValorLiquido(BigDecimal valorLiquido) {
        this.valorLiquido = valorLiquido;
    }

    /**
     * Identificação dos concursos premiados relacionados a aposta
     **/
    @ApiModelProperty(value = "Identificação dos concursos premiados relacionados a aposta")
    public List<ConcursoPremiadoDTO> getConcursos() {
        return concursos;
    }

    public void setConcursos(List<ConcursoPremiadoDTO> concursos) {
        this.concursos = concursos;
    }

    /**
     * Data do pagamento do prêmio
     **/
    @ApiModelProperty(value = "Data do pagamento do prêmio")
    public String getDataPagamento() {
        return dataPagamento;
    }

    public void setDataPagamento(String dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    /**
     * Hora do pagamento do prêmio
     **/
    @ApiModelProperty(value = "Hora do pagamento do prêmio")
    public String getHoraPagamento() {
        return horaPagamento;
    }

    public void setHoraPagamento(String horaPagamento) {
        this.horaPagamento = horaPagamento;
    }

    /**
     * Local onde ocorreu o pagamento do prêmio
     **/
    @ApiModelProperty(value = "Local onde ocorreu o pagamento do prêmio")
    public String getLocalPagamento() {
        return localPagamento;
    }

    public void setLocalPagamento(String localPagamento) {
        this.localPagamento = localPagamento;
    }

    /**
     * NSU do  pagamento
     **/
    @ApiModelProperty(value = "NSU do  pagamento")
    public Long getNsuPagamento() {
        return nsuPagamento;
    }

    public void setNsuPagamento(Long nsuPagamento) {
        this.nsuPagamento = nsuPagamento;
    }

    public List<ConcursoPremiadoDTO> getConcursosNaoPremiado() {
        return concursosNaoPremiado;
    }

    public void setConcursosNaoPremiado(List<ConcursoPremiadoDTO> concursosNaoPremiado) {
        this.concursosNaoPremiado = concursosNaoPremiado;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PremioDTO premioDTO = (PremioDTO) o;
        return (this.id == null ? premioDTO.id == null : this.id.equals(premioDTO.id)) &&
                (this.valorBruto == null ? premioDTO.valorBruto == null : this.valorBruto.equals(premioDTO.valorBruto)) &&
                (this.valorLiquido == null ? premioDTO.valorLiquido == null : this.valorLiquido.equals(premioDTO.valorLiquido)) &&
                (this.concursos == null ? premioDTO.concursos == null : this.concursos.equals(premioDTO.concursos)) &&
                (this.concursosNaoPremiado == null ? premioDTO.concursosNaoPremiado == null : this.concursosNaoPremiado.equals(premioDTO.concursosNaoPremiado)) &&
                (this.dataPagamento == null ? premioDTO.dataPagamento == null : this.dataPagamento.equals(premioDTO.dataPagamento)) &&
                (this.horaPagamento == null ? premioDTO.horaPagamento == null : this.horaPagamento.equals(premioDTO.horaPagamento)) &&
                (this.localPagamento == null ? premioDTO.localPagamento == null : this.localPagamento.equals(premioDTO.localPagamento)) &&
                (this.nsuPagamento == null ? premioDTO.nsuPagamento == null : this.nsuPagamento.equals(premioDTO.nsuPagamento));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.valorBruto == null ? 0 : this.valorBruto.hashCode());
        result = 31 * result + (this.valorLiquido == null ? 0 : this.valorLiquido.hashCode());
        result = 31 * result + (this.concursos == null ? 0 : this.concursos.hashCode());
        result = 31 * result + (this.concursosNaoPremiado == null ? 0 : this.concursosNaoPremiado.hashCode());
        result = 31 * result + (this.dataPagamento == null ? 0 : this.dataPagamento.hashCode());
        result = 31 * result + (this.horaPagamento == null ? 0 : this.horaPagamento.hashCode());
        result = 31 * result + (this.localPagamento == null ? 0 : this.localPagamento.hashCode());
        result = 31 * result + (this.nsuPagamento == null ? 0 : this.nsuPagamento.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class PremioDTO {\n" +
                "  id: " + id + "\n" +
                "  valorBruto: " + valorBruto + "\n" +
                "  valorLiquido: " + valorLiquido + "\n" +
                "  concursos: " + concursos + "\n" +
                "  concursos: " + concursosNaoPremiado + "\n" +
                "  dataPagamento: " + dataPagamento + "\n" +
                "  horaPagamento: " + horaPagamento + "\n" +
                "  localPagamento: " + localPagamento + "\n" +
                "  nsuPagamento: " + nsuPagamento + "\n" +
                "}\n";
        return sb;
    }
}
