/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class PremiacaoTimeDoCoracaoDTO implements Serializable {

    @SerializedName("quantidadeGanhadores")
    protected Long quantidadeGanhadores = null;
    @SerializedName("valor")
    protected BigDecimal valor = null;
    @SerializedName("equipe")
    protected ParametroEquipe equipe = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getQuantidadeGanhadores() {
        return quantidadeGanhadores;
    }

    public void setQuantidadeGanhadores(Long quantidadeGanhadores) {
        this.quantidadeGanhadores = quantidadeGanhadores;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public BigDecimal getValor() {
        return valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ParametroEquipe getEquipe() {
        return equipe;
    }

    public void setEquipe(ParametroEquipe equipe) {
        this.equipe = equipe;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PremiacaoTimeDoCoracaoDTO premiacaoTimeDoCoracaoDTO = (PremiacaoTimeDoCoracaoDTO) o;
        return (this.quantidadeGanhadores == null ? premiacaoTimeDoCoracaoDTO.quantidadeGanhadores == null : this.quantidadeGanhadores.equals(premiacaoTimeDoCoracaoDTO.quantidadeGanhadores)) &&
                (this.valor == null ? premiacaoTimeDoCoracaoDTO.valor == null : this.valor.equals(premiacaoTimeDoCoracaoDTO.valor)) &&
                (this.equipe == null ? premiacaoTimeDoCoracaoDTO.equipe == null : this.equipe.equals(premiacaoTimeDoCoracaoDTO.equipe));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.quantidadeGanhadores == null ? 0 : this.quantidadeGanhadores.hashCode());
        result = 31 * result + (this.valor == null ? 0 : this.valor.hashCode());
        result = 31 * result + (this.equipe == null ? 0 : this.equipe.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class PremiacaoTimeDoCoracaoDTO {\n" +
                "  quantidadeGanhadores: " + quantidadeGanhadores + "\n" +
                "  valor: " + valor + "\n" +
                "  equipe: " + equipe + "\n" +
                "}\n";
        return sb;
    }
}
