/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class PushRegistrarDispositivo implements Serializable {

    @SerializedName("codigo")
    protected String codigo = null;
    @SerializedName("mensagem")
    protected String mensagem = null;

    @ApiModelProperty(value = "Código do erro")
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @ApiModelProperty(value = "Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário")
    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PushRegistrarDispositivo silceResponse = (PushRegistrarDispositivo) o;
        return (this.codigo == null ? silceResponse.codigo == null : this.codigo.equals(silceResponse.codigo)) &&
                (this.mensagem == null ? silceResponse.mensagem == null : this.mensagem.equals(silceResponse.mensagem));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.codigo == null ? 0 : this.codigo.hashCode());
        result = 31 * result + (this.mensagem == null ? 0 : this.mensagem.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ComprovanteApostaDTOResponse {\n" +
                "  codigo: " + codigo + "\n" +
                "  mensagem: " + mensagem + "\n" +
                "}\n";
        return sb;
    }
}
