/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class    RapidaoDTO {

    @SerializedName("valorMinimo")
    @Expose(serialize = true, deserialize = true)
    private BigDecimal valorMinimo = null;
    @SerializedName("valorMaximo")
    @Expose(serialize = true, deserialize = true)
    private BigDecimal valorMaximo = null;
    @SerializedName("valorMinimoPremioPrincipal")
    @Expose(serialize = true, deserialize = true)
    private BigDecimal valorMinimoPremioPrincipal = null;
    @SerializedName("prognosticosObrigatorios")
    @Expose(serialize = true, deserialize = true)
    private List<Integer> prognosticosObrigatorios = null;
    @SerializedName("prognosticosProibidos")
    @Expose(serialize = true, deserialize = true)
    private List<Integer> prognosticosProibidos = null;
    @SerializedName("modalidades")
    @Expose(serialize = true, deserialize = true)
    private List<ModalidadeDTO> modalidades = null;
    @SerializedName("apostasFavoritas")
    @Expose(serialize = true, deserialize = true)
    private List<ApostaFavoritaDTO> apostasFavoritas = null;

    /**
     * Valor Mínimo de Apostas para Compor o rapidão
     **/
    @ApiModelProperty(value = "Valor Mínimo de Apostas para Compor o rapidão")
    public BigDecimal getValorMinimo() {
        return valorMinimo;
    }

    public void setValorMinimo(BigDecimal valorMinimo) {
        this.valorMinimo = valorMinimo;
    }

    /**
     * Valor Máximo das Apostas do rapidão
     **/
    @ApiModelProperty(value = "Valor Máximo das Apostas do rapidão")
    public BigDecimal getValorMaximo() {
        return valorMaximo;
    }

    public void setValorMaximo(BigDecimal valorMaximo) {
        this.valorMaximo = valorMaximo;
    }

    /**
     * Valor da estimativa de prêmio das apostas a serem compostas na geração do rapidão
     **/
    @ApiModelProperty(value = "Valor da estimativa de prêmio das apostas a serem compostas na geração do rapidão")
    public BigDecimal getValorMinimoPremioPrincipal() {
        return valorMinimoPremioPrincipal;
    }

    public void setValorMinimoPremioPrincipal(BigDecimal valorMinimoPremioPrincipal) {
        this.valorMinimoPremioPrincipal = valorMinimoPremioPrincipal;
    }

    /**
     * Lista de Prognósticos obrigatórios a serem gerados nas apostas do rapidão
     **/
    @ApiModelProperty(value = "Lista de Prognósticos obrigatórios a serem gerados nas apostas do rapidão")
    public List<Integer> getPrognosticosObrigatorios() {
        return prognosticosObrigatorios;
    }

    public void setPrognosticosObrigatorios(List<Integer> prognosticosObrigatorios) {
        this.prognosticosObrigatorios = prognosticosObrigatorios;
    }

    /**
     * Lista de Prognósticos que não podem estar nas apostas geradas para o rapidão
     **/
    @ApiModelProperty(value = "Lista de Prognósticos que não podem estar nas apostas geradas para o rapidão")
    public List<Integer> getPrognosticosProibidos() {
        return prognosticosProibidos;
    }

    public void setPrognosticosProibidos(List<Integer> prognosticosProibidos) {
        this.prognosticosProibidos = prognosticosProibidos;
    }

    /**
     * TipoModalidade a compor as apostas do rapidão
     **/
    @ApiModelProperty(value = "TipoModalidade a compor as apostas do rapidão")
    public List<ModalidadeDTO> getModalidades() {
        return modalidades;
    }

    public void setModalidades(List<ModalidadeDTO> modalidades) {
        this.modalidades = modalidades;
    }

    /**
     * Lista de apostas favoritas a compor o rapidão
     **/
    @ApiModelProperty(value = "Lista de apostas favoritas a compor o rapidão")
    public List<ApostaFavoritaDTO> getApostasFavoritas() {
        return apostasFavoritas;
    }

    public void setApostasFavoritas(List<ApostaFavoritaDTO> apostasFavoritas) {
        this.apostasFavoritas = apostasFavoritas;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RapidaoDTO rapidaoDTO = (RapidaoDTO) o;
        return (this.valorMinimo == null ? rapidaoDTO.valorMinimo == null : this.valorMinimo.equals(rapidaoDTO.valorMinimo)) &&
                (this.valorMaximo == null ? rapidaoDTO.valorMaximo == null : this.valorMaximo.equals(rapidaoDTO.valorMaximo)) &&
                (this.valorMinimoPremioPrincipal == null ? rapidaoDTO.valorMinimoPremioPrincipal == null : this.valorMinimoPremioPrincipal.equals(rapidaoDTO.valorMinimoPremioPrincipal)) &&
                (this.prognosticosObrigatorios == null ? rapidaoDTO.prognosticosObrigatorios == null : this.prognosticosObrigatorios.equals(rapidaoDTO.prognosticosObrigatorios)) &&
                (this.prognosticosProibidos == null ? rapidaoDTO.prognosticosProibidos == null : this.prognosticosProibidos.equals(rapidaoDTO.prognosticosProibidos)) &&
                (this.modalidades == null ? rapidaoDTO.modalidades == null : this.modalidades.equals(rapidaoDTO.modalidades)) &&
                (this.apostasFavoritas == null ? rapidaoDTO.apostasFavoritas == null : this.apostasFavoritas.equals(rapidaoDTO.apostasFavoritas));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.valorMinimo == null ? 0 : this.valorMinimo.hashCode());
        result = 31 * result + (this.valorMaximo == null ? 0 : this.valorMaximo.hashCode());
        result = 31 * result + (this.valorMinimoPremioPrincipal == null ? 0 : this.valorMinimoPremioPrincipal.hashCode());
        result = 31 * result + (this.prognosticosObrigatorios == null ? 0 : this.prognosticosObrigatorios.hashCode());
        result = 31 * result + (this.prognosticosProibidos == null ? 0 : this.prognosticosProibidos.hashCode());
        result = 31 * result + (this.modalidades == null ? 0 : this.modalidades.hashCode());
        result = 31 * result + (this.apostasFavoritas == null ? 0 : this.apostasFavoritas.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class RapidaoDTO {\n" +
                "  valorMinimo: " + valorMinimo + "\n" +
                "  valorMaximo: " + valorMaximo + "\n" +
                "  valorMinimoPremioPrincipal: " + valorMinimoPremioPrincipal + "\n" +
                "  prognosticosObrigatorios: " + prognosticosObrigatorios + "\n" +
                "  prognosticosProibidos: " + prognosticosProibidos + "\n" +
                "  modalidades: " + modalidades + "\n" +
                "  apostasFavoritas: " + apostasFavoritas + "\n" +
                "}\n";
        return sb;
    }
}
