/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class RepassometroDTO {

    @SerializedName("arrecadacaoAcumulada")
    private BigDecimal arrecadacaoAcumulada = null;
    @SerializedName("arrecadacaoUltimaSemana")
    private BigDecimal arrecadacaoUltimaSemana = null;
    @SerializedName("dataBase")
    private String dataBase = null;

    @SerializedName("percentualProgramasSociais")
    private BigDecimal percentualProgramasSociais = null;



    @SerializedName("percentualEducacao")
    private BigDecimal percentualEducacao = null;

    @SerializedName("percentualCultura")
    private BigDecimal percentualCultura = null;

    @SerializedName("percentualEsporte")
    private BigDecimal percentualEsporte = null;

    @SerializedName("percentualSeguranca")
    private BigDecimal percentualSeguranca = null;

    @SerializedName("percentualSeguridade")
    private BigDecimal percentualSeguridade = null;

    @SerializedName("percentualOutros")
    private BigDecimal percentualOutros = null;

    /*

     */

    /**
     * Valor da arrecadação. Este valor deve ser utilizado como base para o incremento do arrecadado no reparrômetro
     **/
    @ApiModelProperty(value = "Valor da arrecadação. Este valor deve ser utilizado como base para o incremento do arrecadado no reparrômetro")
    public BigDecimal getArrecadacaoAcumulada() {
        return arrecadacaoAcumulada;
    }

    public void setArrecadacaoAcumulada(BigDecimal arrecadacaoAcumulada) {
        this.arrecadacaoAcumulada = arrecadacaoAcumulada;
    }

    /**
     * Valor que foi arrecadado na semana anterior. Valor deve ser ser diluído no período de uma semana (604800 segundos) para criar o contador
     **/
    @ApiModelProperty(value = "Valor que foi arrecadado na semana anterior. Valor deve ser ser diluído no período de uma semana (604800 segundos) para criar o contador")
    public BigDecimal getArrecadacaoUltimaSemana() {
        return arrecadacaoUltimaSemana;
    }

    public void setArrecadacaoUltimaSemana(BigDecimal arrecadacaoUltimaSemana) {
        this.arrecadacaoUltimaSemana = arrecadacaoUltimaSemana;
    }

    /**
     * Data base para incremento do rapidão. dd/MM/yyyy
     **/
    @ApiModelProperty(value = "Data base para incremento do rapidão. dd/MM/yyyy")
    public String getDataBase() {
        return dataBase;
    }

    public void setDataBase(String dataBase) {
        this.dataBase = dataBase;
    }


    public BigDecimal getPercentualProgramasSociais() {
        return percentualProgramasSociais;
    }

    public void setPercentualProgramasSociais(BigDecimal percentualProgramasSociais) {
        this.percentualProgramasSociais = percentualProgramasSociais;
    }

    public BigDecimal getPercentualEducacao() {
        return percentualEducacao;
    }

    public void setPercentualEducacao(BigDecimal percentualEducacao) {
        this.percentualEducacao = percentualEducacao;
    }

    public BigDecimal getPercentualCultura() {
        return percentualCultura;
    }

    public void setPercentualCultura(BigDecimal percentualCultura) {
        this.percentualCultura = percentualCultura;
    }

    public BigDecimal getPercentualEsporte() {
        return percentualEsporte;
    }

    public void setPercentualEsporte(BigDecimal percentualEsporte) {
        this.percentualEsporte = percentualEsporte;
    }

    public BigDecimal getPercentualSeguranca() {
        return percentualSeguranca;
    }

    public void setPercentualSeguranca(BigDecimal percentualSeguranca) {
        this.percentualSeguranca = percentualSeguranca;
    }

    public BigDecimal getPercentualSeguridade() {
        return percentualSeguridade;
    }

    public void setPercentualSeguridade(BigDecimal percentualSeguridade) {
        this.percentualSeguridade = percentualSeguridade;
    }

    public BigDecimal getPercentualOutros() {
        return percentualOutros;
    }

    public void setPercentualOutros(BigDecimal percentualOutros) {
        this.percentualOutros = percentualOutros;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RepassometroDTO repassometroDTO = (RepassometroDTO) o;
        return (this.arrecadacaoAcumulada == null ? repassometroDTO.arrecadacaoAcumulada == null : this.arrecadacaoAcumulada.equals(repassometroDTO.arrecadacaoAcumulada)) &&
                (this.arrecadacaoUltimaSemana == null ? repassometroDTO.arrecadacaoUltimaSemana == null : this.arrecadacaoUltimaSemana.equals(repassometroDTO.arrecadacaoUltimaSemana)) &&
                (this.dataBase == null ? repassometroDTO.dataBase == null : this.dataBase.equals(repassometroDTO.dataBase)) &&
                (this.percentualProgramasSociais == null ? repassometroDTO.percentualProgramasSociais == null : this.percentualProgramasSociais.equals(repassometroDTO.percentualProgramasSociais)) &&
                (this.percentualCultura == null ? repassometroDTO.percentualCultura == null : this.percentualCultura.equals(repassometroDTO.percentualCultura)) &&
                (this.percentualEducacao == null ? repassometroDTO.percentualEducacao == null : this.percentualEducacao.equals(repassometroDTO.percentualEducacao)) &&
                (this.percentualEsporte == null ? repassometroDTO.percentualEsporte == null : this.percentualEsporte.equals(repassometroDTO.percentualEsporte)) &&
                (this.percentualOutros == null ? repassometroDTO.percentualOutros == null : this.percentualOutros.equals(repassometroDTO.percentualOutros)) &&
                (this.percentualSeguranca == null ? repassometroDTO.percentualSeguranca == null : this.percentualSeguranca.equals(repassometroDTO.percentualSeguranca)) &&
                (this.percentualSeguridade == null ? repassometroDTO.percentualSeguridade == null : this.percentualSeguridade.equals(repassometroDTO.percentualSeguridade));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.arrecadacaoAcumulada == null ? 0 : this.arrecadacaoAcumulada.hashCode());
        result = 31 * result + (this.arrecadacaoUltimaSemana == null ? 0 : this.arrecadacaoUltimaSemana.hashCode());
        result = 31 * result + (this.dataBase == null ? 0 : this.dataBase.hashCode());
        result = 31 * result + (this.percentualSeguridade == null ? 0 : this.percentualSeguridade.hashCode());
        result = 31 * result + (this.percentualSeguranca == null ? 0 : this.percentualSeguranca.hashCode());
        result = 31 * result + (this.percentualOutros == null ? 0 : this.percentualOutros.hashCode());
        result = 31 * result + (this.percentualEsporte == null ? 0 : this.percentualEsporte.hashCode());
        result = 31 * result + (this.percentualEducacao == null ? 0 : this.percentualEducacao.hashCode());
        result = 31 * result + (this.percentualCultura == null ? 0 : this.percentualCultura.hashCode());
        result = 31 * result + (this.percentualProgramasSociais == null ? 0 : this.percentualProgramasSociais.hashCode());
        return result;
    }

    @Override
    public String toString() {
        String sb = "class RepassometroDTO {\n" +
                "  arrecadacaoAcumulada: " + arrecadacaoAcumulada + "\n" +
                "  arrecadacaoUltimaSemana: " + arrecadacaoUltimaSemana + "\n" +
                "  dataBase: " + dataBase + "\n" +
                "  dataBase: " + percentualCultura + "\n" +
                "  dataBase: " + percentualEducacao + "\n" +
                "  dataBase: " + percentualEsporte + "\n" +
                "  dataBase: " + percentualOutros + "\n" +
                "  dataBase: " + percentualProgramasSociais + "\n" +
                "  dataBase: " + percentualSeguranca + "\n" +
                "  dataBase: " + percentualSeguridade + "\n" +
                "}\n";
        return sb;
    }
}
