/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ResultadoConsultaBilheteFederalDTO {

    @SerializedName("premio")
    private PremiacaoExtracaoDTO premio = null;
    @SerializedName("extracao")
    private ExtracaoDTO extracao = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public PremiacaoExtracaoDTO getPremio() {
        return premio;
    }

    public void setPremio(PremiacaoExtracaoDTO premio) {
        this.premio = premio;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ExtracaoDTO getExtracao() {
        return extracao;
    }

    public void setExtracao(ExtracaoDTO extracao) {
        this.extracao = extracao;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResultadoConsultaBilheteFederalDTO resultadoConsultaBilheteFederalDTO = (ResultadoConsultaBilheteFederalDTO) o;
        return (this.premio == null ? resultadoConsultaBilheteFederalDTO.premio == null : this.premio.equals(resultadoConsultaBilheteFederalDTO.premio)) &&
                (this.extracao == null ? resultadoConsultaBilheteFederalDTO.extracao == null : this.extracao.equals(resultadoConsultaBilheteFederalDTO.extracao));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.premio == null ? 0 : this.premio.hashCode());
        result = 31 * result + (this.extracao == null ? 0 : this.extracao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ResultadoConsultaBilheteFederalDTO {\n" +
                "  premio: " + premio + "\n" +
                "  extracao: " + extracao + "\n" +
                "}\n";
        return sb;
    }
}
