/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ResultadoPesquisaPaginadaDTOApostaFavoritaDTO {

    @SerializedName("rowCount")
    private Long rowCount = null;
    @SerializedName("lista")
    private List<ApostaFavoritaDTO> lista = null;
    @SerializedName("listaSize")
    private Integer listaSize = null;

    /**
     * Quantidade de colunas existentes para cada registro de retorno
     **/
    @ApiModelProperty(value = "Quantidade de colunas existentes para cada registro de retorno")
    public Long getRowCount() {
        return rowCount;
    }

    public void setRowCount(Long rowCount) {
        this.rowCount = rowCount;
    }

    /**
     * Criação da lista vazia
     **/
    @ApiModelProperty(value = "Criação da lista vazia")
    public List<ApostaFavoritaDTO> getLista() {
        return lista;
    }

    public void setLista(List<ApostaFavoritaDTO> lista) {
        this.lista = lista;
    }

    /**
     * Tamanho da lista
     **/
    @ApiModelProperty(value = "Tamanho da lista")
    public Integer getListaSize() {
        return listaSize;
    }

    public void setListaSize(Integer listaSize) {
        this.listaSize = listaSize;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResultadoPesquisaPaginadaDTOApostaFavoritaDTO resultadoPesquisaPaginadaDTOApostaFavoritaDTO = (ResultadoPesquisaPaginadaDTOApostaFavoritaDTO) o;
        return (this.rowCount == null ? resultadoPesquisaPaginadaDTOApostaFavoritaDTO.rowCount == null : this.rowCount.equals(resultadoPesquisaPaginadaDTOApostaFavoritaDTO.rowCount)) &&
                (this.lista == null ? resultadoPesquisaPaginadaDTOApostaFavoritaDTO.lista == null : this.lista.equals(resultadoPesquisaPaginadaDTOApostaFavoritaDTO.lista)) &&
                (this.listaSize == null ? resultadoPesquisaPaginadaDTOApostaFavoritaDTO.listaSize == null : this.listaSize.equals(resultadoPesquisaPaginadaDTOApostaFavoritaDTO.listaSize));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.rowCount == null ? 0 : this.rowCount.hashCode());
        result = 31 * result + (this.lista == null ? 0 : this.lista.hashCode());
        result = 31 * result + (this.listaSize == null ? 0 : this.listaSize.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ResultadoPesquisaPaginadaDTOApostaFavoritaDTO {\n" +
                "  rowCount: " + rowCount + "\n" +
                "  lista: " + lista + "\n" +
                "  listaSize: " + listaSize + "\n" +
                "}\n";
        return sb;
    }
}
