/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ResultadoConsultaBilheteNovoDTO {

    @SerializedName("situacao")
    private DTOEnumLong situacao = null;
    @SerializedName("locaisParaRecebimento")
    private List<TipoPagamentoDTO> locaisParaRecebimento = null;
    @SerializedName("premio")
    private PremioNovoDTO premio = null;
    @SerializedName("modalidade")
    private ModalidadeDTO modalidade = null;

    public DTOEnumLong getSituacao() {
        return situacao;
    }

    public void setSituacao(DTOEnumLong situacao) {
        this.situacao = situacao;
    }

    public List<TipoPagamentoDTO> getLocaisParaRecebimento() {
        return locaisParaRecebimento;
    }

    public void setLocaisParaRecebimento(List<TipoPagamentoDTO> locaisParaRecebimento) {
        this.locaisParaRecebimento = locaisParaRecebimento;
    }

    public PremioNovoDTO getPremio() {
        return premio;
    }

    public void setPremio(PremioNovoDTO premio) {
        this.premio = premio;
    }

    public ModalidadeDTO getModalidade() {
        return modalidade;
    }

    public void setModalidade(ModalidadeDTO modalidade) {
        this.modalidade = modalidade;
    }
}
