/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResultadoPesquisaPaginadaDTOApostaDTOResponse {
  
  @SerializedName("codigo")
  private String codigo = null;
  @SerializedName("mensagem")
  private String mensagem = null;

  @SerializedName("tipo")
  private TipoEnum tipo = null;

  @SerializedName("redirect")
  private RedirectEnum redirect = null;
  @SerializedName("errosValidacao")
  private List<ErroValidacao> errosValidacao = null;
  @SerializedName("versao")
  private String versao = null;
  @SerializedName("payload")
  private ResultadoPesquisaPaginadaDTOApostaDTO payload = null;

  /**
   * Código do erro
   **/
  @ApiModelProperty(value = "Código do erro")
  public String getCodigo() {
    return codigo;
  }
  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  /**
   * Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário
   **/
  @ApiModelProperty(value = "Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário")
  public String getMensagem() {
    return mensagem;
  }
  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  /**
   * Tipo da mensagem. 1=Mensagem de usuário, 2=Mensagem de sistema, 3= Erro de validação
   **/
  @ApiModelProperty(value = "Tipo da mensagem. 1=Mensagem de usuário, 2=Mensagem de sistema, 3= Erro de validação")
  public TipoEnum getTipo() {
    return tipo;
  }
  public void setTipo(TipoEnum tipo) {
    this.tipo = tipo;
  }

  /**
   * ID da tela que o usuário deve ser redirecionado
   **/
  @ApiModelProperty(value = "ID da tela que o usuário deve ser redirecionado")
  public RedirectEnum getRedirect() {
    return redirect;
  }
  public void setRedirect(RedirectEnum redirect) {
    this.redirect = redirect;
  }

  /**
   * Lista com os erros de validação
   **/
  @ApiModelProperty(value = "Lista com os erros de validação")
  public List<ErroValidacao> getErrosValidacao() {
    return errosValidacao;
  }
  public void setErrosValidacao(List<ErroValidacao> errosValidacao) {
    this.errosValidacao = errosValidacao;
  }

  /**
   * Versão do serviço
   **/
  @ApiModelProperty(value = "Versão do serviço")
  public String getVersao() {
    return versao;
  }
  public void setVersao(String versao) {
    this.versao = versao;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ResultadoPesquisaPaginadaDTOApostaDTO getPayload() {
    return payload;
  }
  public void setPayload(ResultadoPesquisaPaginadaDTOApostaDTO payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultadoPesquisaPaginadaDTOApostaDTOResponse resultadoPesquisaPaginadaDTOApostaDTOResponse = (ResultadoPesquisaPaginadaDTOApostaDTOResponse) o;
    return (this.codigo == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.codigo == null : this.codigo.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.codigo)) &&
        (this.mensagem == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.mensagem == null : this.mensagem.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.mensagem)) &&
        (this.tipo == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.tipo == null : this.tipo.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.tipo)) &&
        (this.redirect == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.redirect == null : this.redirect.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.redirect)) &&
        (this.errosValidacao == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.errosValidacao == null : this.errosValidacao.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.errosValidacao)) &&
        (this.versao == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.versao == null : this.versao.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.versao)) &&
        (this.payload == null ? resultadoPesquisaPaginadaDTOApostaDTOResponse.payload == null : this.payload.equals(resultadoPesquisaPaginadaDTOApostaDTOResponse.payload));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.codigo == null ? 0: this.codigo.hashCode());
    result = 31 * result + (this.mensagem == null ? 0: this.mensagem.hashCode());
    result = 31 * result + (this.tipo == null ? 0: this.tipo.hashCode());
    result = 31 * result + (this.redirect == null ? 0: this.redirect.hashCode());
    result = 31 * result + (this.errosValidacao == null ? 0: this.errosValidacao.hashCode());
    result = 31 * result + (this.versao == null ? 0: this.versao.hashCode());
    result = 31 * result + (this.payload == null ? 0: this.payload.hashCode());
    return result;
  }

  @Override
  public String toString()  {

      String sb = "class ResultadoPesquisaPaginadaDTOApostaDTOResponse {\n" +
              "  codigo: " + codigo + "\n" +
              "  mensagem: " + mensagem + "\n" +
              "  tipo: " + tipo + "\n" +
              "  redirect: " + redirect + "\n" +
              "  errosValidacao: " + errosValidacao + "\n" +
              "  versao: " + versao + "\n" +
              "  payload: " + payload + "\n" +
              "}\n";
      return sb;
  }
}
