/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import br.gov.caixa.loterias.apostas.utils.AppUtils;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ResultadoConcursoDTO<T> implements Serializable {

    @SerializedName("municipioSorteio")
    protected MunicipioDTO municipioSorteio = null;
    @SerializedName("ufSorteio")
    protected UnidadeFederacaoDTO ufSorteio = null;
    @SerializedName("aviso")
    protected String aviso = null;
    @SerializedName("arrecadacaoTotal")
    protected BigDecimal arrecadacaoTotal = null;
    @SerializedName("acumuladoParaProximoConcurso")
    protected BigDecimal acumuladoParaProximoConcurso = null;
    @SerializedName("acumulou")
    protected Boolean acumulou = null;
    @SerializedName("numerosSorteadosSegundoSorteio")
    protected List<Integer> numerosSorteadosSegundoSorteio = null;
    @SerializedName("partidasLotogol")
    protected List<PartidaLotogolDTO> partidasLotogol = null;
    @SerializedName("partidasLoteca")
    protected List<PartidaLotecaDTO> partidasLoteca = null;
    @SerializedName("concurso")
    protected ConcursoDTO concurso = null;
    @SerializedName("proximoConcurso")
    protected ConcursoDTO proximoConcurso = null;
    @SerializedName("proximoConcursoFinalZero")
    protected ConcursoDTO proximoConcursoFinalZero = null;
    @SerializedName("proximoConcursoFinalCinco")
    protected ConcursoDTO proximoConcursoFinalCinco = null;
    @SerializedName("proximoConcursoEspecial")
    protected ConcursoDTO proximoConcursoEspecial = null;
    @SerializedName("premiacoesPrimeiroSorteio")
    protected List<PremiacaoConcursoDTO> premiacoesPrimeiroSorteio = null;
    @SerializedName("premiacoesSegundoSorteio")
    protected List<PremiacaoConcursoDTO> premiacoesSegundoSorteio = null;
    @SerializedName("premiacaoTimeDoCoracao")
    protected PremiacaoTimeDoCoracaoDTO premiacaoTimeDoCoracao = null;
    @SerializedName("premiacaoMesDeSorte")
    protected PremiacaoMesDeSorteDTO premiacaoMesDeSorte = null;
    @SerializedName("ganhadoresPrimeiroSorteio")
    protected List<GanhadoresPorRegiaoDTO> ganhadoresPrimeiroSorteio = null;
    @SerializedName("ganhadoresSegundoSorteio")
    protected List<GanhadoresPorRegiaoDTO> ganhadoresSegundoSorteio = null;
    @SerializedName("numerosSorteadosPrimeiroSorteio")
    protected T numerosSorteadosPrimeiroSorteio = null;
    @SerializedName("trevosSorteadosPrimeiroSorteio")
    protected List<Integer> trevosSorteadosPrimeiroSorteio = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public MunicipioDTO getMunicipioSorteio() {
        return municipioSorteio;
    }

    public void setMunicipioSorteio(MunicipioDTO municipioSorteio) {
        this.municipioSorteio = municipioSorteio;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public UnidadeFederacaoDTO getUfSorteio() {
        return ufSorteio;
    }

    public void setUfSorteio(UnidadeFederacaoDTO ufSorteio) {
        this.ufSorteio = ufSorteio;
    }

    /**
     * Aviso relacionado ao concurso da modalidade
     **/
    @ApiModelProperty(value = "Aviso relacionado ao concurso da modalidade")
    public String getAviso() {
        return aviso;
    }

    public void setAviso(String aviso) {
        this.aviso = aviso;
    }

    /**
     * Arrecadação total do concurso
     **/
    @ApiModelProperty(value = "Arrecadação total do concurso")
    public BigDecimal getArrecadacaoTotal() {
        return arrecadacaoTotal;
    }

    public void setArrecadacaoTotal(BigDecimal arrecadacaoTotal) {
        this.arrecadacaoTotal = arrecadacaoTotal;
    }

    /**
     * Valor acumulado para o próximo concurso
     **/
    @ApiModelProperty(value = "Valor acumulado para o próximo concurso")
    public BigDecimal getAcumuladoParaProximoConcurso() {
        return acumuladoParaProximoConcurso;
    }

    public void setAcumuladoParaProximoConcurso(BigDecimal acumuladoParaProximoConcurso) {
        this.acumuladoParaProximoConcurso = acumuladoParaProximoConcurso;
    }

    /**
     * Identificação se o prêmio do concurso foi acumulado para o próximo
     **/
    @ApiModelProperty(value = "Identificação se o prêmio do concurso foi acumulado para o próximo")
    public Boolean getAcumulou() {
        return acumulou;
    }

    public void setAcumulou(Boolean acumulou) {
        this.acumulou = acumulou;
    }

    /**
     * Números sorteados
     **/
    @ApiModelProperty(value = "Números sorteados")
    public T getNumerosSorteadosPrimeiroSorteio() {
        return numerosSorteadosPrimeiroSorteio;
    }

    public void setNumerosSorteadosPrimeiroSorteio(T numerosSorteadosPrimeiroSorteio) {
        this.numerosSorteadosPrimeiroSorteio = numerosSorteadosPrimeiroSorteio;
    }

    public List<Integer> getListaSorteadosPrimeiroSorteio(){
        if(numerosSorteadosPrimeiroSorteio != null){
            return AppUtils.converteListaInteiros((List<Integer>) numerosSorteadosPrimeiroSorteio);
        } else  {
            return  null;
        }
    }

    public ArrayList<ArrayList<Integer>> getMatrizNumerosSorteadosPrimeiroSorteio(){
        return AppUtils.converteMatrizInteiros((List<List<Integer>>) numerosSorteadosPrimeiroSorteio);
    }
    /**
     * Números sorteados no segundo sorteio, válidos apenas para DuplaSena
     **/
    @ApiModelProperty(value = "Números sorteados no segundo sorteio, válidos apenas para DuplaSena")
    public List<Integer> getNumerosSorteadosSegundoSorteio() {
        return numerosSorteadosSegundoSorteio;
    }

    public void setNumerosSorteadosSegundoSorteio(List<Integer> numerosSorteadosSegundoSorteio) {
        this.numerosSorteadosSegundoSorteio = numerosSorteadosSegundoSorteio;
    }

    public List<Integer> getListaSorteadosSegundoSorteio(){
        if(numerosSorteadosSegundoSorteio != null){
            return AppUtils.converteListaInteiros((List<Integer>) numerosSorteadosSegundoSorteio);
        } else  {
            return  null;
        }
    }

    /**
     * Resultado das partidas de futebol da Lotogol
     **/
    @ApiModelProperty(value = "Resultado das partidas de futebol da Lotogol")
    public List<PartidaLotogolDTO> getPartidasLotogol() {
        return partidasLotogol;
    }

    public void setPartidasLotogol(List<PartidaLotogolDTO> partidasLotogol) {
        this.partidasLotogol = partidasLotogol;
    }

    /**
     * Resultado das partidas da Loteca
     **/
    @ApiModelProperty(value = "Resultado das partidas da Loteca")
    public List<PartidaLotecaDTO> getPartidasLoteca() {
        return partidasLoteca;
    }

    public void setPartidasLoteca(List<PartidaLotecaDTO> partidasLoteca) {
        this.partidasLoteca = partidasLoteca;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ConcursoDTO getConcurso() {
        return concurso;
    }

    public void setConcurso(ConcursoDTO concurso) {
        this.concurso = concurso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ConcursoDTO getProximoConcurso() {
        return proximoConcurso;
    }

    public void setProximoConcurso(ConcursoDTO proximoConcurso) {
        this.proximoConcurso = proximoConcurso;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ConcursoDTO getProximoConcursoFinalZero() {
        return proximoConcursoFinalZero;
    }

    public void setProximoConcursoFinalZero(ConcursoDTO proximoConcursoFinalZero) {
        this.proximoConcursoFinalZero = proximoConcursoFinalZero;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ConcursoDTO getProximoConcursoFinalCinco() {
        return proximoConcursoFinalCinco;
    }

    public void setProximoConcursoFinalCinco(ConcursoDTO proximoConcursoFinalCinco) {
        this.proximoConcursoFinalCinco = proximoConcursoFinalCinco;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public ConcursoDTO getProximoConcursoEspecial() {
        return proximoConcursoEspecial;
    }

    public void setProximoConcursoEspecial(ConcursoDTO proximoConcursoEspecial) {
        this.proximoConcursoEspecial = proximoConcursoEspecial;
    }

    /**
     * Lista dos prêmios relacionados como o Concurso, no caso da DuplaSena representa os prêmios do primeiro sorteio
     **/
    @ApiModelProperty(value = "Lista dos prêmios relacionados como o Concurso, no caso da DuplaSena representa os prêmios do primeiro sorteio")
    public List<PremiacaoConcursoDTO> getPremiacoesPrimeiroSorteio() {
        return premiacoesPrimeiroSorteio;
    }

    public void setPremiacoesPrimeiroSorteio(List<PremiacaoConcursoDTO> premiacoesPrimeiroSorteio) {
        this.premiacoesPrimeiroSorteio = premiacoesPrimeiroSorteio;
    }

    /**
     * Lista dos prêmios relacionados ao segundo sorteio, disponibilizado apenas para DuplaSena
     **/
    @ApiModelProperty(value = "Lista dos prêmios relacionados ao segundo sorteio, disponibilizado apenas para DuplaSena")
    public List<PremiacaoConcursoDTO> getPremiacoesSegundoSorteio() {
        return premiacoesSegundoSorteio;
    }

    public void setPremiacoesSegundoSorteio(List<PremiacaoConcursoDTO> premiacoesSegundoSorteio) {
        this.premiacoesSegundoSorteio = premiacoesSegundoSorteio;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public PremiacaoTimeDoCoracaoDTO getPremiacaoTimeDoCoracao() {
        return premiacaoTimeDoCoracao;
    }

    public void setPremiacaoTimeDoCoracao(PremiacaoTimeDoCoracaoDTO premiacaoTimeDoCoracao) {
        this.premiacaoTimeDoCoracao = premiacaoTimeDoCoracao;
    }

    public PremiacaoMesDeSorteDTO getPremiacaoMesDeSorte() {
        return premiacaoMesDeSorte;
    }

    public void setPremiacaoMesDeSorte(PremiacaoMesDeSorteDTO premiacaoMesDeSorte) {
        this.premiacaoMesDeSorte = premiacaoMesDeSorte;
    }

    /**
     * Cidade e UF em que os Prêmios saíram, para a Dupla Sena, representa as localidades ganhadoras do primeiro sorteio
     **/
    @ApiModelProperty(value = "Cidade e UF em que os Prêmios saíram, para a Dupla Sena, representa as localidades ganhadoras do primeiro sorteio")
    public List<GanhadoresPorRegiaoDTO> getGanhadoresPrimeiroSorteio() {
        return ganhadoresPrimeiroSorteio;
    }

    public void setGanhadoresPrimeiroSorteio(List<GanhadoresPorRegiaoDTO> ganhadoresPrimeiroSorteio) {
        this.ganhadoresPrimeiroSorteio = ganhadoresPrimeiroSorteio;
    }

    /**
     * Existente apenas para a DuplaSena, Cidade e UF em que os prêmios do segudo sorteio saíram
     **/
    @ApiModelProperty(value = "Existente apenas para a DuplaSena, Cidade e UF em que os prêmios do segudo sorteio saíram")
    public List<GanhadoresPorRegiaoDTO> getGanhadoresSegundoSorteio() {
        return ganhadoresSegundoSorteio;
    }

    public void setGanhadoresSegundoSorteio(List<GanhadoresPorRegiaoDTO> ganhadoresSegundoSorteio) {
        this.ganhadoresSegundoSorteio = ganhadoresSegundoSorteio;
    }

    public List<Integer> getTrevosSorteadosPrimeiroSorteio() {
        return trevosSorteadosPrimeiroSorteio;
    }

    public void setTrevosSorteadosPrimeiroSorteio(List<Integer> trevosSorteadosPrimeiroSorteio) {
        this.trevosSorteadosPrimeiroSorteio = trevosSorteadosPrimeiroSorteio;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResultadoConcursoDTO resultadoConcursoDTO = (ResultadoConcursoDTO) o;
        return (this.municipioSorteio == null ? resultadoConcursoDTO.municipioSorteio == null : this.municipioSorteio.equals(resultadoConcursoDTO.municipioSorteio)) &&
                (this.ufSorteio == null ? resultadoConcursoDTO.ufSorteio == null : this.ufSorteio.equals(resultadoConcursoDTO.ufSorteio)) &&
                (this.aviso == null ? resultadoConcursoDTO.aviso == null : this.aviso.equals(resultadoConcursoDTO.aviso)) &&
                (this.arrecadacaoTotal == null ? resultadoConcursoDTO.arrecadacaoTotal == null : this.arrecadacaoTotal.equals(resultadoConcursoDTO.arrecadacaoTotal)) &&
                (this.acumuladoParaProximoConcurso == null ? resultadoConcursoDTO.acumuladoParaProximoConcurso == null : this.acumuladoParaProximoConcurso.equals(resultadoConcursoDTO.acumuladoParaProximoConcurso)) &&
                (this.acumulou == null ? resultadoConcursoDTO.acumulou == null : this.acumulou.equals(resultadoConcursoDTO.acumulou)) &&
                (this.numerosSorteadosPrimeiroSorteio == null ? resultadoConcursoDTO.numerosSorteadosPrimeiroSorteio == null : this.numerosSorteadosPrimeiroSorteio.equals(resultadoConcursoDTO.numerosSorteadosPrimeiroSorteio)) &&
                (this.numerosSorteadosSegundoSorteio == null ? resultadoConcursoDTO.numerosSorteadosSegundoSorteio == null : this.numerosSorteadosSegundoSorteio.equals(resultadoConcursoDTO.numerosSorteadosSegundoSorteio)) &&
                (this.partidasLotogol == null ? resultadoConcursoDTO.partidasLotogol == null : this.partidasLotogol.equals(resultadoConcursoDTO.partidasLotogol)) &&
                (this.partidasLoteca == null ? resultadoConcursoDTO.partidasLoteca == null : this.partidasLoteca.equals(resultadoConcursoDTO.partidasLoteca)) &&
                (this.concurso == null ? resultadoConcursoDTO.concurso == null : this.concurso.equals(resultadoConcursoDTO.concurso)) &&
                (this.proximoConcurso == null ? resultadoConcursoDTO.proximoConcurso == null : this.proximoConcurso.equals(resultadoConcursoDTO.proximoConcurso)) &&
                (this.proximoConcursoFinalZero == null ? resultadoConcursoDTO.proximoConcursoFinalZero == null : this.proximoConcursoFinalZero.equals(resultadoConcursoDTO.proximoConcursoFinalZero)) &&
                (this.proximoConcursoFinalCinco == null ? resultadoConcursoDTO.proximoConcursoFinalCinco == null : this.proximoConcursoFinalCinco.equals(resultadoConcursoDTO.proximoConcursoFinalCinco)) &&
                (this.proximoConcursoEspecial == null ? resultadoConcursoDTO.proximoConcursoEspecial == null : this.proximoConcursoEspecial.equals(resultadoConcursoDTO.proximoConcursoEspecial)) &&
                (this.premiacoesPrimeiroSorteio == null ? resultadoConcursoDTO.premiacoesPrimeiroSorteio == null : this.premiacoesPrimeiroSorteio.equals(resultadoConcursoDTO.premiacoesPrimeiroSorteio)) &&
                (this.premiacoesSegundoSorteio == null ? resultadoConcursoDTO.premiacoesSegundoSorteio == null : this.premiacoesSegundoSorteio.equals(resultadoConcursoDTO.premiacoesSegundoSorteio)) &&
                (this.premiacaoTimeDoCoracao == null ? resultadoConcursoDTO.premiacaoTimeDoCoracao == null : this.premiacaoTimeDoCoracao.equals(resultadoConcursoDTO.premiacaoTimeDoCoracao)) &&
                (this.ganhadoresPrimeiroSorteio == null ? resultadoConcursoDTO.ganhadoresPrimeiroSorteio == null : this.ganhadoresPrimeiroSorteio.equals(resultadoConcursoDTO.ganhadoresPrimeiroSorteio)) &&
                (this.ganhadoresSegundoSorteio == null ? resultadoConcursoDTO.ganhadoresSegundoSorteio == null : this.ganhadoresSegundoSorteio.equals(resultadoConcursoDTO.ganhadoresSegundoSorteio));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.municipioSorteio == null ? 0 : this.municipioSorteio.hashCode());
        result = 31 * result + (this.ufSorteio == null ? 0 : this.ufSorteio.hashCode());
        result = 31 * result + (this.aviso == null ? 0 : this.aviso.hashCode());
        result = 31 * result + (this.arrecadacaoTotal == null ? 0 : this.arrecadacaoTotal.hashCode());
        result = 31 * result + (this.acumuladoParaProximoConcurso == null ? 0 : this.acumuladoParaProximoConcurso.hashCode());
        result = 31 * result + (this.acumulou == null ? 0 : this.acumulou.hashCode());
        result = 31 * result + (this.numerosSorteadosPrimeiroSorteio == null ? 0 : this.numerosSorteadosPrimeiroSorteio.hashCode());
        result = 31 * result + (this.numerosSorteadosSegundoSorteio == null ? 0 : this.numerosSorteadosSegundoSorteio.hashCode());
        result = 31 * result + (this.partidasLotogol == null ? 0 : this.partidasLotogol.hashCode());
        result = 31 * result + (this.partidasLoteca == null ? 0 : this.partidasLoteca.hashCode());
        result = 31 * result + (this.concurso == null ? 0 : this.concurso.hashCode());
        result = 31 * result + (this.proximoConcurso == null ? 0 : this.proximoConcurso.hashCode());
        result = 31 * result + (this.proximoConcursoFinalZero == null ? 0 : this.proximoConcursoFinalZero.hashCode());
        result = 31 * result + (this.proximoConcursoFinalCinco == null ? 0 : this.proximoConcursoFinalCinco.hashCode());
        result = 31 * result + (this.proximoConcursoEspecial == null ? 0 : this.proximoConcursoEspecial.hashCode());
        result = 31 * result + (this.premiacoesPrimeiroSorteio == null ? 0 : this.premiacoesPrimeiroSorteio.hashCode());
        result = 31 * result + (this.premiacoesSegundoSorteio == null ? 0 : this.premiacoesSegundoSorteio.hashCode());
        result = 31 * result + (this.premiacaoTimeDoCoracao == null ? 0 : this.premiacaoTimeDoCoracao.hashCode());
        result = 31 * result + (this.ganhadoresPrimeiroSorteio == null ? 0 : this.ganhadoresPrimeiroSorteio.hashCode());
        result = 31 * result + (this.ganhadoresSegundoSorteio == null ? 0 : this.ganhadoresSegundoSorteio.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ResultadoConcursoDTO {\n" +
                "  municipioSorteio: " + municipioSorteio + "\n" +
                "  ufSorteio: " + ufSorteio + "\n" +
                "  aviso: " + aviso + "\n" +
                "  arrecadacaoTotal: " + arrecadacaoTotal + "\n" +
                "  acumuladoParaProximoConcurso: " + acumuladoParaProximoConcurso + "\n" +
                "  acumulou: " + acumulou + "\n" +
                "  numerosSorteadosPrimeiroSorteio: " + numerosSorteadosPrimeiroSorteio + "\n" +
                "  numerosSorteadosSegundoSorteio: " + numerosSorteadosSegundoSorteio + "\n" +
                "  partidasLotogol: " + partidasLotogol + "\n" +
                "  partidasLoteca: " + partidasLoteca + "\n" +
                "  concurso: " + concurso + "\n" +
                "  proximoConcurso: " + proximoConcurso + "\n" +
                "  proximoConcursoFinalZero: " + proximoConcursoFinalZero + "\n" +
                "  proximoConcursoFinalCinco: " + proximoConcursoFinalCinco + "\n" +
                "  proximoConcursoEspecial: " + proximoConcursoEspecial + "\n" +
                "  premiacoesPrimeiroSorteio: " + premiacoesPrimeiroSorteio + "\n" +
                "  premiacoesSegundoSorteio: " + premiacoesSegundoSorteio + "\n" +
                "  premiacaoTimeDoCoracao: " + premiacaoTimeDoCoracao + "\n" +
                "  ganhadoresPrimeiroSorteio: " + ganhadoresPrimeiroSorteio + "\n" +
                "  ganhadoresSegundoSorteio: " + ganhadoresSegundoSorteio + "\n" +
                "}\n";
        return sb;
    }
}
