/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResultadoPesquisaPaginadaDTOHistoricoApostaDTO {
  
  @SerializedName("rowCount")
  private Long rowCount = null;
  @SerializedName("lista")
  private List<ApostaDTO> lista = null;
  @SerializedName("listaSize")
  private Integer listaSize = null;

  /**
   * Quantidade de colunas existentes para cada registro de retorno
   **/
  @ApiModelProperty(value = "Quantidade de colunas existentes para cada registro de retorno")
  public Long getRowCount() {
    return rowCount;
  }
  public void setRowCount(Long rowCount) {
    this.rowCount = rowCount;
  }

  /**
   * Registros retornados na pesquisa
   **/
  @ApiModelProperty(value = "Registros retornados na pesquisa")
  public List<ApostaDTO> getLista() {
    return lista;
  }
  public void setLista(List<ApostaDTO> lista) {
    this.lista = lista;
  }

  /**
   * Tamanho da lista
   **/
  @ApiModelProperty(value = "Tamanho da lista")
  public Integer getListaSize() {
    return listaSize;
  }
  public void setListaSize(Integer listaSize) {
    this.listaSize = listaSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultadoPesquisaPaginadaDTOHistoricoApostaDTO resultadoPesquisaPaginadaDTOHistoricoApostaDTO = (ResultadoPesquisaPaginadaDTOHistoricoApostaDTO) o;
    return (this.rowCount == null ? resultadoPesquisaPaginadaDTOHistoricoApostaDTO.rowCount == null : this.rowCount.equals(resultadoPesquisaPaginadaDTOHistoricoApostaDTO.rowCount)) &&
        (this.lista == null ? resultadoPesquisaPaginadaDTOHistoricoApostaDTO.lista == null : this.lista.equals(resultadoPesquisaPaginadaDTOHistoricoApostaDTO.lista)) &&
        (this.listaSize == null ? resultadoPesquisaPaginadaDTOHistoricoApostaDTO.listaSize == null : this.listaSize.equals(resultadoPesquisaPaginadaDTOHistoricoApostaDTO.listaSize));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.rowCount == null ? 0: this.rowCount.hashCode());
    result = 31 * result + (this.lista == null ? 0: this.lista.hashCode());
    result = 31 * result + (this.listaSize == null ? 0: this.listaSize.hashCode());
    return result;
  }

  @Override
  public String toString()  {

      String sb = "class ResultadoPesquisaPaginadaDTOHistoricoApostaDTO {\n" +
              "  rowCount: " + rowCount + "\n" +
              "  lista: " + lista + "\n" +
              "  listaSize: " + listaSize + "\n" +
              "}\n";
      return sb;
  }
}
