/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ResultadoConsultaBilheteDTO {

    @SerializedName("situacao")
    private DTOEnumLong situacao = null;
    @SerializedName("valorPremio")
    private BigDecimal valorPremio = null;
    @SerializedName("locaisParaRecebimento")
    private List<TipoPagamentoDTO> locaisParaRecebimento = null;
    @SerializedName("premio")
    private PremioDTO premioDTO = null;
    @SerializedName("modalidade")
    private ModalidadeDTO modalidadeDTO = null;

    public ModalidadeDTO getModalidadeDTO() {
        return modalidadeDTO;
    }

    public void setModalidadeDTO(ModalidadeDTO modalidadeDTO) {
        this.modalidadeDTO = modalidadeDTO;
    }

    public PremioDTO getPremioDTO() {
        return premioDTO;
    }

    public void setPremioDTO(PremioDTO premioDTO) {
        this.premioDTO = premioDTO;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public DTOEnumLong getSituacao() {
        return situacao;
    }

    public void setSituacao(DTOEnumLong situacao) {
        this.situacao = situacao;
    }

    /**
     * Valor do Prêmio, se premiado e se for abaixo do permitido para exibição
     **/
    @ApiModelProperty(value = "Valor do Prêmio, se premiado e se for abaixo do permitido para exibição")
    public BigDecimal getValorPremio() {
        return valorPremio;
    }

    public void setValorPremio(BigDecimal valorPremio) {
        this.valorPremio = valorPremio;
    }

    /**
     * Lista dos locais em que é possível receber o prêmio
     **/
    @ApiModelProperty(value = "Lista dos locais em que é possível receber o prêmio")
    public List<TipoPagamentoDTO> getLocaisParaRecebimento() {
        return locaisParaRecebimento;
    }

    public void setLocaisParaRecebimento(List<TipoPagamentoDTO> locaisParaRecebimento) {
        this.locaisParaRecebimento = locaisParaRecebimento;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResultadoConsultaBilheteDTO resultadoConsultaBilheteDTO = (ResultadoConsultaBilheteDTO) o;
        return (this.situacao == null ? resultadoConsultaBilheteDTO.situacao == null : this.situacao.equals(resultadoConsultaBilheteDTO.situacao)) &&
                (this.valorPremio == null ? resultadoConsultaBilheteDTO.valorPremio == null : this.valorPremio.equals(resultadoConsultaBilheteDTO.valorPremio)) &&
                (this.locaisParaRecebimento == null ? resultadoConsultaBilheteDTO.locaisParaRecebimento == null : this.locaisParaRecebimento.equals(resultadoConsultaBilheteDTO.locaisParaRecebimento));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.situacao == null ? 0 : this.situacao.hashCode());
        result = 31 * result + (this.valorPremio == null ? 0 : this.valorPremio.hashCode());
        result = 31 * result + (this.locaisParaRecebimento == null ? 0 : this.locaisParaRecebimento.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ResultadoConsultaBilheteDTO {\n" +
                "  situacao: " + situacao + "\n" +
                "  valorPremio: " + valorPremio + "\n" +
                "  locaisParaRecebimento: " + locaisParaRecebimento + "\n" +
                "}\n";
        return sb;
    }
}
