/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class RetornoErroMercadoPago {

    @SerializedName("message")
    private String message = null;
    @SerializedName("error")
    private String error = null;
    @SerializedName("status")
    private Integer status = null;
    @SerializedName("causeCode")
    private Integer causeCode = null;
    @SerializedName("causeMessage")
    private String causeMessage = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getCauseCode() {
        return causeCode;
    }

    public void setCauseCode(Integer causeCode) {
        this.causeCode = causeCode;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getCauseMessage() {
        return causeMessage;
    }

    public void setCauseMessage(String causeMessage) {
        this.causeMessage = causeMessage;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RetornoErroMercadoPago retornoErroMercadoPago = (RetornoErroMercadoPago) o;
        return (this.message == null ? retornoErroMercadoPago.message == null : this.message.equals(retornoErroMercadoPago.message)) &&
                (this.error == null ? retornoErroMercadoPago.error == null : this.error.equals(retornoErroMercadoPago.error)) &&
                (this.status == null ? retornoErroMercadoPago.status == null : this.status.equals(retornoErroMercadoPago.status)) &&
                (this.causeCode == null ? retornoErroMercadoPago.causeCode == null : this.causeCode.equals(retornoErroMercadoPago.causeCode)) &&
                (this.causeMessage == null ? retornoErroMercadoPago.causeMessage == null : this.causeMessage.equals(retornoErroMercadoPago.causeMessage));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.message == null ? 0 : this.message.hashCode());
        result = 31 * result + (this.error == null ? 0 : this.error.hashCode());
        result = 31 * result + (this.status == null ? 0 : this.status.hashCode());
        result = 31 * result + (this.causeCode == null ? 0 : this.causeCode.hashCode());
        result = 31 * result + (this.causeMessage == null ? 0 : this.causeMessage.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class RetornoErroMercadoPago {\n" +
                "  message: " + message + "\n" +
                "  error: " + error + "\n" +
                "  status: " + status + "\n" +
                "  causeCode: " + causeCode + "\n" +
                "  causeMessage: " + causeMessage + "\n" +
                "}\n";
        return sb;
    }
}
