/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RetornoIniciaPagamentoExternoDTO
 */
public class RetornoIniciaPagamentoExternoDTO {
  @SerializedName("idCompra")
  private Long idCompra = null;

  @SerializedName("enderecoExterno")
  private String enderecoExterno = null;

  public RetornoIniciaPagamentoExternoDTO idCompra(Long idCompra) {
    this.idCompra = idCompra;
    return this;
  }

   /**
   * Identificação da Compra
   * @return idCompra
  **/
  @ApiModelProperty(value = "Identificação da Compra")
  public Long getIdCompra() {
    return idCompra;
  }

  public void setIdCompra(Long idCompra) {
    this.idCompra = idCompra;
  }

  public RetornoIniciaPagamentoExternoDTO enderecoExterno(String enderecoExterno) {
    this.enderecoExterno = enderecoExterno;
    return this;
  }

   /**
   * URL de pagamento externo
   * @return enderecoExterno
  **/
  @ApiModelProperty(value = "URL de pagamento externo")
  public String getEnderecoExterno() {
    return enderecoExterno;
  }

  public void setEnderecoExterno(String enderecoExterno) {
    this.enderecoExterno = enderecoExterno;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetornoIniciaPagamentoExternoDTO retornoIniciaPagamentoExternoDTO = (RetornoIniciaPagamentoExternoDTO) o;
    return Objects.equals(this.idCompra, retornoIniciaPagamentoExternoDTO.idCompra) &&
        Objects.equals(this.enderecoExterno, retornoIniciaPagamentoExternoDTO.enderecoExterno);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCompra, enderecoExterno);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetornoIniciaPagamentoExternoDTO {\n");
    
    sb.append("    idCompra: ").append(toIndentedString(idCompra)).append("\n");
    sb.append("    enderecoExterno: ").append(toIndentedString(enderecoExterno)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

