/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;
import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * SalvarCarrinhoFavoritoDTO
 */
public class SalvarCarrinhoFavoritoDTO {
  @SerializedName("nome")
  private String nome = null;

  @SerializedName("manterSurpresinhas")
  private Boolean manterSurpresinhas = null;

  public SalvarCarrinhoFavoritoDTO nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome do carrinho favorito
   * @return nome
  **/
  @ApiModelProperty(value = "Nome do carrinho favorito")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public SalvarCarrinhoFavoritoDTO manterSurpresinhas(Boolean manterSurpresinhas) {
    this.manterSurpresinhas = manterSurpresinhas;
    return this;
  }

   /**
   * Status manter supresinhas em carrinho favorito
   * @return manterSurpresinhas
  **/
  @ApiModelProperty(value = "Status manter supresinhas em carrinho favorito")
  public Boolean isManterSurpresinhas() {
    return manterSurpresinhas;
  }

  public void setManterSurpresinhas(Boolean manterSurpresinhas) {
    this.manterSurpresinhas = manterSurpresinhas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalvarCarrinhoFavoritoDTO salvarCarrinhoFavoritoDTO = (SalvarCarrinhoFavoritoDTO) o;
    return Objects.equals(this.nome, salvarCarrinhoFavoritoDTO.nome) &&
        Objects.equals(this.manterSurpresinhas, salvarCarrinhoFavoritoDTO.manterSurpresinhas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nome, manterSurpresinhas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalvarCarrinhoFavoritoDTO {\n");
    
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    manterSurpresinhas: ").append(toIndentedString(manterSurpresinhas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

