/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * SecaoDTO
 */
public class SecaoDTO {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("duvidas")
  private List<DuvidaDTO> duvidas = new ArrayList<DuvidaDTO>();

  public SecaoDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Identificação da Seção
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Identificação da Seção")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SecaoDTO nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Descrição da Seção
   * @return nome
  **/
  @ApiModelProperty(required = true, value = "Descrição da Seção")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public SecaoDTO duvidas(List<DuvidaDTO> duvidas) {
    this.duvidas = duvidas;
    return this;
  }

  public SecaoDTO addDuvidasItem(DuvidaDTO duvidasItem) {
    this.duvidas.add(duvidasItem);
    return this;
  }

   /**
   * Dúvidas cadastradas nesta Seção
   * @return duvidas
  **/
  @ApiModelProperty(required = true, value = "Dúvidas cadastradas nesta Seção")
  public List<DuvidaDTO> getDuvidas() {
    return duvidas;
  }

  public void setDuvidas(List<DuvidaDTO> duvidas) {
    this.duvidas = duvidas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecaoDTO secaoDTO = (SecaoDTO) o;
    return Objects.equals(this.id, secaoDTO.id) &&
        Objects.equals(this.nome, secaoDTO.nome) &&
        Objects.equals(this.duvidas, secaoDTO.duvidas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nome, duvidas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecaoDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    duvidas: ").append(toIndentedString(duvidas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

