/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class SilceResponse<T> implements Serializable {

    @SerializedName("codigo")
    protected String codigo = null;
    @SerializedName("mensagem")
    protected String mensagem = null;
    @SerializedName("tipo")
    protected TipoEnum tipo = null;
    @SerializedName("redirect")
    protected RedirectEnum redirect = null;
    @SerializedName("errosValidacao")
    protected List<ErroValidacao> errosValidacao = null;
    @SerializedName("versao")
    private String versao = null;
    @SerializedName("payload")
    protected T payload = null;
    @SerializedName("dataHoraServidor")
    private String dataHoraServidor = null;

    /**
     * Código do erro
     **/
    @ApiModelProperty(value = "Código do erro")
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário
     **/
    @ApiModelProperty(value = "Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário")
    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * Tipo da mensagem. 1=Mensagem de usuário, 2=Mensagem de sistema, 3= Erro de validação
     **/
    @ApiModelProperty(value = "Tipo da mensagem. 1=Mensagem de usuário, 2=Mensagem de sistema, 3= Erro de validação")
    public TipoEnum getTipo() {
        return tipo;
    }

    public void setTipo(TipoEnum tipo) {
        this.tipo = tipo;
    }

    /**
     * ID da tela que o usuário deve ser redirecionado
     **/
    @ApiModelProperty(value = "ID da tela que o usuário deve ser redirecionado")
    public RedirectEnum getRedirect() {
        return redirect;
    }

    public void setRedirect(RedirectEnum redirect) {
        this.redirect = redirect;
    }

    /**
     * Lista com os erros de validação
     **/
    @ApiModelProperty(value = "Lista com os erros de validação")
    public List<ErroValidacao> getErrosValidacao() {
        return errosValidacao;
    }

    public void setErrosValidacao(List<ErroValidacao> errosValidacao) {
        this.errosValidacao = errosValidacao;
    }

    /**
     * Versão do serviço
     * @return versao
     **/
    @ApiModelProperty(value = "Versão do serviço")
    public String getVersao() {
        return versao;
    }

    public void setVersao(String versao) {
        this.versao = versao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public T getPayload() {
        return payload;
    }

    public void setPayload(T payload) {
        this.payload = payload;
    }

    public String getDataHoraServidor() {
        return dataHoraServidor;
    }

    public void setDataHoraServidor(String dataHoraServidor) {
        this.dataHoraServidor = dataHoraServidor;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SilceResponse silceResponse = (SilceResponse) o;
        return (this.codigo == null ? silceResponse.codigo == null : this.codigo.equals(silceResponse.codigo)) &&
                (this.mensagem == null ? silceResponse.mensagem == null : this.mensagem.equals(silceResponse.mensagem)) &&
                (this.tipo == null ? silceResponse.tipo == null : this.tipo.equals(silceResponse.tipo)) &&
                (this.redirect == null ? silceResponse.redirect == null : this.redirect.equals(silceResponse.redirect)) &&
                (this.errosValidacao == null ? silceResponse.errosValidacao == null : this.errosValidacao.equals(silceResponse.errosValidacao)) &&
                (this.versao == null ? silceResponse.versao == null : this.versao.equals(silceResponse.versao)) &&
                (this.payload == null ? silceResponse.payload == null : this.payload.equals(silceResponse.payload));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.codigo == null ? 0 : this.codigo.hashCode());
        result = 31 * result + (this.mensagem == null ? 0 : this.mensagem.hashCode());
        result = 31 * result + (this.tipo == null ? 0 : this.tipo.hashCode());
        result = 31 * result + (this.redirect == null ? 0 : this.redirect.hashCode());
        result = 31 * result + (this.errosValidacao == null ? 0 : this.errosValidacao.hashCode());
        result = 31 * result + (this.versao == null ? 0 : this.versao.hashCode());
        result = 31 * result + (this.payload == null ? 0 : this.payload.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ComprovanteApostaDTOResponse {\n" +
                "  codigo: " + codigo + "\n" +
                "  mensagem: " + mensagem + "\n" +
                "  tipo: " + tipo + "\n" +
                "  redirect: " + redirect + "\n" +
                "  errosValidacao: " + errosValidacao + "\n" +
                "  versao: " + versao + "\n" +
                "  payload: " + payload + "\n" +
                "}\n";
        return sb;
    }
}
