/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class SituacaoLoterica {
    @SerializedName("id")
    private Long id = null;
    @SerializedName("descricao")
    private String descricao = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SituacaoLoterica situacaoLoterica = (SituacaoLoterica) o;
        return (this.id == null ? situacaoLoterica.id == null : this.id.equals(situacaoLoterica.id)) &&
                (this.descricao == null ? situacaoLoterica.descricao == null : this.descricao.equals(situacaoLoterica.descricao));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.descricao == null ? 0 : this.descricao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class SituacaoLoterica {\n" +
                "  id: " + id + "\n" +
                "  descricao: " + descricao + "\n" +
                "}\n";
        return sb;
    }
}
