/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class Telefone {

    @SerializedName("ddd")
    private Integer ddd = null;
    @SerializedName("numero")
    private Integer numero = null;
    @SerializedName("numeroMascarado")
    private String numeroMascarado = null;
    @SerializedName("numeroCompletoSemMascara")
    private String numeroCompletoSemMascara = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getDdd() {
        return ddd;
    }

    public void setDdd(Integer ddd) {
        this.ddd = ddd;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNumeroMascarado() {
        return numeroMascarado;
    }

    public void setNumeroMascarado(String numeroMascarado) {
        this.numeroMascarado = numeroMascarado;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getNumeroCompletoSemMascara() {
        return numeroCompletoSemMascara;
    }

    public void setNumeroCompletoSemMascara(String numeroCompletoSemMascara) {
        this.numeroCompletoSemMascara = numeroCompletoSemMascara;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Telefone telefone = (Telefone) o;
        return (this.ddd == null ? telefone.ddd == null : this.ddd.equals(telefone.ddd)) &&
                (this.numero == null ? telefone.numero == null : this.numero.equals(telefone.numero)) &&
                (this.numeroMascarado == null ? telefone.numeroMascarado == null : this.numeroMascarado.equals(telefone.numeroMascarado)) &&
                (this.numeroCompletoSemMascara == null ? telefone.numeroCompletoSemMascara == null : this.numeroCompletoSemMascara.equals(telefone.numeroCompletoSemMascara));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.ddd == null ? 0 : this.ddd.hashCode());
        result = 31 * result + (this.numero == null ? 0 : this.numero.hashCode());
        result = 31 * result + (this.numeroMascarado == null ? 0 : this.numeroMascarado.hashCode());
        result = 31 * result + (this.numeroCompletoSemMascara == null ? 0 : this.numeroCompletoSemMascara.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class Telefone {\n" +
                "  ddd: " + ddd + "\n" +
                "  numero: " + numero + "\n" +
                "  numeroMascarado: " + numeroMascarado + "\n" +
                "  numeroCompletoSemMascara: " + numeroCompletoSemMascara + "\n" +
                "}\n";
        return sb;
    }
}
