/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class TermoDeUso {

    @SerializedName("id")
    private Long id = null;
    @SerializedName("conteudo")
    private String conteudo = null;
    @SerializedName("dataInicioVigencia")
    private Data dataInicioVigencia = null;
    @SerializedName("dataCriacao")
    private Data dataCriacao = null;
    @SerializedName("dataUltimaAlteracao")
    private Data dataUltimaAlteracao = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getConteudo() {
        return conteudo;
    }

    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataInicioVigencia() {
        return dataInicioVigencia;
    }

    public void setDataInicioVigencia(Data dataInicioVigencia) {
        this.dataInicioVigencia = dataInicioVigencia;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataCriacao() {
        return dataCriacao;
    }

    public void setDataCriacao(Data dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Data getDataUltimaAlteracao() {
        return dataUltimaAlteracao;
    }

    public void setDataUltimaAlteracao(Data dataUltimaAlteracao) {
        this.dataUltimaAlteracao = dataUltimaAlteracao;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TermoDeUso termoDeUso = (TermoDeUso) o;
        return (this.id == null ? termoDeUso.id == null : this.id.equals(termoDeUso.id)) &&
                (this.conteudo == null ? termoDeUso.conteudo == null : this.conteudo.equals(termoDeUso.conteudo)) &&
                (this.dataInicioVigencia == null ? termoDeUso.dataInicioVigencia == null : this.dataInicioVigencia.equals(termoDeUso.dataInicioVigencia)) &&
                (this.dataCriacao == null ? termoDeUso.dataCriacao == null : this.dataCriacao.equals(termoDeUso.dataCriacao)) &&
                (this.dataUltimaAlteracao == null ? termoDeUso.dataUltimaAlteracao == null : this.dataUltimaAlteracao.equals(termoDeUso.dataUltimaAlteracao));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.conteudo == null ? 0 : this.conteudo.hashCode());
        result = 31 * result + (this.dataInicioVigencia == null ? 0 : this.dataInicioVigencia.hashCode());
        result = 31 * result + (this.dataCriacao == null ? 0 : this.dataCriacao.hashCode());
        result = 31 * result + (this.dataUltimaAlteracao == null ? 0 : this.dataUltimaAlteracao.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class TermoDeUso {\n" +
                "  id: " + id + "\n" +
                "  conteudo: " + conteudo + "\n" +
                "  dataInicioVigencia: " + dataInicioVigencia + "\n" +
                "  dataCriacao: " + dataCriacao + "\n" +
                "  dataUltimaAlteracao: " + dataUltimaAlteracao + "\n" +
                "}\n";
        return sb;
    }
}
