/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class TermoDeUsoDTO {

    @SerializedName("conteudo")
    private String conteudo = null;

    /**
     * Conteúdo do termo de uso
     **/
    @ApiModelProperty(value = "Conteúdo do termo de uso")
    public String getConteudo() {
        return conteudo;
    }

    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TermoDeUsoDTO termoDeUsoDTO = (TermoDeUsoDTO) o;
        return (this.conteudo == null ? termoDeUsoDTO.conteudo == null : this.conteudo.equals(termoDeUsoDTO.conteudo));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.conteudo == null ? 0 : this.conteudo.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class TermoDeUsoDTO {\n" +
                "  conteudo: " + conteudo + "\n" +
                "}\n";
        return sb;
    }
}
