/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * TextoInformativoDTOResponse
 */
public class TextoInformativoDTOResponse {
  @SerializedName("codigo")
  private String codigo = null;

  @SerializedName("mensagem")
  private String mensagem = null;

  /**
   * Tipo da mensagem. 1&#x3D;Mensagem de usuário, 2&#x3D;Mensagem de sistema, 3&#x3D; Erro de validação
   */
  @JsonAdapter(TipoEnum.Adapter.class)
  public enum TipoEnum {
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    TipoEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TipoEnum fromValue(String text) {
      for (TipoEnum b : TipoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TipoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TipoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TipoEnum read(final JsonReader jsonReader) throws IOException {
        Integer value = jsonReader.nextInt();
        return TipoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("tipo")
  private TipoEnum tipo = null;

  /**
   * ID da tela que o usuário deve ser redirecionado
   */
  @JsonAdapter(RedirectEnum.Adapter.class)
  public enum RedirectEnum {
    HOME("home"),
    
    MEGA_SENA("mega-sena"),
    
    SURPRESINHAMEGASENA("surpresinhaMegaSena"),
    
    DIA_DE_SORTE("dia-de-sorte"),
    
    SURPRESINHADIADESORTE("surpresinhaDiaDeSorte"),
    
    QUINA("quina"),
    
    SURPRESINHAQUINA("surpresinhaQuina"),
    
    DUPLA_SENA("dupla-sena"),
    
    SURPRESINHADUPLASENA("surpresinhaDuplaSena"),
    
    LOTOMANIA("lotomania"),
    
    SURPRESINHALOTOMANIA("surpresinhaLotomania"),
    
    LOTOFACIL("lotofacil"),
    
    SURPRESINHALOTOFACIL("surpresinhaLotofacil"),
    
    TIMEMANIA("timemania"),
    
    SURPRESINHATIMEMANIA("surpresinhaTimemania"),
    
    LOTOGOL("lotogol"),
    
    LOTECA("loteca"),
    
    FORM_APOSTAS("form-apostas"),
    
    CARRINHO("carrinho"),
    
    CADASTRAR_APOSTADOR("cadastrar-apostador"),
    
    SELECIONAR_LOTERICA("selecionar-loterica"),
    
    ACEITAR_TERMO_DE_USO("aceitar-termo-de-uso");

    private String value;

    RedirectEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RedirectEnum fromValue(String text) {
      for (RedirectEnum b : RedirectEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RedirectEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RedirectEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RedirectEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RedirectEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("redirect")
  private RedirectEnum redirect = null;

  @SerializedName("errosValidacao")
  private List<ErroValidacao> errosValidacao = null;

  @SerializedName("versao")
  private String versao = null;

  @SerializedName("payload")
  private TextoInformativoDTO payload = null;

  public TextoInformativoDTOResponse codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Código do erro
   * @return codigo
  **/
  @ApiModelProperty(value = "Código do erro")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public TextoInformativoDTOResponse mensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário
   * @return mensagem
  **/
  @ApiModelProperty(value = "Mensagem de erro de negócio ou de erro de sistema que deve ser exibido para o usuário")
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  public TextoInformativoDTOResponse tipo(TipoEnum tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Tipo da mensagem. 1&#x3D;Mensagem de usuário, 2&#x3D;Mensagem de sistema, 3&#x3D; Erro de validação
   * @return tipo
  **/
  @ApiModelProperty(value = "Tipo da mensagem. 1=Mensagem de usuário, 2=Mensagem de sistema, 3= Erro de validação")
  public TipoEnum getTipo() {
    return tipo;
  }

  public void setTipo(TipoEnum tipo) {
    this.tipo = tipo;
  }

  public TextoInformativoDTOResponse redirect(RedirectEnum redirect) {
    this.redirect = redirect;
    return this;
  }

   /**
   * ID da tela que o usuário deve ser redirecionado
   * @return redirect
  **/
  @ApiModelProperty(value = "ID da tela que o usuário deve ser redirecionado")
  public RedirectEnum getRedirect() {
    return redirect;
  }

  public void setRedirect(RedirectEnum redirect) {
    this.redirect = redirect;
  }

  public TextoInformativoDTOResponse errosValidacao(List<ErroValidacao> errosValidacao) {
    this.errosValidacao = errosValidacao;
    return this;
  }

  public TextoInformativoDTOResponse addErrosValidacaoItem(ErroValidacao errosValidacaoItem) {
    if (this.errosValidacao == null) {
      this.errosValidacao = new ArrayList<ErroValidacao>();
    }
    this.errosValidacao.add(errosValidacaoItem);
    return this;
  }

   /**
   * Lista com os erros de validação
   * @return errosValidacao
  **/
  @ApiModelProperty(value = "Lista com os erros de validação")
  public List<ErroValidacao> getErrosValidacao() {
    return errosValidacao;
  }

  public void setErrosValidacao(List<ErroValidacao> errosValidacao) {
    this.errosValidacao = errosValidacao;
  }

  public TextoInformativoDTOResponse versao(String versao) {
    this.versao = versao;
    return this;
  }

   /**
   * Versão do serviço
   * @return versao
  **/
  @ApiModelProperty(value = "Versão do serviço")
  public String getVersao() {
    return versao;
  }

  public void setVersao(String versao) {
    this.versao = versao;
  }

  public TextoInformativoDTOResponse payload(TextoInformativoDTO payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @ApiModelProperty(value = "")
  public TextoInformativoDTO getPayload() {
    return payload;
  }

  public void setPayload(TextoInformativoDTO payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextoInformativoDTOResponse textoInformativoDTOResponse = (TextoInformativoDTOResponse) o;
    return Objects.equals(this.codigo, textoInformativoDTOResponse.codigo) &&
        Objects.equals(this.mensagem, textoInformativoDTOResponse.mensagem) &&
        Objects.equals(this.tipo, textoInformativoDTOResponse.tipo) &&
        Objects.equals(this.redirect, textoInformativoDTOResponse.redirect) &&
        Objects.equals(this.errosValidacao, textoInformativoDTOResponse.errosValidacao) &&
        Objects.equals(this.versao, textoInformativoDTOResponse.versao) &&
        Objects.equals(this.payload, textoInformativoDTOResponse.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, mensagem, tipo, redirect, errosValidacao, versao, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextoInformativoDTOResponse {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    errosValidacao: ").append(toIndentedString(errosValidacao)).append("\n");
    sb.append("    versao: ").append(toIndentedString(versao)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

