/*
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TipoComboDTO
 */
@ApiModel(description = "")
public class TipoComboDTO implements Serializable {
  @SerializedName("codigo")
  private Integer codigo = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("descricao")
  private String descricao = null;

  @SerializedName("novo")
  private Boolean novo = null;

  public TipoComboDTO codigo(Integer codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Código do combo
   * @return codigo
  **/
  @ApiModelProperty(value = "Código do combo")
  public Integer getCodigo() {
    return codigo;
  }

  public void setCodigo(Integer codigo) {
    this.codigo = codigo;
  }

  public TipoComboDTO nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome do combo
   * @return nome
  **/
  @ApiModelProperty(value = "Nome do combo")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public TipoComboDTO descricao(String descricao) {
    this.descricao = descricao;
    return this;
  }

   /**
   * Descrição do combo
   * @return descricao
  **/
  @ApiModelProperty(value = "Descrição do combo")
  public String getDescricao() {
    return descricao;
  }

  public void setDescricao(String descricao) {
    this.descricao = descricao;
  }

  public TipoComboDTO novo(Boolean novo) {
    this.novo = novo;
    return this;
  }

   /**
   * Booleano para definir se um combo é novo
   * @return novo
  **/
  @ApiModelProperty(value = "Booleano para definir se um combo é novo")
  public Boolean isNovo() {
    return novo;
  }

  public void setNovo(Boolean novo) {
    this.novo = novo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TipoComboDTO tipoComboDTO = (TipoComboDTO) o;
    return Objects.equals(this.codigo, tipoComboDTO.codigo) &&
        Objects.equals(this.nome, tipoComboDTO.nome) &&
        Objects.equals(this.descricao, tipoComboDTO.descricao) &&
        Objects.equals(this.novo, tipoComboDTO.novo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, nome, descricao, novo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TipoComboDTO {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    descricao: ").append(toIndentedString(descricao)).append("\n");
    sb.append("    novo: ").append(toIndentedString(novo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

