/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Objeto que contêm os valores dos trevos.
 **/
@ApiModel(description = "Objeto que contêm os valores dos trevos.")
public class TrevosDTO implements Serializable {
  
  @SerializedName("prognosticoMaximoTrevo")
  protected Integer prognosticoMaximoTrevo;
  @SerializedName("quantidadeMinimaTrevo")
  protected Integer quantidadeMinimaTrevo;
  @SerializedName("quantidadeMaximaTrevo")
  protected Integer quantidadeMaximaTrevo;


  /**
   * Quantidade maxima de prognostico dos trevos.
   **/
  @ApiModelProperty(value = "Quantidade maxima de prognostico dos trevos")
  public Integer getQtdPrognostico() {
    return prognosticoMaximoTrevo;
  }
  public void setQtdPrognostico(Integer prognostico) {
    this.prognosticoMaximoTrevo = prognostico;
  }

  /**
   * Quantidade minima de trevos.
   **/
  @ApiModelProperty(value = "Quantidade minima de trevos")
  public Integer getQtdMinima() {
    return quantidadeMinimaTrevo;
  }
  public void setQtdMinimo(Integer minimo) {
    this.quantidadeMinimaTrevo = minimo;
  }

  /**
   * Quantidade maxima de trevos.
   **/
  @ApiModelProperty(value = "Quantidade maxima de trevos")
  public Integer getQtdMaxima() {
    return quantidadeMaximaTrevo;
  }
  public void setQtdMaximo(Integer maximo) {
    this.quantidadeMaximaTrevo = maximo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;
    TrevosDTO trevosDTO = (TrevosDTO) o;
    return prognosticoMaximoTrevo.equals(trevosDTO.prognosticoMaximoTrevo) &&
            quantidadeMinimaTrevo.equals(trevosDTO.quantidadeMinimaTrevo) &&
            quantidadeMaximaTrevo.equals(trevosDTO.quantidadeMaximaTrevo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prognosticoMaximoTrevo, quantidadeMinimaTrevo, quantidadeMaximaTrevo);
  }

  @Override
  public String toString() {
    return "TrevosDTO{" +
            "prognosticoMaximoTrevo=" + prognosticoMaximoTrevo +
            ", quantidadeMinimaTrevo=" + quantidadeMinimaTrevo +
            ", quantidadeMaximaTrevo=" + quantidadeMaximaTrevo +
            '}';
  }
}
