/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class UnidadeFederacaoDTO implements Serializable {

    @SerializedName("id")
    protected Long id = null;
    @SerializedName("sigla")
    protected String sigla = null;
    @SerializedName("nome")
    protected String nome = null;

    /**
     * Identificação da UF
     **/
    @ApiModelProperty(required = true, value = "Identificação da UF")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Sigla da UF
     **/
    @ApiModelProperty(value = "Sigla da UF")
    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    /**
     * Nome da UF
     **/
    @ApiModelProperty(value = "Nome da UF")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UnidadeFederacaoDTO unidadeFederacaoDTO = (UnidadeFederacaoDTO) o;
        return (this.id == null ? unidadeFederacaoDTO.id == null : this.id.equals(unidadeFederacaoDTO.id)) &&
                (this.sigla == null ? unidadeFederacaoDTO.sigla == null : this.sigla.equals(unidadeFederacaoDTO.sigla)) &&
                (this.nome == null ? unidadeFederacaoDTO.nome == null : this.nome.equals(unidadeFederacaoDTO.nome));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.sigla == null ? 0 : this.sigla.hashCode());
        result = 31 * result + (this.nome == null ? 0 : this.nome.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class UnidadeFederacaoDTO {\n" +
                "  id: " + id + "\n" +
                "  sigla: " + sigla + "\n" +
                "  nome: " + nome + "\n" +
                "}\n";
        return sb;
    }
}
