/**
 * SILCE
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.gov.caixa.loterias.apostas.model.bo.silce.dto;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ValoresPagosPorSerieDTO {

    @SerializedName("dezenhaDeMilhar")
    private String dezenhaDeMilhar = null;
    @SerializedName("bilhetesPremiados")
    private List<PremiacaoExtracaoDTO> bilhetesPremiados = null;

    /**
     * Identificação da dezena de Milhar do Bilhete Premiado
     **/
    @ApiModelProperty(value = "Identificação da dezena de Milhar do Bilhete Premiado")
    public String getDezenhaDeMilhar() {
        return dezenhaDeMilhar;
    }

    public void setDezenhaDeMilhar(String dezenhaDeMilhar) {
        this.dezenhaDeMilhar = dezenhaDeMilhar;
    }

    /**
     * Identificação dos bilhetes premiados conforme a dezena de milhar detalhada
     **/
    @ApiModelProperty(value = "Identificação dos bilhetes premiados conforme a dezena de milhar detalhada")
    public List<PremiacaoExtracaoDTO> getBilhetesPremiados() {
        return bilhetesPremiados;
    }

    public void setBilhetesPremiados(List<PremiacaoExtracaoDTO> bilhetesPremiados) {
        this.bilhetesPremiados = bilhetesPremiados;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ValoresPagosPorSerieDTO valoresPagosPorSerieDTO = (ValoresPagosPorSerieDTO) o;
        return (this.dezenhaDeMilhar == null ? valoresPagosPorSerieDTO.dezenhaDeMilhar == null : this.dezenhaDeMilhar.equals(valoresPagosPorSerieDTO.dezenhaDeMilhar)) &&
                (this.bilhetesPremiados == null ? valoresPagosPorSerieDTO.bilhetesPremiados == null : this.bilhetesPremiados.equals(valoresPagosPorSerieDTO.bilhetesPremiados));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.dezenhaDeMilhar == null ? 0 : this.dezenhaDeMilhar.hashCode());
        result = 31 * result + (this.bilhetesPremiados == null ? 0 : this.bilhetesPremiados.hashCode());
        return result;
    }

    @Override
    public String toString() {

        String sb = "class ValoresPagosPorSerieDTO {\n" +
                "  dezenhaDeMilhar: " + dezenhaDeMilhar + "\n" +
                "  bilhetesPremiados: " + bilhetesPremiados + "\n" +
                "}\n";
        return sb;
    }
}
