## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Fri Feb 13 12:21:17 BRT 2026
android.defaults.buildfeatures.buildconfig=true
android.enableJetifier=true
android.enableR8.fullMode=true
android.r8.optimizedResourceShrinking=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.useAndroidX=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.parallel=true
# =============================================================================
# VERSIONAMENTO
# =============================================================================
FARM_VERSION_CODE=230102400
DES_VERSION_CODE=230102400
PLT_VERSION_CODE=230102400
PRD_VERSION_CODE=230102400

FARM_VERSION_NAME=1.24.0
DES_VERSION_NAME=1.24.0
PLT_VERSION_NAME=1.24.0
PRD_VERSION_NAME=1.24.0
