# ============================================================================= #
#         CAIXA DEVSECOPS - TEMPLATE DO WORKFLOW DE ANDROID APK v1.0            #
# ============================================================================= #
# Este workflow é um modelo padrão para todos os desenvolvedores da Caixa.      #
# Ele automatiza processos de CI/CD.                                            #
# O workflows realiza implanção nos seguintes ambientes:                        #
# - Farm                                                                        #
# - Firebase                                                                    #
# - Nexus                                                                       #
# - Loja                                                                        #
# ============================================================================= #

# ============================================================================= #
# Nome do workflow para facilitar a identificação nas execuções                 #
# ============================================================================= #

name: Call Android Workflow

# ============================================================================= #
# Nome dinâmico da execução, útil para rastreamento e auditoria                 #
# ============================================================================= #

run-name: ${{ inputs.RUN_NAME || format('{0}_{1}_{2}.{3}', github.repository, github.ref_name, github.run_id, github.run_number) }}

# ========================================================================================================================== #
# Eventos que disparam o workflow                                                                                            #
# ========================================================================================================================== #
# push              -> Executa automaticamente em push, de acordo com os filtros                                             #
# branches          -> Filtro de execução. O workflow, no evento push, será executado apenas nas branches main e develop     #
# paths-ignore      -> Filtro de execução. O workflow, no evento push, não será executado quando existir alteração           #
#                   -> nos caminhos .github/** e no arquivo catalog-info.yaml                                                #
# pull_request      -> Executa automaticamente em pull_requests, de acordo com os filtros                                    #
# schedule          -> Executa o workflow automaticamente no horário definido pelo cron.                                     #
#                                                                                                                            #
# Documentação de referência                                                                                                 #
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow                    #
# ========================================================================================================================== #

on:
  workflow_dispatch:
    inputs:
      RUN_NAME:
        required: false
        type: string
        description: 'Nome customizado da run:'
#  push:
#    branches:
#      - main
#      - develop
#    paths-ignore:
#      - '.github/**'
#      - 'catalog-info.yaml'
#  pull_request:
#    branches:
#      - main
#      - develop
#    paths-ignore:
#      - '.github/**'
#      - 'catalog-info.yaml'

# ============================================================================================================================ #
# Permissões necessárias para o workflow interagir com o repositório de automação de CI/CD e serviços                          #
# ============================================================================================================================ #
# contents: read         -> Permite ler os arquivos do repositório                                                             #
# security-events: write -> Permite registrar eventos de segurança                                                             #
# packages: read         -> Permite ler pacotes (ex: npm, docker)                                                              #
# actions: read          -> Permite ler ações do GitHub                                                                        #
#                                                                                                                              #
# Documentação de referência                                                                                                   #
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token#modifying-the-permissions-for-the-github_token   #
# ============================================================================================================================ #

permissions:
  contents: read
  security-events: write
  actions: read
  packages: read

# ======================================================================================================================================================== #
# Definição dos jobs que serão executados                                                                                                                  #
# ======================================================================================================================================================== #
# name: CI_CD                                                                                      -> Nome do job, aparece na interface do GitHub Actions  #
# uses: caixagithub/DevSecOps-Solutions/.github/workflows/generic-android-apk-pipelines.yaml@main  -> Template reutilizado                                 #
# secrets: inherit                                                                                 -> Herda os segredos definidos no repositório principal #
#                                                                                                                                                          #
# Documentação de referência                                                                                                                               #
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-jobs                                                             #
# https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows                                                                             #
# -======================================================================================================================================================= #

jobs:
  CI_CD:
    name: CI_CD
    uses: caixagithub/DevSecOps-Solutions/.github/workflows/generic-android-apk-pipelines.yaml@main
    secrets: inherit
